### ISSUE TITLE
Blog about checklist

### ISSUE THREAD

**Issue by RachelF** [GSA/EDX#109]
## Summary
Write a blog about the go-live checklist for Digital.gov

As a federal website manager
I want to understand how to use the checklist
So that I can validate that my site meets federal web requirements

**Comment by AKM399** [comment]
does the checklist have no guidance that we can direct to?   Does digital.gov have comms people who should be doing this if we request it?
are we talking to a "federal website manager" to make sure the blog makes sense?  Should this trail your PD work, understanding who that is?

**Comment by ryanwoldatwork** [comment]
https://digital.gov/resources/checklist-of-requirements-for-federal-digital-services/?dg

**Comment by RachelF** [comment]
@AKM399 I'm the author of the checklist, I've been waiting for digital.gov team to publish it. I am (have been) a federal website manager so have clear understanding of the audience; it's not really related to the PD work.

**Comment by RachelF** [comment]
[Draft done](https://docs.google.com/document/d/1IQ9bdvR5huevFtfPW9NcCT22vkzxHvRZ00T-vN2PPIo/edit#); routing for review and OSC approval, then will submit to digital.gov

**Comment by RachelF** [comment]
https://docs.google.com/document/d/1IQ9bdvR5huevFtfPW9NcCT22vkzxHvRZ00T-vN2PPIo/edit#
@anatecture @monicas-d @gailsprinkle 
Requesting 2nd pair of eyes review by next Monday 11/30

**Comment by monicas-d** [comment]
My review is complete. Nice work!


-- 

U.S. General Services Administration

*Monica Suber-Duffy*, GCDF <http://www.cce-global.org/GCDF> and Federal
Internal Coach
<https://insite.gsa.gov/topics/training-and-development/developmental-services/coaching-services>

Organizational Development Consultant
<https://insite.gsa.gov/topics/training-and-development/developmental-services/organizational-development>

GSA  | OHRM Talent Development

Pronouns: She/Her/Hers

Office of Human Resources Management (OHRM)

1800 F St, NW

Washington, DC 20526

Mobile: (202) 701-8197

E-mail: ***@***.***

Join the Yoga & Mindfulness Chatter Group
<https://gsa.my.salesforce.com/_ui/core/chatter/groups/GroupProfilePage?g=0F9t0000000aU0i>,
and see our page on InSite
<https://insite.gsa.gov/topics/training-and-development/continuous-learning/yoga-mindfulness>

Between stimulus and response there is a space. In that space is our power
to choose our response. In that response lies our growth and our
freedom.-Viktor
E. Frankl

<https://insite.gsa.gov/topics/hr-pay-and-leave>

**Comment by RachelF** [comment]
I received notice that TTS _finally_ published the checklist spreadsheet today. I've also received OSC concurrence on the blog content, so I submitted to digital.gov today: https://github.com/GSA/digitalgov.gov/issues/4404
