### ISSUE TITLE
New mentor for Reach/Research/Data working group

### ISSUE THREAD

**Issue by RachelF** [GSA/EDX#111]
## Summary
Find a new Council member to replace Sarah Bryant as the Reach/Research/Data working group mentor.

As a member of the RRD working group
I want to connect with a mentor from the Digital Council
So that I can receive guidance and know that the work is endorsed by the Council

## Checklist
- [ ] Put a call out to the Council to find a new mentor
- [ ] Communicate to the group once a new mentor is identified

**Comment by ryanwoldatwork** [comment]
Should this be moved to https://github.com/GSA/wg-web-modernization/issues?

**Comment by AKM399** [comment]
more elaboration on what work you need an endorsement for?  What does the endorsement do? Who-What-Why

**Comment by RachelF** [comment]
We're restructuring the working groups; closing this
