### ISSUE TITLE
Reach out to techradar.gsa.gov team 

### ISSUE THREAD

**Issue by anatecture** [GSA/EDX#114]
## Summary

New site popped up called techradar.gsa Two problems at surface level: 

1. Site name seems likely to have trademark issues. 
2. Site claims to `"Connect and collaborate with innovators to assess emerging tech and align with past, present, and prospective efforts."` From customer perspective, what does this mean? Who is this for? How will a website facilitate connection? This seems like it might be a CoP, not a standalone site.

Private repo, but owner and owner's leadership are known. Friend of the show and DC member is going to reach out to team to find out additional context before EDX outreach. Ana will reach out from EDX.

## Additional context and links

Dev site: 
https://federalist-055cb3d0-1a3b-4653-98f1-1f64a7f195a4.app.cloud.gov/site/gsa/techradar/

Add any other context, screenshots, or links to working docs.

## Checklist

List below the specific actions to be taken

- [x] DC member reaches out to team
- [x] Ana reaches out individually to known repo owner to ask them about site name and site's stated purpose
- [ ] @AKM399 and @anatecture meet w/ techradar.gsa team to talk through their idea

**Comment by ryanwoldatwork** [comment]
Also see https://ussm.gsa.gov/m3/

**Comment by AKM399** [comment]
@AKM399 document how process and discussion operates

**Comment by AKM399** [comment]
- [ ] @anatecture creating framework for next discussion
- [ ] agenda from @AKM399 
- [ ] bringing @RachelF into meeting with techradar in two weeks to discuss them addressing the DC

I wrote up some preliminary questions to base around the next meeting and agenda - 

https://docs.google.com/document/d/1d-PmVSRIyMtv3XdfV3fEj-KHVWvWRgX7otVsJJB0-Xg/edit?usp=sharing

**Comment by anatecture** [comment]
Edited this doc a bit to break it into two separate conversations, as it seems to be trying to accomplish two separate things: 

**Discussion 1: Forwarding techradar idea** 
Turning Idea into Product: EDX design workshop 
Questions based on [Vision Statement doc](https://docs.google.com/document/d/1aoPBUvrIVweA3K-Pn4P4jWwz4t5rb5ftgrfgoTpPumw/edit)

1. From Vision statement: `The Tech Radar provides GSA IT and its customers with the industry’s strategic pulse regarding emerging IT tools, technologies, and processes.` Do you know about other teams in the GSA and federal space with similar missions? (@RachelF please list a few for us here that you referenced in our conversation) 
2. From Vision statement: `Most importantly, the Tech Radar is not meant to be a unidirectional information sharing website. It IS designed to be interactive and collaborative. It IS designed to be interactive and collaborative.` In your vision, how will you make this site interactive and collaborative? What does that look like? 

**Discussion 2: EDX Intake**
Prioritizing the Idea 

- Did you have sufficient opportunity to discuss what you are trying to accomplish? 
- Do you have a full understanding of what EDX is trying to accomplish? 
- Engagement with GSA digital ecosystem via Inventory
- Does the information collected in the Inventory make sense? 
- Do you have a full understanding of what would be required to make a site in full compliance of current GSA CX standards? 
- Do you feel equipped to make a site in compliance or discover more information about what is required of compliance?
- Is the discussion achieving the desired balance of strategy (how to accomplish your goals) vs tactics (how to stand up a compliant web page as your method for achieving those goals)?

**Comment by anatecture** [comment]
@AKM399 have we framed our next discussion w/ the TR team as a feedback opportunity on EDX intake or as a forwarding-their-idea workshop or working session?

**Comment by monicas-d** [comment]
Hi Team! My initial reaction is to the questions: 1-are you only collecting "yes" / "no" answers? If so, close ended questions are fine. If you want more qualitative data pointing to what / how they found the EDX work/process, then I recommend making these what / how //open ended questions. Your data will likely be much richer with open ended questions OR a likert scale questions (ex: Very satisfied; Somewhat satisfied; Neither satisfied nor dissatisfied; Somewhat dissatisfied; Very dissatisfied) followed by a question after some/all of them with a place to ask "Please share why you provided that answer". Happy to discuss this more on a call. Thanks!

**Comment by ryanwoldatwork** [comment]
Regarding feedback surveys: https://www.federalregister.gov/documents/2019/07/03/2019-14217/information-collection-improving-customer-experience-implementation-of-section-280-of-omb-circular

**Comment by AKM399** [comment]
@anatecture neither frame is there yet, as i am adding the agenda now, based upon your feedback i feel we go with the frame as EDX feedback with the potential to propose workshopping their idea at a future engagement if so desired.

**Comment by monicas-d** [comment]
And Ana pointed out in my meeting with her that these are interviews and
not a survey, but some of my comment still applies! THanks.


-- 

U.S. General Services Administration

*Monica Suber-Duffy*, GCDF <http://www.cce-global.org/GCDF> and Federal
Internal Coach
<https://insite.gsa.gov/topics/training-and-development/developmental-services/coaching-services>

Organizational Development Consultant
<https://insite.gsa.gov/topics/training-and-development/developmental-services/organizational-development>

GSA  | OHRM Talent Development

Pronouns: She/Her/Hers

Office of Human Resources Management (OHRM)

1800 F St, NW

Washington, DC 20526

Mobile: (202) 701-8197

E-mail: ***@***.***

Join the Yoga & Mindfulness Chatter Group
<https://gsa.my.salesforce.com/_ui/core/chatter/groups/GroupProfilePage?g=0F9t0000000aU0i>,
and see our page on InSite
<https://insite.gsa.gov/topics/training-and-development/continuous-learning/yoga-mindfulness>

Between stimulus and response there is a space. In that space is our power
to choose our response. In that response lies our growth and our
freedom.-Viktor
E. Frankl

<https://insite.gsa.gov/topics/hr-pay-and-leave>

**Comment by AKM399** [comment]
@monicas-d used your notes to make things more open ended.  Meeting is rescheduled to happen this Wednesday

**Comment by AKM399** [comment]
due to reestablish communications in FY22

**Comment by ryanwoldatwork** [comment]
Hi @AKM399, 
FY22 began Oct 1. Is this for calendar year 2022, in January?

**Comment by anatecture** [comment]
@AKM399 @ryanwoldatwork it is CY2022, not FY. Going to close this issue now, with the option to open it back up if/when we re-engage with this team. Thanks to all in this thread.

**Comment by AKM399** [comment]
https://docs.google.com/document/d/1WxXIY5WANMzjXZMd5jKIliqrENiVde6OTk2hVPCe4wQ/edit?usp=sharing

agenda - good template for future engagements.   tagging @monicas-d and @gailsprinkle so they can evaluate and fold it into comms knowledge management.

**Comment by monicas-d** [comment]
Thanks @AKM399 . We have saved that document here to incorporate into DLP messaging: https://drive.google.com/drive/folders/1AQ3E9Dcu6FfGzm8VJipslOkm3yK-AsGC
