### ISSUE TITLE
Facilitate updates to cybersecurity pages

### ISSUE THREAD

**Issue by RachelF** [GSA/EDX#116]
## Summary
Facilitate updates to GSA content on cybersecurity.

## Additional context and links
OCE facilitates conversations with, and provides guidance to FAS, OGP, CISO on how to update GSA guidance/content on cybersecurity, including new guidance for vendors on requirements in recent cyber EO.

## Checklist
- [x] Touchbase meeting 10/28
- [x] FAS drafts new content
- [x] FAS routes content through internal approval (incl. FAS, OGP, OSC)
- [x] FAS publishes new guidance for vendors
- [x] OSC works with OGP, FAS, CISO to streamline and update cybersecurity section of GSA.gov and integrate new guidance

**Comment by ryanwoldatwork** [comment]
https://www.whitehouse.gov/briefing-room/presidential-actions/2021/05/12/executive-order-on-improving-the-nations-cybersecurity/

**Comment by AKM399** [comment]
is this EDX work?   cybersecurity is within scope of CX.  It sounds like security work at heart?
