### ISSUE TITLE
Host Fall 2021 Exec Board meeting

### ISSUE THREAD

**Issue by RachelF** [GSA/EDX#117]
## Summary
Host Board meeting and follow up on action items.

## Checklist
- [x] Prepare talking points for Ed
- [x] Host meeting 11/2
  - [x] Identify note-taker (Star)
  - [x] Identify who will drive slides (RF)
  - [x] Identify speakers
- [x] Create survey to gather feedback from meeting participants
- [x] Send follow-up email and survey

As a Board member
I want to understand what the Council's been working on the past 3 months
So I can support their work

**Comment by ryanwoldatwork** [comment]
What does success look like for this meeting?
What is the goal?

**Comment by anatecture** [comment]
Is this issue ready to close?

**Comment by RachelF** [comment]
@anatecture I will close as soon as I get the meeting notes out later today

**Comment by RachelF** [comment]
Notes/survey sent 11/5
