### ISSUE TITLE
Remove USWDS Score from Touchpoints CSV export and better understand USWDS compliance

### ISSUE THREAD

**Issue by hatfieldjm4** [GSA/EDX#118]
The USWDS score is no longer a part of the Site Scanning tool's [report](https://digital.gov/guides/site-scanning/data/). The Site Scanning tool has about 10 fields related to USWDS, but does not provide an overall score. This may have been a legacy data field in SS. Tasks related to this issue include: 

- [x] Remove the "current_uswds_score" field from the Touchpoints CSV export 
- [x] Gain a better understanding of how the USWDS fields are calculated in SS tool (example: the "uswds_count" field is defined as "Calculated likelihood a site is using USWDS", but what does a score of 153 mean? I expected a %) _(Update: 12/2021: Feature deprecated by site scanner team because calculation lacked rigor)_
- [x] Determine whether the other USWDS data fields in the Site Scanning tool are sufficient to create a score _(Update 12/17/21: NO)_ 
- [x] If the existing data fields are not sufficient to create a USWDS score, determine which metrics of the USWDS we want to include. (Is ensuring the USWDS version is up-to-date sufficient enough?- _Update 12/17/2021: NO_)
- [x] If needed, communicate the need to Gray so that he can add it to the Site Scanning team's backlog 

As an EDX member, I want to be able to view USWDS compliance data for GSA websites and ensure that the data is up-to-date.
As a website owner, I want to be able to view USWDS compliance data and understand how the compliance determination or score was developed so that I have explicit steps to improve my website.

**Comment by hatfieldjm4** [comment]
It looks like the uswds_count field is just a summation of 10 other uswds fields (which doesn't provide much insight on its face): 
1. uswds_usa_classes
2. uswds_string
3. uswds_tables
4. uswds_inline_css
5. uswds_favicon
6. uswds_string_in_css
7. uswds_favicon_in_css
8. uswds_merriweather_font
9. uswds_publicsans_font
10. uswds_source_sans_font

**Comment by ryanwoldatwork** [comment]
USWDS score has been removed; merged into Touchpoints `develop` branch. 
This should go out by end of week.

**Comment by hatfieldjm4** [comment]
Thanks Ryan! 
Also, I plan on meeting with Daniel Williams from the USWDS team on Monday at 2pm EST to gather his thoughts about a good USWDS performance metric. Would you like me to add you to that invite, @ryanwoldatwork ?

**Comment by anatecture** [comment]
Update to this issue: met w/ Dan Williams, EDX CY22 will be aiding USWDS team in creating a meaningful score for USWDS. We'll do this through:

1. Re-examining the previous work done by the site scanner team in this quantification and extending it if needed
2. Working w/ the Lab at OPM team to build a rubric for the squishier parts of USWDS adoption

This work is wrapped to: GSA Strategic Plan KPI on using USWDS as a marker for 21st Century IDEA compliance.

**Comment by anatecture** [comment]
Project referenced in comment above is going forward; closing this issue and starting a new one to capture that project.
