### ISSUE TITLE
Ensure that the "last updated at" field in Touchpoints accurately shows the date of the last edit

### ISSUE THREAD

**Issue by hatfieldjm4** [GSA/EDX#119]
As a Touchpoints user, I want to know that the "last updated at" field displays the accurate date that the website entry was last edited so that I can determine whether the website data needs to be reviewed. 

Take [this site](https://touchpoints.app.cloud.gov/admin/websites/21/events), for example-- the "last updated at" date is currently 2021-10-08, but when you click on the date to view the edit log, it only shows dates in September.   @ryanwoldatwork I'm guessing this is likely a case where you edited something on the back end for the website and it didn't get registered in the logs, but I figured I'd bring it to your attention.

**Comment by ryanwoldatwork** [comment]
Thanks @hatfieldjm4.

Confirmed. Looks like adding Tags doesn't increment the date.

**Comment by anatecture** [comment]
Checking in on this @ryanwoldatwork - were you able to address this issue?

**Comment by ryanwoldatwork** [comment]
Yep. Changes to website objects are now versioned in detail, which addresses this issue.
