### ISSUE TITLE
DLP development research: Explore functionality of https://buy.gsa.gov/start-your-acquisition

### ISSUE THREAD

**Issue by gailsprinkle** [GSA/EDX#121]
The interactive lifecycle component of the DLP will serve as data collection for the EDX Team as well as a job aid for website managers and program directors. The buy.gsa.gov site walks buyers through a decision tree to determine if they are ready to begin the acquisition process. It requires answering a series of questions and uploading documents. 
Explore:

- What platform is used and who manages it?
- Are instructions imbedded in the survey?
- Is there human intervention?
- Where do these results go?

- [x] Interview Maurice Smith
- [x] Interview Amy Direda
- [ ] Draw conclusions

**Comment by gailsprinkle** [comment]
Interviewed Maurice Smith 11.3.21. Highlights of conversation:
Updated MS on DLP (have presented the ideas to him before)
Referred me to Amy Direda to discuss technical aspects of the buy.gsa.gov site. Users are external to GSA.
Discussed website manager resistance to moving content from stand-alone sites to gsa.gov. MS's ancedotal observations: 
- OSC is under-resourced to manage content
- Making changes to content is cumbersome therefore website managers want to retain control. 
- Many website managers responsibilities are 'other duties as assigned"
GS-we will interview website managers to explore resistance factors

Requested meeting with Amy DiReda for Monday, Nov 8.

**Comment by AKM399** [comment]
working with @gailsprinkle to try to work out how this would look for DLP

**Comment by gailsprinkle** [comment]
@AKM399 Please add and/or edit
Met with Amy DiReda 11/8/21. Takeaways:
What we looked at was Buy.GSA.Gov/startyouracquisition 1.0. They're working on 2.0 which is a reusable wizard.
Survey is 4 sequential steps. Moving toward more automation. They use a style guide.
How has it been received by users? Only have direct tested on one user, still designing & developing. They want:
- More description
- To save & come back to finish
- To save one entry, then create a new entry
- Use it as a job aid to determine if they're ready to buy

2.0 Is beginning as a job aid but they're adding more detail, moving toward more automation
Amy volunteered to be a tester for us.

**Comment by AKM399** [comment]
just a note that we should mock up the thing in a survey tool or google forms.

**Comment by gailsprinkle** [comment]
Conclusion:
Stay in touch with Maurice & Amy and track their progress with their reusable wizard. They don't have anything that we can adopt at the moment.
@AKM399 Yes, We've got the Proposal phase mocked up in Forms and exploring options for Touchpoints. We can launch the Proposal phase before launching the Design & Production phase. 
Closing.
