### ISSUE TITLE
Project Management Plan

### ISSUE THREAD

**Issue by AKM399** [GSA/EDX#124]
Creation of a Project Management Plan (high level)
so that we have a clear description of expected products, practices, and developing PM priorities
in order to facilitate a transfer of responsibilities when/if someone new inherits the position

## Checklist

List below the specific actions to be taken

- [x] Scope high level priorities
- [x] @anatecture consultation
- [x] #127
- [ ] add milestones
- [ ] consultations with team
- [ ] final product

**Comment by monicas-d** [comment]
@gailsprinkle and I can support this effort as well with change aspects. This is what Mark and I started last summer if it helps: https://docs.google.com/document/d/1RkEH6xPVoxmXedXqRpR6Rm3n6AOcKzYcX8ktKfwgjqs/edit

**Comment by AKM399** [comment]
Rough - in development https://docs.google.com/document/d/12YwqXac0J1XWxY9iS1NgXaJuzgBLWr9Ph_b7EhGUk1Q/edit?usp=sharing

**Comment by AKM399** [comment]
> @gailsprinkle and I can support this effort as well with change aspects. This is what Mark and I started last summer if it helps: https://docs.google.com/document/d/1RkEH6xPVoxmXedXqRpR6Rm3n6AOcKzYcX8ktKfwgjqs/edit

This helps, im starting much more high level and internally focused to the PM role, check my rough draft to get an idea of what I'm thinking.  Both docs are valid just a different purpose.

**Comment by AKM399** [comment]
Exporting step 3 to a need for a knowledge management plan

**Comment by AKM399** [comment]
@AKM399 reissue into workflow

**Comment by monicas-d** [comment]
Gail and I are happy to help @AKM399 re change. Just let us know. Thanks!

**Comment by AKM399** [comment]
closed for new ticket
