### ISSUE TITLE
ssq.gsa.gov: Working with a team to decommission a site

### ISSUE THREAD

**Issue by anatecture** [GSA/EDX#125]
## Important customer quote driving this issue: 

 "I want to note that I am not getting paid to dig through these materials. I get that the site owner is swamped but I just spent a fair amount of time digging through this list for them. The response to notifications of issues are well evolved in the service industry. “I’m sorry to hear those links are still in those materials, I will look into that” or “Thanks for bringing that to my attention, those materials are due for an update”

## Summary

Background: 
A design world colleague reached out to me because, in trying to get on schedule, he encountered an expired SSL on ssq.gsa.gov, a site he needed to access in order to do the market research required by the scheduling tasks. 

First, I confirmed that the site had the expired link. Then I used the Website Inventory to find the site, which was listed as a redirect, and the site manager, who I reached out to. She stated that: 

1. The website was no longer hers, and tagged two other people. 
2. The website should not even exist any more; it had been decommissioned. 
3. Provided me with the correct link, https://d2d.gsa.gov/report/fas-schedule-sales-query-plus-ssq
4. When I asked about fixing the broken links in the training, she said that the entire vec platform was going to be sunset in the next month, implying that she thinks that fixing the links is pointless. My editorial thought: it's not pointless to a customer trying to get on schedule circa now. 

I let her know that the site was not decommissioned nor a redirect, and asked the other people she tagged who should be the new manager. At the same time, since I was trying to solve this for a small business customer, I reached out to folks on TTS Slack to see what if they knew anyone, and was told to submit a ServiceNow ticket, which I did. 

The individuals named as website managers did not reply to the thread, so I proactively asked them who should be the manager. I got a reply, updated the manager name in the Inventory, and asked that person to please: 

1. Fix the SSL 
2. Fix + complete the redirect or 
3. Decommission entirely

If (3), then also please update the Website Inventory listing. I received no direct reply. I was pinged via email by Sarah B. that they requested decomissioning from the IT Service Desk. 

## Additional context and links

Links that were broken in the training for small businessnes trying to get on schedule: 

Seminars —
https://vec.gsa.gov/EducationalSeminarsStatusTrack?seminar=Pathway%20To%20Success (Notably section 2.7)

Documents —
https://vec.gsa.gov/resource/1510601548000/GSA_Contractor_Checklist
https://vec.gsa.gov/resource/1510601548000/PTSModule1Documents
https://vec.gsa.gov/resource/1368157644000/NCOSection3Documents
https://vec.gsa.gov/resource/1510601549000/VTBoxChap2Analyze (talks about SSQ, not SSQ+ and directs you to training materials with the bad link, but does not have the link itself)
https://vec.gsa.gov/resource/1510601548000/HelpfulHints2
https://vec.gsa.gov/resource/1510601549000/SSQInstructions508

This is the readiness assessment that REQUIRES ssq.gsa.gov to work with links to it. Also the URL on the first slide is broken due to a typo (it is ffwww.gsaelibrary but should be www.gsaelibrary)
https://vec.gsa.gov/resource/1510601548000/RASelfPDF

Also! In https://vec.gsa.gov/resource/1368157644000/NCOSection2Documents there is a URL https://72a.gsa.gov that does not resolve. The New Contractor Orientation sheds light on this and it says that contractors report their sales online here.

## Checklist

All that being said, this now means we need to: 

- [ ] Work with them to identify the right site that small business owners need.
- [ ] Relink all the links that are broken in the trainings so they link to the right site.
- [ ] Find out what's replacing vec 
- [ ] Add any new sites to the Inventory
- [ ] Evaluate those new sites 
- [ ] Consider a feature request for Site Scanner: crawling for anything that effectively takes a site offline, like expired SSL links 
- [ ] Consider a feature request for Site Scanner: crawling and flagging broken links

**Comment by anatecture** [comment]
This loops in with Nov 9 notification of vec.gsa.gov retirement. Links will need to be updated.

**Comment by AKM399** [comment]
@AKM399 tasked to investigate vec.gsa.gov platform, how they're managing the transfer for or where the features and content are going.

**Comment by monicas-d** [comment]
@gailsprinkle per our conversation, work with Aaron to come up with SOP and get comms out there about this within the DLP.

**Comment by monicas-d** [comment]
@anatecture Can we discuss what our messaging looks like when reaching out to them via email or other written comms? Thanks!

**Comment by hatfieldjm4** [comment]
@anatecture: 
Mark V. confirmed that he heard vec.gsa.gov is going away. The content is moving into gsa.gov- the existing vec site requires folks login, take training, and complete quizzes, and they are doing away with that quiz portion as a means for streamlining. **He noted that since his team manages vec.gsa.gov that he will ensure that there is a redirect from vec.gsa.gov to the content on gsa.gov.**

**Comment by anatecture** [comment]
great - thanks @hatfieldjm4 that all makes sense. Update on this: as off 11/22: site is still up and ssl cert is still broken. **servicenow has tried to get in touch with the current website manager for ssq.gsa.gov (see Inventory for name) but seems non-respondent.**

@RachelF should we bring this to the DC next week if we don't hear anything from the website manager? All that needs to happen here is for the site to be pulled down and the training links updated.

**Comment by anatecture** [comment]
update to this: ssq.gsa.gov is fully down, but no redirect and no word from that team re: if links in training have been updated to correct link.

**Comment by hatfieldjm4** [comment]
On its [Touchpoints entry](https://touchpoints.app.cloud.gov/admin/websites/471), ssq.gsa.gov is tagged as Critical Infrastructure which is very similar to the sites that I pointed out that have no endpoint or user interface. As @RachelF pointed, out: if something is tagged "critical infrastructure" then it's not considered a website per se. We have them in the inventory to track the domain, but they aren't public-facing, they exist to provide some back-end functionality. Therefore we consider them exempt from IDEA act compliance.

**Comment by monicas-d** [comment]
This is good! It goes back to our conversation a few months ago about how
we define a website...


-- 

U.S. General Services Administration

*Monica Suber-Duffy*, GCDF <http://www.cce-global.org/GCDF> and Federal
Internal Coach
<https://insite.gsa.gov/topics/training-and-development/developmental-services/coaching-services>

Organizational Development Consultant
<https://insite.gsa.gov/topics/training-and-development/developmental-services/organizational-development>

GSA  | OHRM Talent Development

Pronouns: She/Her/Hers

Office of Human Resources Management (OHRM)

1800 F St, NW

Washington, DC 20526

Mobile: (202) 701-8197

E-mail: ***@***.***

Join the Yoga & Mindfulness Chatter Group
<https://gsa.my.salesforce.com/_ui/core/chatter/groups/GroupProfilePage?g=0F9t0000000aU0i>,
and see our page on InSite
<https://insite.gsa.gov/topics/training-and-development/continuous-learning/yoga-mindfulness>

Between stimulus and response there is a space. In that space is our power
to choose our response. In that response lies our growth and our
freedom.-Viktor
E. Frankl

<https://insite.gsa.gov/topics/hr-pay-and-leave>

**Comment by anatecture** [comment]
I get that @hatfieldjm4, but the site is linked to end users in the training to get on schedule. So it might be tagged critical infrastructure, but it was presenting as public facing...except it wasn't because of the expired SSL. 

I'm not sure that any of the links in the training have been updated, which means that even though this site is now down, it's still not getting customers what they need. We need to check on that.
