### ISSUE TITLE
fedidcard.gov & https://usaccess-alp.gsa.gov/ Stage 1 (exploration) 

### ISSUE THREAD

**Issue by anatecture** [GSA/EDX#126]
## Summary

Fedidcard.gov and https://usaccess-alp.gsa.gov/ are looking to consolidate to gsa.gov. EDX was pinged by OCE to help facilitate customer experience and features/functionality transition in advance of and then in collaboration with OSC managing the content migration. 

## Additional context and links

Motivation for this consolidation came from FAS commissioner in response to teams' request for Drupal 9 migration. 

## Checklist

List below the specific actions to be taken

- [x] reach out to fedidcard team for context, meeting
- [x] read any formal customer data like reports, journey maps, survey data, or other they might be able to provide. _Update 12/09/2021: they have no customer data beyond google analytics_ 
- [x] meet with the team to understand institutional or anecdotal customer experience data _Update: met with team 12/09/2021_
- [x] map with the team the extant customer experience using the site, focusing on adjacent site on ramps and off ramps. Note: this might be where the usaccess-alp tem comes in. _Update 12/09/2021: a portion of this work will be done in a small hcd project in Jan 2022_ 
- [ ] map with the team a continuity plan so that the migration of this website and its features is painless / invisible to customers. 
- [ ] work with team and OSC on content to complete migration

**Comment by AKM399** [comment]
Results from 11/19 discussion.

@AKM399 To document DAP information and publicly accessible user research
@RachelF discuss document and plan discussion with Peter in regards to a move to GSA.gov, the cost share model and potential savings
@mvogelgesang looking into salesforce data
@anatecture mapping eco system of websites

discussion will be framed as savings and burden reduction that will free them up for other opportunities.

Connecting to @monicas-d to help manage discussion - unpack motivations and feelings.

**Comment by RachelF** [comment]
Emailed Patrick Son from gsa.gov team. Current state on their end is that Patrick met with the fedidcard team this week and asked them to document any special functionality or requirements so they can evaluate how best to integrate. He will share that with us when he receives it, and is happy to collaborate going forward.
They don't have any documentation around proposed costs savings, so maybe that is a project we tackle? Can we develop some general estimates by type of site, hosting platform, contract...? We should also get current costs from the fedidcard team so we can document savings going forward.

Also dropping this in here as further reference: https://docs.google.com/document/d/1Wz-b17xkJGXySeMNpzLrZ3I3QirCdPyxS6WRQiDNpaE/edit

**Comment by AKM399** [comment]
More to be added, and but its a start https://docs.google.com/document/d/1ch184cU87m5HMaoJdqXKx05I-kKWHhFwNJSJ2yXRyso/edit?usp=sharing

Big takeaways, Mobile is a big deal.   Some pages are losing a ton of users despite a good overall bounce rate, and page load times are often through the roof.   Next task is to look for indicators of bot scanning and make sure they're technology is consistent throughout their constellation of sites.

**Comment by anatecture** [comment]
**Preparing for meeting on 12/09.** 
Here's the team's [business case. ](https://docs.google.com/document/d/1MRNSStHM80eBWRCx78Jg6fAEqcz_R68D2mUQRpHTYq4/edit#heading=h.bjbkgzfe8wqr)

Here's the [starter agenda,](https://docs.google.com/document/d/1F4uwTJ9RlUcaC4yxQYolFUlXo9fd8adOSU5OYn3iE1s/edit) pulled from techradar conversation.

**Comment by anatecture** [comment]
tl/dr on the fedidcard meeting: 

1. They'd like to not go with a drupal migration; willing to spend their time and resources in moving somewhere else
2. They'd like to maintain a redirect for the fedidcard.gov url
3. They don't have any customer data beyond google analytics
5. They have a substantial daily burden of manually uploading some data...concerned that that burden would increase if they have to work through another team to make those changes. 

Next steps: 

1. They're willing to do a small hcd project (~4 weeks) to learn about how customers use the site. Sheila D is working to see if they can get on the agenda for a monthly meeting of their customers to talk, next one is in January. 
2. Ben is reaching out to gsa IT to see if they can get an estimate for a migration project, dollars and timeline
3. We need to talk to Sarah B to see _if_ gsa.gov can support this work, both immediate/migration-related and ongoing/program-related

**Comment by ryanwoldatwork** [comment]
I'd be happy to do a very short discovery with them regarding their burdensome data integration.

**Comment by anatecture** [comment]
That would be very helpful @ryanwoldatwork - I'm wondering the same thing: why is this a recurring burden? 

My root level question is: why do they need to update this list of open/closed locations every day? Do customers actually use the list? Is the list required my law or policy? But in the interest of meeting their immediate need to fulfill their mission, I think we leave those questions aside and figure out if there's a possibility for direct-from-data-source integration.

**Comment by anatecture** [comment]
Closing this issue as the original stage is complete: we met with the fedidcard team and determined whether or not they are amenable to folding fedidcard into another, bigger site. They *are amenable*. EDX will not elevate this to the DC. First test of the EDX engagement with teams about consolidating their site is done, and it was a success. 

EDX will work with the fedidcard team to ensure that their information and features can be supported by another site, probably gsa.gov. We will also work to help them engage with customers at a more meaningful level than just through analytics. Next stage of this work is in [issue 135.](https://github.com/GSA/EDX/issues/135)

Closing this issue. Great job, everyone.
