### ISSUE TITLE
establish knowledge management

### ISSUE THREAD

**Issue by AKM399** [GSA/EDX#127]
Create, document, and execute a strategy for knowledge management in order ensure that key information resources are readily available, documented, and structured in a manner that speaks to their application in the EDX workflow.

Goals:  
1)  Find and utilize use cases easily.
2)  onboarding members
3) reducing the burden to adopt standards

**Comment by AKM399** [comment]
Research on Issue:

https://www.kmworld.com/Articles/Editorial/ViewPoints/Agile-Knowledge-Management-(KMAgile)-106593.aspx

https://www.infoworld.com/article/3611420/knowledge-management-for-agile-and-devops-teams.html

https://globalhandwashing.org/resources/human-centered-design-for-knowledge-management-at-the-global-handwashing-partnership/

**Comment by anatecture** [comment]
this is duplicative to [issue 124](https://github.com/GSA/EDX/issues/124). closing
