### ISSUE TITLE
Follow up with site owners for unresponsive production sites on Touchpoints

### ISSUE THREAD

**Issue by hatfieldjm4** [GSA/EDX#130]
As a website user, I want to successfully connect to a website in order to access its functionality. 

In Touchpoints, I identified 8 sites that are unreachable: 

1. kibana.search.usa.gov
2. roads.fas.gsa.gov
3. identitysandbox.gov
4. pivcac.staging.login.gov
5. pivcac.prod.login.gov
6. preview.login.gov
7. app.cloud.gov
8. federalist-builder.18f.gov

I plan to follow up with the site owners to determine if the site has been decommissioned, and if not, what the plan is for that domain.

**Comment by hatfieldjm4** [comment]
@ryanwoldatwork I noticed that 7/8 of these sites are in TTS. I just wanted to check with you before reaching out to them. Is it okay if I reach out to them or would you prefer to do so? 

For reference, the site owners are:

1. kibana.search.usa.gov: dawn.mccleskey@gsa.gov
3. identitysandbox.gov: clinton.troxel@gsa.gov
4. pivcac.staging.login.gov: julia.elman@gsa.gov
5. pivcac.prod.login.gov: julia.elman@gsa.gov
6. preview.login.gov: julia.elman@gsa.gov
7. app.cloud.gov: kara.reinsel@gsa.gov
8. federalist-builder.18f.gov: kara.reinsel@gsa.gov

**Comment by ryanwoldatwork** [comment]
All those sites are marked as Critical Infrastructure, thus exist, but may not be accessible.

![Screen Shot 2021-11-22 at 2 04 39 PM](https://user-images.githubusercontent.com/64987852/142941982-0243dc51-9a72-42e0-9935-328803d44474.png)

**Comment by hatfieldjm4** [comment]
Thanks Ryan. Does this mean that they are involved in backend processes like authentication but do not directly have a UI? If so, I'm guessing there is no action needed here.

**Comment by hatfieldjm4** [comment]
Per @RachelF : if something is tagged "critical infrastructure" then it's not considered a website per se. We have them in the inventory to track the domain, but they aren't public-facing, they exist to provide some back-end functionality. 
Therefore, in the "Type of site" field on Touchpoints, we consider the sites with the following tags to be exempt from IDEA Act compliance: 

- Critical infrastructure
- API

No action is needed in following up with the POCs as mentioned in the issue, and I will close it.
