### ISSUE TITLE
Improve mobile friendliness via targeting pages

### ISSUE THREAD

**Issue by mvogelgesang** [GSA/EDX#132]
## Summary

While overall mobile friendliness of sites is important, targeting specific pages where there might be an outsized proportion of mobile users could prove to be more timely. Looking into DAP, we see some pages where 2/3rds or more of the visitors are on a mobile device. Running scans against those pages and reporting back to the site managers would be a valuable activity. 

## Additional context and links

Full dataset available on DAP (must have DAP access) at, https://analytics.google.com/analytics/web/#/analysis/a33523145w60822123p65263002/edit/9YHkNkRsQrGDxz1yWzKDUg. 

![table showing the top visited GSA pages along with the breakdown by device (mobile, desktop, tablet) for each page.](https://user-images.githubusercontent.com/4053083/143053258-5f9bc413-6b18-408e-b7b6-d6261c6ec8f6.png)

## This issue is complete when

- [ ] Analytics package template is created for this datapoint

**Comment by AKM399** [comment]
Maybe pairing this with bounce rate and comparing it to desktop?   Trying to think of how we can answer whether or not the mobile view is scaring people away.

**Comment by mvogelgesang** [comment]
@AKM399 very true, or, is the mobile experience painful and how can it be improved?

**Comment by AKM399** [comment]
I have to do a project like this for the executive data governance board.  It's in the analysis phase right now.  Let me know if you want to talk through this.  I think most of it can be done dashboarding with DAP, so its a potential low hanging fruit.

**Comment by AKM399** [comment]
RE:  Mark, folds into lighthouse and closed

**Comment by mvogelgesang** [comment]
Propose that this gets incorporated into the evaluation criteria @AKM399 could this become a dashboard that we provide?

**Comment by AKM399** [comment]
add to website evaluation year 2 reports?

**Comment by mvogelgesang** [comment]
How might we determine which pages pass this threshold for inclusion into the analytics report? 

Provide for users the following:
- a list of top mobile trafficked pages (give percentages of total traffic)

**Comment by AKM399** [comment]
Target sprint 1.  Needs meeting on books.

**Comment by mvogelgesang** [comment]
Met w/ @AKM399 we will pull top 25 pages by sessions. Columns will show URL, mobile sessions, %mobile sessions, desktop/tablet sessions, total sessions.

Guidance for web managers is to use this as a tool when prioritizing mobile UI development. For example:

|URL|Mobile Sessions | % mobile sessions | Desktop/Tablet Sessions | total sessions |
|-|-|-|-|-|
|/pageA|50,000| 50% | 50,000 | 100,000|
|/page2|50,000| 66% | 25,000 | 75,000|
|/pageZ|10,000| 66% | 5,000 | 15,000|

Our recommendation would be to optimize pages in the following order:
1. /page2
2. /pageA
3. /pageZ

**Comment by AKM399** [comment]
process incorporated into web evals year 2.
