### ISSUE TITLE
Login Systems

### ISSUE THREAD

**Issue by mvogelgesang** [GSA/EDX#137]
## Summary

A large portion of externally facing GSA sites use login systems that require users to maintain a unique set of credentials for that site. As a result, a user who may need to use multiple sites to complete a task has to manage and _hopefully_ keep organized all of those credentials. Instead, we should be pushing folks towards common solutions that limit the unique number of credentials to manage.

Investigate the primary login systems used at GSA for externally-facing systems. Need to look at how each of those solutions fit into [ICAM architecture](https://playbooks.idmanagement.gov/arch/). 

- login.gov  (@hatfieldjm4 )
- Okta (FAS) (@mvogelgesang )
- OMB Max    (@anatecture )

## Checklist

For each system, look into

- [ ] Primary audience (feds, vendors, citizen/public)
- [ ] How does a GSA team onboard?
- [ ] Costs/ Process (IAA)? 
- [ ] What constraints are there to onboarding? Financial? Technical? Identity proofing?

## Outputs

* Have each login system team present to Digital Council
* Understand long-term outlook for Max.gov

## Desired Outcomes

* Identify challenges/ misconceptions that are barriers to teams migrating to a common system
* Identify future login system for each site which is using a non-common solution
* Determine costs to switch (both development and license)

**Comment by hatfieldjm4** [comment]
@anatecture @mvogelgesang 
I spoke with LaChelle (ICAM Shared Services team) about the GSA-wide IAA for Login.gov, and she said breaking down the cost model is still in the works (possibly have it figured out by February). She said her work has been pushing app owners towards one of [three solutions](https://sites.google.com/a/gsa.gov/icam-portfolio/users/user-authentication-services?authuser=1) (SecureAuth for internal GSA, MAX for fed govt users, Login for vendors/public). I will set up a meeting with her in January to discuss.

**Comment by mvogelgesang** [comment]
Meeting notes from 1/4 
🔒 https://docs.google.com/document/d/1aMqC7pM8O14lO5k1lXfjywZtWfXDXbb4Hb4N518VTzE/edit

**Comment by AKM399** [comment]
Home office just implemented MFA on a modernization - let me know if you want me to hit them up for their alternatives analysis - im pretty sure it included some light cost modeling.

**Comment by anatecture** [comment]
ICAM User Authentication Services intake form: https://docs.google.com/forms/d/e/1FAIpQLScZsHZ5pSrZQerB_Kd1hYX5_yiXwf1CoGpVGHhG6ykslCYnSQ/viewform

**Comment by AKM399** [comment]
pair with research phase of #142

**Comment by mvogelgesang** [comment]
Suggest that we close this out once it has been fit into #142. A potential future task may be to elucidate the benefits of and strategies for switching from homegrown auth solutions to those identified by ICAM.

**Comment by mvogelgesang** [comment]
Added suggested bullets to the website evaluation findings and recommendations doc. Once merged we can close

**Comment by anatecture** [comment]
OBE. closing.
