### ISSUE TITLE
EDX + OES + USWDS Impact Eval project

### ISSUE THREAD

**Issue by anatecture** [GSA/EDX#138]
## Summary

Background: https://github.com/GSA/EDX/issues/118

EDX will be working with the USWDS and OES teams to design and perform an impact evaluation to determine whether using the USWDS results in higher accessibility scores. The scope of this evaluation is still being determined. Some open questions seem to be: 

1.  What parts of the USWDS will we count as "use" in this study? The header and footer? Navigation? Other? Only sites fully using the USWDS? 
2. Different idea: What is the correlated data that we're pulling out of scans? What's a layer deeper than scanning? 
2. What slice of accessibility will we use in this study? This needs to go beyond things that can be scanned for, like the presence of alt text, but also needs to be relatively easy for humans to evaluate. If we use something like "the presence of _good_ alt text", how do we define "good"? 

Overall user story: As a federal or public user of the USWDS, I want to know if using the USWDS positively impacts my accessibility scores. 

## Additional context and links

[OES](https://oes.gsa.gov/)
[USWDS](https://designsystem.digital.gov/) 

## Checklist

Specific actions to be taken

- [x] Meet with USWDS team to get their input on open questions: Dan Williams daniel.williams@gsa.gov and Elisa Chen (detailed from 18f) elisa.chen@gsa.gov 
- [x] Send web analytics readings to OES team so they can do grounding readings
- [x] Meet w/ OES team to get their input on open questions
- [x] Meet as large team- start drafting evaluation plan
- [x] Let OGP team know this eval is happening (@anatecture)
- [x] Let DC know this eval is happening (@anatecture) 
- [x] Calendar evaluation plan
- [x] Perform evaluation 1: correlation
- [x] Plan evaluation 2: causation
- [x] Perform evaluation 2: causation
- [x] Meet with Mike to discuss phase 2 - 3/3
- [x] Meet with USWDS team to discuss phase 2 - 3/15
- [x] Interpret evaluation
- [x] Report out
- [x] Crosswalk report findings with EDX and USWDS roadmaps to plan to make changes

**Comment by anatecture** [comment]
Sent this web analytics readings to Mike DiDomenico (OES) 

CX CoP presentation on DAP- [video](https://vimeo.com/gsavisualcommunications/review/622408992/55f268b72a) and [slide deck](https://drive.google.com/file/d/1b_QlEYO-TJf2b7XcdqEO6FrGw5VibqeL/view)
Blog: https://www.kaushik.net/avinash/
Occam's razor - just a smart analytics expert. He focuses a lot on tracking numbers that matter rather than simple counts.  Gives very plain language explanations.
Blog: https://www.webanalyticsworld.net/ - Best place to go for analytics ethics
Paper: https://www.researchgate.net/publication/290304834_Uses_limitations_and_trends_in_web_analytics - Still relevant, has a good explanation of why analytics without thoughtful design falls apart.

**Comment by AKM399** [comment]
Should we talk about setting up some listening goals on google analytics?  You can measure how often people through a specific keyboard focus as a proxy for people who are probably using assistive technology.  That creates a user segment that could be useful here.

**Comment by anatecture** [comment]
From Dan: 
2. Basic correlation vs accessibility metric or group of metrics (out of the box) 
2. specific component or interaction USWDS vis a vis accessibility 
3. deeper layer of specific interaction in terms of accessibility 
4. where there might be gaps in terms of accessibility at the point of implementation

**Comment by anatecture** [comment]
From comment above, we're taking on a version of number (2). 

[Meeting notes](https://docs.google.com/document/d/1ithydR0s8rxUMxTgAE2EAafN29Dj7LhSFfGJIcOU4kI/edit) from Mark, Eliza, Aaron, Ana meeting 01/12. tl/dr: 

Thesis: Using specific USWDS components as our starting point, we will 

1. Design and implement an evaluation to determine whether there is a correlation between use of these specific components and higher accessibility scores. We will use sites that use USWDS compared to sites that do not use USWDS to determine this. If correlation exists, we will then: 
2. Design and implement an evaluation to determine whether causation exists between use of these specific components and higher accessibility scores. 

To get started:

- [ ] @AKM399 : How does 508 scores for header, footer, colors and accordion? What does 508 do?
- [ ] @elisa chen: Top tasks - top components
- [ ] @mvogelgesang: first collection of websites that use USWDS and don’t
- [ ] @anatecture: Update Mike
- [ ] @anatecture: Ask Mike what are the cuts of data we want? Or define what sites we want to look at? If n set is not that big, @anatecture: maybe we can collect it all. 
- [ ] @anatecture: Create a project brief
- [ ] @anatecture: Ask Mike for LOE for each team

**Comment by elisaachen** [comment]
Here's what I found for "top components" from our Google Analytics based on page views. This is Oct 1 - today. 
![image](https://user-images.githubusercontent.com/56040216/149355222-ce9912ee-c02e-48fa-9cd9-dc15e47726d4.png)

**Comment by anatecture** [comment]
Documenting the catch up conversation with @oesmiked: 

1. [OES Analysis Plan](https://docs.google.com/document/d/1Kcw06JrZWud-xxOQguhpLrq5nlBSW6Qb3yPppDx_ppU/edit#)
2. **Website population:** tbd: @mvogelgesang You said yesterday that "if we scan one, we might as well scan them all..." is that accurate? Can we run the 508 scanner (whichever one we use)
3. **What are we scanning?** Going to scan the landing page + the most highly traffic-ed page of each GSA website in our population
4. **What type of eval are we doing?** On @oesmiked's recommendation, we're going to run an evaluation type called a **2 Sample T test.** Why? As I understand it: because that allows us to make comparative statements expressed in simple terms like on a 0-100 or percentage scale on this dataset in particular, instead of a simple regression which is useful when you need to maintain possibilities for comparisons across multiple, not always identical datasets and involves squishiness around outputs that are compelling and those that are weak.
5. Cuts of data needed:
    1. What are the USWDS components are we going to hook onto to indicate that a site is "using" the USWDS? Basing this on our conversation and the list of top components that @elisaachen posted above, I propose:
        1. Header
        2. Footer
        3. Accordion
        4. Button
        5. Card
        6. Alert
    6. **What 508 scanner are we going to use?** It doesn't matter which one, but we need to document it. If we use our own crawler, we need a link to that script.

**Comment by elisaachen** [comment]
@anatecture -  I believe GSA IT has a goal to have all GSA websites include USWDS' banner, footer, and identifier. Brought it up with Dan and he said "banner and identifier would be good to look for from a usage perspective, if not super interesting from an accessibility perspective since they don’t often have non-USWDS equivalents." Could we also add these two additional components?

**Comment by AKM399** [comment]
requested 508 parts:  https://docs.google.com/document/d/1XQdSBeTfhSgaavW-arm_MjeUD0VC-BqrMroeu5X-nZU/edit?usp=sharing

**Comment by mvogelgesang** [comment]
@anatecture I uploaded Lighthouse scan data here, 🔒 https://drive.google.com/drive/folders/1adLwohREqOhKM9iJbmhy81c7mGtHvM2L

**Comment by ltillery** [comment]
Test

**Comment by mvogelgesang** [comment]
@anatecture Data set along with data dictionary available at 🔒 https://docs.google.com/spreadsheets/d/1slGw3LQL_2rOi_lSge9BGyq6VD3xP0SGGcXbrwEd8qU/edit#gid=219840986

Some websites did not play nice with the scans while others did not have a most viewed page since they weren't using DAP. Finally, some sites had their homepage as the most visited page so we didn't need to scan those a second time.

**Comment by anatecture** [comment]
[OES Analysis Plan](https://docs.google.com/document/d/1Kcw06JrZWud-xxOQguhpLrq5nlBSW6Qb3yPppDx_ppU/edit#heading=h.7aw9f6422a7p), posted for time stamp to ensure data and methodology hygiene.

**Comment by anatecture** [comment]
Correlation between using USWDS and higher accessibility scores [is established!](https://docs.google.com/document/d/107CWWK35n9SeLGoMWDk2V1CcaeZHpU8e/edit)

**Comment by anatecture** [comment]
@RachelF @AKM399 I have a note up in the checklist that I need to inform OGP that this eval is happening - who in OGP needs to know, do you all think?

**Comment by RachelF** [comment]
Not sure - the OGP DC reps should be aware via your reports to DC. Perhaps that was in reference to informing the 508 team in OGP? If so, that would be Andrew Nielson andrew.nielson@gsa.gov. Might also include Chuck Popelka in that update, as the GSA 508 team lead.

**Comment by ltillery** [comment]
@anatecture Next steps - I will be sending our email addresses to Marina for access to the Digital Dashboard. Marina will be sending us the historical data file that goes back to 2017. Once we have access and the file, we can plan for the team to meet.

**Comment by mvogelgesang** [comment]
Emailed Marina with questions regarding the data gap in 2021, waiting to hear back

**Comment by AKM399** [comment]
check on october 20th post debrief....

Likely to close out after year 1.  Worth pursuing again?
