### ISSUE TITLE
Create additional tickets for: Combine FISMA system and business application inventories

### ISSUE THREAD

**Issue by hatfieldjm4** [GSA/EDX#139]
In order to eliminate duplication and confusion, the FISMA system/subsystem inventory in Archer is being compared to the business application inventory in GEAR. The goal is to have one inventory, since there is so much overlap between the two. 

This work will involve: 

- [x] Analyzing both inventories and creating one master inventory
- [x] Collaborating with the security team to agree on one master inventory
- [x] Create communication docs to socialize the intent
- [ ] Communicate any relevant changes to ISSOs and ISSMs 
- [x] Update GEAR and Archer with any changes
- [ ] Update the relationships in GEAR (between websites, technologies, etc.)

**Comment by AKM399** [comment]
RE:  Jonah, break out into several tickets

**Comment by anatecture** [comment]
@hatfieldjm4 is this an earlier version of your current business capabilities work?

**Comment by hatfieldjm4** [comment]
@anatecture No, this work is around combining the business application inventory in GEAR and the FISMA system/subsystem inventory in Archer. I just have some backend work to complete in GEAR, and then this will be completed.

**Comment by mvogelgesang** [comment]
@hatfieldjm4 I believe these changes have been incorporated into GEAR- if so, could you close?

**Comment by hatfieldjm4** [comment]
This has been incorporated in to the dev instance of GEAR and is properly functioning.
