### ISSUE TITLE
Digital Council Charter

### ISSUE THREAD

**Issue by mvogelgesang** [GSA/EDX#14]
## Summary

Review existing Digital Council Charter and revise.

## Additional context and links

[Digital Council Charter 🔒 ](https://docs.google.com/document/d/1lGYXnnmkMCMIjeVVNbXr9XfuGwX7xA-BaeyIJ0ZHS8M/edit)

**Comment by RachelF** [comment]
WORKING COPY: https://docs.google.com/document/d/1PfFJ21-_LiaBt4Nl6CFB7MfpAQZ2SAiN5kzTeCy2YoE/edit

**Comment by RachelF** [comment]
New charter was approved by the DC in July; see https://docs.google.com/document/d/1jvgFRGc9k2dVEeorvQtV2sghuCNOl8lKEh8YnfsRd8w/edit#heading=h.byb0efkvfj5k
