### ISSUE TITLE
Follow-up Interviews from Website Manager Survey (14 web managers)

### ISSUE THREAD

**Issue by gailsprinkle** [GSA/EDX#140]
## Summary

Ask follow up questions of website managers who completed the Website Manager Survey and volunteered to be interviewed. 
We are drilling down on questions such as:
How did you land in that role? What training have you had? What resources are at your disposal? Elaborate on your resistance to migrating content.
Questions and the interview schedule are under development.

## Additional context and links

List below the specific actions to be taken

- [x] Reserve 14 time slots for interviews
- [x] Send message asking for website managers to select an interview time slot
- [x] Refine Questions
- [x] Pull PD for each interviewee
- [x] Pull survey responses for each interviewee
- [x] Conduct interviews
- [x] Analyze results
- [x] Report out to EDX team (consider if anyone else should receive a briefing)
- [x] Share results with Classification to inform next steps in PD project (see Issue #113

**Comment by gailsprinkle** [comment]
The 14 Touchpoints Roster web managers who volunteered for follow-up interviews: @hatfieldjm4 

chris.lundstrom@gsa.gov
christy.hermansen@gsa.gov
dave.skender@gsa.gov
dawn.mccleskey@gsa.gov
james.bates@gsa.gov
jeffrey.fredrickson@gsa.gov
jonathan.plante@gsa.gov
kenneth.myers@gsa.gov
manish.deorukhkar@gsa.gov
michael.bloom@gsa.gov
pompa.debroy@gsa.gov
russell.oneill@gsa.gov
sheila.dawson@gsa.gov
susanne.combs@gsa.gov

[Website Manager Follow Up Interview Schedule](https://docs.google.com/spreadsheets/d/1tFyBjEFxNyMGyDFEmvWFnyMDpjm3la6xSTPeBAOgpls/edit#gid=0
)

**Comment by hatfieldjm4** [comment]
@gailsprinkle @monicas-d 
I created [this spreadsheet](https://docs.google.com/spreadsheets/d/1RBM4QErD2h6tQ-lbr_iahm8qE5naOKLjAGx2wNsPTPg/edit#gid=0) with those POCs and the websites where they are listed as site owners. As you can see, some of those POCs have multiple websites attributed to them.

**Comment by monicas-d** [comment]
Yes. I would say that Susanne Combs is not a website manager but oversees site managers. She is a division director/GS-15. Thanks for pulling this together, @hatfieldjm4 ! Great stuff! 

As discussed today, one of the draft questions currently is: Would you be willing to participate in our pilot? (what would be required in the pilot: Be available for more interviews to discuss how to improve your site over the next year)

**Comment by monicas-d** [comment]
Data analysis: https://docs.google.com/spreadsheets/d/1F0wA_-o-sVNHWi6XqH0Vyq3B-DSmsgzP3DA8a9EE39w/edit#gid=0

Presentation: https://docs.google.com/presentation/d/1F2ZoFn-2Px8l6MZVf6BGEG7vnqWXvmZQdO0g897wpzU/edit#slide=id.g114652782c8_0_0

@anatecture - the deck is the same as what we shared with Sarah, and added one slide to follow onto question 17 from the survey of what top one or two challenges people consider to be for website migrations. Check it out and let us know what you'd like us to do next. Thanks!

We are meeting with Classification Mar 2nd. Stay tuned for more on that. Thanks! Ref: GitHub issue #113

**Comment by anatecture** [comment]
The portion of the website manager identification project that this issue describes is complete. Closing.
