### ISSUE TITLE
Website Eval Protocol

### ISSUE THREAD

**Issue by RachelF** [GSA/EDX#142]
## Summary
Develop a protocol for website reviews

## Additional context and links

[Proposal](https://docs.google.com/document/d/1zro0ewvgOElrm21JMQWBFqc3_H13X9brlIDkw_oFAXQ/edit#) (work in progress)
[Working folder for website evals](https://drive.google.com/drive/folders/1aRvGDHqbdDWQ8X7zfIYMNM5f0Okwog4r)
[Sprint plan](https://app.asana.com/0/1201500521890223/timeline)

## Checklist - Process Tasks

- [x] Complete first draft
- [x] Review draft w/the team and incorporate feedback
- [x] Identify a site to test out the protocol
- [x] Conduct the test and tweak the process as needed
- [x] Identify exactly which ~80 sites we'll review in 2022
- [x] Determine the schedule for individual site reviews
- [x] Reach out to site owners 2-3 weeks beforehand, to introduce the project and schedule the review
- [x] Pull data and create the site info report for each site that is reviewed

## Checklist - Comms

Develop templates for:
- [x] Intro email (to introduce the review process and schedule the interview)
- [x] Report on findings (to send after the interview) - [Website Evaluation Findings and Action Items](https://docs.google.com/document/d/1IFkJT_yYSd2Nwmjf-7PK7P96dE6hbyqisH4NuAH3nkU/edit#)
- [x] Followup email back to website manager/team (to check in on progress)

**Comment by AKM399** [comment]
Link to sprint plan  https://app.asana.com/share/gsa/website-evaluations-draft/4927569879033/ca09e39b86d90a35ffddf0e16b6d0b55

**Comment by AKM399** [comment]
link to draft schedule https://docs.google.com/spreadsheets/d/1-zSAASvxoiVnhNlbvQU2zq50mhB3ErWjdtpVlFvPTgk/edit?usp=sharing

**Comment by AKM399** [comment]
schedule edited to remove login systems.   will be further curated on an as needed basis to consolidate similar sites under the same owner

**Comment by AKM399** [comment]
session sign up sheet https://docs.google.com/spreadsheets/d/16xaaYNzN9_WVgxOQl9sYlK1A1mVPU0JEP4pMbsNGRVo/edit?usp=sharing

**Comment by RachelF** [comment]
@AKM399 Hope you don't mind but I added lines in the table to help people stay on the right line when filling in their info. Should we add a column for "website" since we have several people who work on more than one site? Also keep in mind that 9a ET is 6a PT. Depending on who's participating in each interview, that is VERY early for many of your teammates. :)

**Comment by AKM399** [comment]
sounds good.   First week of sessions i made according to my times.  so no
worries there.   I'll discuss the rest in the edx meeting.

**Comment by RachelF** [comment]
Updated the checklist to remove references to the "pre-meeting" report; we're only providing a post-meeting report, and focus the checklist on the "process" tasks. Actual work is documented in the protocol.

**Comment by RachelF** [comment]
@AKM399 once the followup email is finalized I think we can close this.
