### ISSUE TITLE
How can Enterprise Digital Experience be measured?

### ISSUE THREAD

**Issue by ryanwoldatwork** [GSA/EDX#143]
Brainstorming on: KPI's for Digital Experience

- general work experience
- organizational service experience
- transactions, per transaction type, per system, volume

---

##### Idea

Used internally to monitor services, and perhaps for performance reporting, later.

**Comment by anatecture** [comment]
I think stater material for this can be found in our website evaluation process that we're building rn. I'll link to the issue.

**Comment by AKM399** [comment]
#142

**Comment by AKM399** [comment]
RE:  Mark.   If you take a website and constellation of links around it.   Is that way of identifying merge possibilities?
