### ISSUE TITLE
Reporting AI Guidance

### ISSUE THREAD

**Issue by ryanwoldatwork** [GSA/EDX#146]
https://www.whitehouse.gov/wp-content/uploads/2020/11/M-21-06.pdf calls to

> Agency plans are due on May 17, 2021 and should be submitted to OIRA at the following email address: Alplans@omb.eop.gov. To inform the public of each agency's planned and implemented activities, agency plans must be posted on, or be accessed from
(through a URL redirect) the following domain on the agency's website: www.[agencyname].gov/guidance. 

### Acceptance Criteria

GSA.gov/guidance includes a link to the agency plan re: AI.

**Comment by AKM399** [comment]
Note from Ryan:  Assertion.   conversed with Eric Ewing.   Whose responsibility?   Dependabot candidate.
