### ISSUE TITLE
find new website owner

### ISSUE THREAD

**Issue by ryanwoldatwork** [GSA/EDX#148]
https://touchpoints.app.cloud.gov/admin/websites/95

**Comment by ryanwoldatwork** [comment]
cc @hatfieldjm4, @mvogelgesang

**Comment by mvogelgesang** [comment]
@ryanwoldatwork I've updated the Website Manager for the Touchpoints record

**Comment by ryanwoldatwork** [comment]
thanks @mvogelgesang!
