### ISSUE TITLE
IPSS Scores

### ISSUE THREAD

**Issue by ryanwoldatwork** [GSA/EDX#149]
A dashboard was built.

### Issues

* We can't see each question

### Ideas

* Import information into a SQL database
* generate a target report
* How does employee satisfaction (IPSS) relate to customer satisfaction (CX)?

IPSS - internal survey - How do they feel about the services they receive from Organizations within the GSA (CFO, GSA IT, TTS, etc) - overall satisfaction.  A consolidated way to get feedback, rather than every office coordinating their own. 
* TODO - find example
* Target audience = Send it out to everybody in GSA. 
Respondent can select which Programs to rate.
This has been going on for 5 years

### Business Questions

* What is the general satisfaction for an internal service?
* What is General satisfaction for an internal organization?
* Can this be tied to employee retention?

**Comment by anatecture** [comment]
@ryanwoldatwork given what we've learned about the granularity of the data for IPSS, do you still see this project as a viable? Or should we close it?

**Comment by ryanwoldatwork** [comment]
I'd close it.
There are many artifacts created, so we don't have much to offer in that regard.
I do think there is an opportunity for follow-up work about how the IPSS experience might be improved (before hand, during, and after the fact).  But that'd be separate.
