### ISSUE TITLE
Senior Steering Committee (SSC) Charter

### ISSUE THREAD

**Issue by mvogelgesang** [GSA/EDX#15]
## Summary

Update Senior Steering Committee Charter

## Additional context and links

[Senior Steering Committee Charter 🔒 ](https://docs.google.com/document/d/1FqQld5y5xXWt7T7MrG_OL3csoOMyQipgIuD_qnI2RIY/edit)

**Comment by RachelF** [comment]
@amstienstra and @mvogelgesang Could you please review the remaining comments in this doc and resolve, or document additional questions, so we can wrap this up? Thanks!

**Comment by mvogelgesang** [comment]
@RachelF  and @amstienstra to meet and discuss further

**Comment by RachelF** [comment]
Comments resolved.
Next steps:
1. Review with, and get buy-in from Digital Council
2. Present to SSC/Board members for final approval
3. Incorporate/document changes to agency digital governance in the Guidelines for GSA's Digital Presence

**Comment by RachelF** [comment]
Update: Board approved the new charter on 7/27/2021.

RF submitted recommendations to OSC to update the GSA Guidelines to explain the roles of the Council and Board, as well as the updated approval process for new websites.
