### ISSUE TITLE
Finalize 2022 OCE Comms Strategic Plan

### ISSUE THREAD

**Issue by RachelF** [GSA/EDX#150]
## 2022 OCE Comms Strategic Plan
Merge EDX and OCE comms plans, and develop one plan to cover all OCE comms activities for the year.

## Additional context and links

[Draft OCE Comms Strat Plan](https://docs.google.com/document/d/1IYD7LL71Tc-ZFbIDJqVAH_oQH3yw3EKYacDh2Ydqm9Y/edit#)

## Checklist

- [x] Merge two existing draft plans
- [ ] Finalize draft
- [ ] Gain buy-in from OCE Comms team
- [ ] Gain sign-off from Ed
- [ ] Share w/OCE for office-wide adoption

**Comment by RachelF** [comment]
Rachel, Monica, and Patricia are working to finalize the draft strategic plan.

**Comment by mvogelgesang** [comment]
@RachelF is this the work you'll do with @gailsprinkle in the next 16 weeks?

**Comment by RachelF** [comment]
No. This was 2022 - going to close this and will open a new ticket for 2023
