### ISSUE TITLE
GSA Order on Collecting Customer Feedback

### ISSUE THREAD

**Issue by RachelF** [GSA/EDX#152]
## Summary

Update the GSA Order to clarify roles/responsibilities of various GSA Teams, better-organize information and guidance, and integrate new data governance structure that now exists at GSA.

## Additional context and links

[DRAFT Updated GSA Order for Customer Feedback Collection 2022](https://docs.google.com/document/d/18VHVEW2B-e1Vg74HVL016GZyoZbiLU28xW-DoZ_AHYc/edit)

## Checklist

- [x] Create first draft of new Order
- [x] Talk to Ed about scheduling a meeting w/Payman to discuss data governance
- [x] Meet with Payman
- [x] Update Order to incorporate current data governance operating processes
- [x] Finalize Order
- [ ] Present to Data teams for initial signoff
- [ ] Route through approval
- [ ] Publish
- [ ] Socialize

**Comment by AKM399** [comment]
@RachelF is this in progress or icebox?
