### ISSUE TITLE
EDX Project - Website Evaluation Project

### ISSUE THREAD

**Issue by AKM399** [GSA/EDX#156]
## Summary

Perform needed website evaluations within this fiscal year.

## Additional context and links

Add any other context, screenshots, or links to working docs.

## Checklist

List below the specific actions to be taken

- [x] #142 
- [ ] outreach
- [x] report template
- [ ] schedule meetings
- [ ] analysis
- [ ] report out

**Comment by AKM399** [comment]
Outreach task - 
 Need a mention at the end of website manager interviews #140 
engagement schedule  https://docs.google.com/spreadsheets/d/1-zSAASvxoiVnhNlbvQU2zq50mhB3ErWjdtpVlFvPTgk/edit?usp=sharing

**Comment by AKM399** [comment]
report template -  https://docs.google.com/document/d/1IFkJT_yYSd2Nwmjf-7PK7P96dE6hbyqisH4NuAH3nkU/edit?usp=sharing

**Comment by RachelF** [comment]
@AKM399 Hi, can you confirm that [this is the list of sites](https://docs.google.com/spreadsheets/d/1-zSAASvxoiVnhNlbvQU2zq50mhB3ErWjdtpVlFvPTgk/edit#gid=0) we're reviewing for this year? If so, which are the top/bottom 5 sites?

**Comment by AKM399** [comment]
The bottom 10 engagements will probably be replaced with them.  Made the list before I had dap so its a change I have coming.

**Comment by RachelF** [comment]
@AKM399 the [interview question template](https://docs.google.com/spreadsheets/d/1EjsQ5nW0wbhH-GZ-Q5OXcEE0qxVg8q8kM4rxSuMAoX0/edit#gid=0) is ready to go. Make a copy of the sheet and use when synthesizing the notes after the interview.

**Comment by anatecture** [comment]
@AKM399 can you confirm the list of websites via link in this issue and then should we close this one out?

**Comment by AKM399** [comment]
https://airtable.com/appaxAzqTVnbOf7cm/tblEc5CVjvlElEz8l/viwS3ASIi8GL74rI8?blocks=hide
