### ISSUE TITLE
Digital Service Design Project with OPM Lab

### ISSUE THREAD

**Issue by ltillery** [GSA/EDX#163]
See [full project write up](https://docs.google.com/document/d/1FqZ1X1N2MgBZUTwmMSfLOe_dExRu4c5f--yf9FE5V78/edit). Two parts to the project. 

- Executive Training
- Website Manager Training

**Briefly:** 
_Training on service design thinking - specifically how websites serve as part of a service ecosystem, the Lab at OPM suggests an interactive session that explores how to push a design practice to consider the broad landscape of touchpoints available to organizations to shape the customer experience._

**Comment by ltillery** [comment]
**Checklist**

- [ ] Have meeting on Jan 25th to discuss content mapping, talking points, and OPM Lab pitch
- [ ] Discuss evaluation component
- [ ] Create sign-up sheet 
- [ ] Feb 1st Council meeting. Announcement for training opportunity
- [ ] Feb 8th CX CoP meeting. Announcement for training opportunity
- [ ] Establish training dates for executives and website managers
- [ ] Identify website managers for training. 29/30 seats available
- [ ] Notify selectees of training dates
- [ ] First draft of training due March 1st
- [ ] April - June Training for executives and website managers
- [ ] Training Evaluation
- [ ] Final report from OPM Lab
- [ ] EDX team report and presentation
- [ ] Briefing for Robin, Katy, Traci DiMartini, Dave Shive

**Comment by anatecture** [comment]
**Background:** Digital Literacy project came out of data call project in Summer/Fall 2021: apparent that many website managers did not share definitions around website management tasks, both subjective and technical. 

Tied to: 

- [Website Evaluation Project](https://github.com/GSA/EDX/issues/156) 
- [DLP ](https://github.com/GSA/EDX/issues/104)
- [Website Manager PDs](https://github.com/GSA/EDX/issues/113)

**Comment by ltillery** [comment]
Created sign-up sheet for [web managers](https://docs.google.com/document/d/1JE6bJTvpCVNSINBzhU3UChtYXf76QAFYUq7aMF6O6K4/edit)

**Comment by anatecture** [comment]
Created sign up sheet for [executive training](https://docs.google.com/forms/d/1jYxFRnPNsYGJX8de9bVKxwNm0cuJ_eiG6YaYLnyHQV8/edit).

**Comment by ltillery** [comment]
Sign-up sheet currently has 34 responses, 9 of which are website manager/coordinator. Need to set cut off date for sign-up.

**Comment by ltillery** [comment]
[Evaluation Analysis](https://docs.google.com/document/d/1GprZUU0zNLZXSODXTidEU-b7LAUvK9W2h0NhIKZbJVk/edit#)

**Comment by anatecture** [comment]
Leadership never requested briefing, but we can produce this when and if requested. Closing.
