### ISSUE TITLE
Capture pages with transactional components and perform 508 scans

### ISSUE THREAD

**Issue by mvogelgesang** [GSA/EDX#166]
## Summary

How might we better capture pages of a site that contain transactional components like forms and zero in on those to perform accessibility scans. Pure content pages are certainly important but if someone is trying to lookup per diem rate and can't complete the form via keyboard or screen reader- they are stuck. 

## Additional context and links

Relates to our work with OES and USWDS team- are forms/transactions created using USWDS styles faring better from an accessibility standpoint than other themes/ frameworks?

## Checklist

List below the specific actions to be taken

- [ ] Create list of pages that we would like to scan for a given site
- [ ] run AMP scans against these sites, report findings
- [ ] Discuss with team how this might be used in website evaluations.

**Comment by AKM399** [comment]
content dependent?

**Comment by AKM399** [comment]
conversation with 508 team.  Give agenda and framework.  include dan williams and patterns?

**Comment by AKM399** [comment]
OBE
