### ISSUE TITLE
Teams 1 through 5 website evaluations

### ISSUE THREAD

**Issue by AKM399** [GSA/EDX#167]
Sprint covering teams 1 through 5

- [x] set appointments - https://docs.google.com/spreadsheets/d/1-zSAASvxoiVnhNlbvQU2zq50mhB3ErWjdtpVlFvPTgk/edit?usp=sharing
- [ ] check website
- [ ] View dashboard
- [ ] meet with website manager
- [ ] include notes
- [x] site scanner data https://drive.google.com/drive/folders/1_hm4FwNPufrIpmT3_H6QJPfq2cYIOZ7o
- [ ] Report

**Comment by AKM399** [comment]
Website Notes - 10x
Top line goal - getting people to submit a goal.
few minor but easily identifiable 508 mistakes - confirmed using powermapper.com
great format for showing projects in progress

Key question - site looks federal centric.   what's their level of interest in public traffic?

**Comment by AKM399** [comment]
Dashboard PDFs - 10x

https://drive.google.com/drive/folders/1fISBgf2DusslkznhQPJFX7aw9wt7bqHO?usp=sharing

**Comment by AKM399** [comment]
Invite Language Link:  https://docs.google.com/document/d/1NUcMPIuZa0fThZako3eVwA87VE52MuluIwKoiYA7U-o/edit?usp=sharing

**Comment by AKM399** [comment]
airtable:  signups:  https://airtable.com/appaxAzqTVnbOf7cm/tblEc5CVjvlElEz8l/viwS3ASIi8GL74rI8?blocks=hide

**Comment by mvogelgesang** [comment]
@AKM399 I have linked to the scan reports https://drive.google.com/drive/folders/1_hm4FwNPufrIpmT3_H6QJPfq2cYIOZ7o. The json files are rather lengthy, my next step is to consolidate the most relevant results into a smaller file.

**Comment by anatecture** [comment]
How do we want to treat this issue @AKM399 @mvogelgesang? We've re-organized how we manage these evals, so wondering if this one can be closed? Does the link to the scan reports, above, need to be re-posted somewhere?
