### ISSUE TITLE
Digital Service Design Project Evaluation Process

### ISSUE THREAD

**Issue by ltillery** [GSA/EDX#169]
## Summary

Digital Service Design project came out of data call project in Summer/Fall 2021: apparent that many website managers did not share definitions around website management tasks, both subjective and technical.

The evalutation process for the Digital Service Design Project will be done in collaboration with Mike DiDomenico from OES. We will randomly choose participants and ask them complete the post-test for the training. 

## Additional context and links

#163 Digital Service Design Project with OPM Lab

## Checklist

- [x] List of website managers
- [x] Email website manager from list about training
- [x] Mar 3 discussion with Mike (OES) on analysis planning
- [x] Mar 9 disscussion with Lab/OES on analysis planning
- [x] Website manages sign-up
- [x] Randomly select website managers
- [x] Questions for post-test
- [ ] Analysis
- [ ] Report out

**Comment by anatecture** [comment]
Project will involve issued a learning eval just after the session and at 30 days away from the session. We will not need a pre-test to determine whether the training was effective, as we will randomize the learning population as @lynette noted above. We will need to have a control sample from those not taking the training, however, in my understanding. 

The design of this eval is TBD, but will, according to Mike: 

`open or closed with closed multiple choice questions or open questions [or to] construct scenarios that apply the knowledge and see if the respondent can apply it accurately in a new context (again could be closed or open).`

**Comment by ltillery** [comment]
Mark DiDomenico will be creating analysis planning that will be shared with us. Need to set up meeting with Lab and him.

**Comment by mvogelgesang** [comment]
Retitled the DLP to Digital Service Design Project

**Comment by anatecture** [comment]
We have the data from immediately after the course. Lab is conducting their own research over the course of the next 2 weeks.

**Comment by mvogelgesang** [comment]
see Ana's comment above, closing
