### ISSUE TITLE
evaluation - USA.GOV

### ISSUE THREAD

**Issue by AKM399** [GSA/EDX#172]
Website Evaluation of 1.usa.gov - Russell Oneill

- [x] Set appointment
- [x] view dashboard
- [x] View website
- [x] load notes to github
- [x] load additional lighthouse data
- [x] meet with website manager
- [x] include notes
- [x] [report draft](https://docs.google.com/document/d/1baoZ49MEzAcVDzjDFnhVtd7ryeYEDsGQWhqWFO0BTrs/edit?usp=sharing)
- [x] Report final

**Comment by AKM399** [comment]
1/28 from 10 - 11 est with @mvogelgesang and @AKM399

**Comment by AKM399** [comment]
Dashboard - https://drive.google.com/file/d/1vtT_fAv_gllBEfpXYLGzKqbEv6gPDONx/view?usp=sharing

**Comment by anatecture** [comment]
[Notes](https://docs.google.com/document/d/1tnwlv_P1gas_ffsGkfQ_XJHoCgMlqFgf8yRXkBSnigs/edit#bookmark=id.hch10vufxblf)
[Interview spreadsheet](https://docs.google.com/spreadsheets/d/11jK8z6OiLYkKtRjRi-G9Fj9sX9mFUAKrIP8zKPvMRYg/edit#gid=0)
[Scan data](https://airtable.com/appaxAzqTVnbOf7cm/tblivzt5qEkjX7UXG/viwd7f1IvYROezpUe/recFCfkOVsXYsG1Cn?blocks=hide)

**Comment by AKM399** [comment]
@anatecture and @RachelF Report is ready for a look through

**Comment by AKM399** [comment]
https://docs.google.com/spreadsheets/d/1_co476pNRNKehEzwsrjNgEHj1jczXiIlEJr9a_ZHZZQ/edit?usp=sharing

**Comment by anatecture** [comment]
[report package complete](https://drive.google.com/drive/folders/1RuvG-uqlb7ZeXPfyjBxpJVW-TozvlHob)

**Comment by anatecture** [comment]
Note: 1.usa.gov is entirely out of compliance. RO'N states he will not shut it down until it stops getting hits, but it will continue to get hits because it is linked in old social posts. @RachelF can we put this site on discussion for DC; we need RO'N to put USWDS footer, header, banner, identifier on site and bring into AMP compliance.

**Comment by mvogelgesang** [comment]
@anatecture @RachelF lets chat through this a bit more. As I understood it, the site was still serving up redirects. However, I cannot find any example 1.usa.gov links which take me to another page via redirect. Instead I get experiences like: https://1.usa.gov/1R7guha/ and https://1.usa.gov/W3TW6h/. 

I think our recommendation should be that they create a 1.usa.gov page on usa.gov with the same content and just redirect all traffic to that page.
