### ISSUE TITLE
Evaluation - aas.gsa.gov

### ISSUE THREAD

**Issue by AKM399** [GSA/EDX#175]
Website Evaluation of aas.gsa.gov - Chris Hamm

- [x] Set appointment
- [x] view dashboard
- [x] View website
- [x] load notes to github
- [x] load additional lighthouse data
- [x] meet with website manager
- [x] include notes
- [ ] [Report](https://docs.google.com/document/d/1meWIWN-yOVm7b8cO8Ak9MIQk_C7PuAI-xU9j7-v6xGk/edit?usp=sharing)

**Comment by AKM399** [comment]
1/28 12 -1 with @AKM399 and @anatecture

**Comment by AKM399** [comment]
dashboard - https://drive.google.com/file/d/1enfzKerOtmLfSEWrnI4aiF9zYyd-BHg0/view?usp=sharing

**Comment by AKM399** [comment]
aas.gsa.gov notes - 
acquisitions site.   Bottom links of page makes me very iffy on the wed design system implementation

not bad 508  https://wave.webaim.org/report#/https://aas.gsa.gov/

not the best seo not horrible either, could use less java  https://freetools.seobility.net/en/seocheck/check?url=https%3A%2F%2Faas.gsa.gov%2F&crawltype=1

no responsive design

**Comment by anatecture** [comment]
## 1/28 Qual research interview
### Summary 
Conversation was mostly around fedsim.gsa.gov. Team is tasked w/ supporting aas.gsa.gov, but that is the parent, multi-region assisted acquisition org; fedsim is a small brand inside that org. Fedsim team considers itself the sandbox for aas.gsa.gov. Team's website management attention is focused on fedsim, not aas. 

[Full notes from interview. ](https://docs.google.com/document/d/1MrgIVTSIHB0XHOe9i1-8WlUXl8_LXWyvbBm4MOmi1AQ/edit#)

### Immediate To-Dos: 

- [ ] @mvogelgesang find and correct scanning error that causes us to see sites as not using https when they are
- [ ] Talk to BP on DC:  aas needs to go to staging site.  How might FAS want to handle this conversation? Two points of contact for the aas side are in notes doc. 
- [ ]   Build reccs doc

### Reccs doc includes: 
1. [Interview data](https://docs.google.com/spreadsheets/d/1-Bf6YIyG5E8_Mq3N-MBrFZpRo0VpJRvl0TW2S-kjJPY/edit#gid=0)
2. [Scan data](https://airtable.com/appaxAzqTVnbOf7cm/tblNnZJ11rEO2z8Nf/viwWIsAEujuzU7zbY/recM28aC0iSmXJMWg?blocks=hide)
3. **Design note:** Move Industry page to far left, as it is the most used page
4. **Design note:** Fold About us and Contact us into a single page

**Comment by AKM399** [comment]
awaiting edit pass on recommendation

**Comment by anatecture** [comment]
[report package complete](https://drive.google.com/drive/folders/1YW8D0dQE-jehAVuEoD0ihe2oF6j3R7CQ)
