### ISSUE TITLE
Evaluation - Contractdirectory.gov

### ISSUE THREAD

**Issue by AKM399** [GSA/EDX#176]
Website Evaluation of contractdirectory.gov - Christy Hermansen

- [x] Set appointment
- [x] view dashboard
- [x] View website
- [x] load notes to github
- [x] load additional lighthouse data
- [x] meet with website manager
- [x] include notes
- [ ] [Report](https://docs.google.com/document/d/1VnyQiWlXKyaTQNl7ZLv8pSkk8KjD5ppdORKYhkpeHo4/edit?usp=sharing)

**Comment by AKM399** [comment]
meeting is 2/4 4 - 5 with @RachelF and @AKM399

**Comment by AKM399** [comment]
dashboard - https://drive.google.com/file/d/1U-ijcmtyS0ScAMrV4EiOP11jCbojIYt-/view?usp=sharing

**Comment by AKM399** [comment]
Very few but very big 508 errors,

https://wave.webaim.org/report#/contractdirectory.gov

its a simple page.  

horrible SEO  https://freetools.seobility.net/en/seocheck/contractdirectory.gov

needs alot of work.  no uswds.  bad use of graphics.  top level purpose of the site is evident up front.   that is a positive.

**Comment by RachelF** [comment]
@AKM399 Is this done, can we close it?
