### ISSUE TITLE
Evaluation - accessibility.digital.gov

### ISSUE THREAD

**Issue by AKM399** [GSA/EDX#177]
Website Evaluation of accessibility.digital.gov - Toni Bonitto

- [x] Set appointment
- [x] view dashboard
- [x] View website
- [x]  Create gDrive folder
- [x]  Make copies of relevant template docs and rename to include site name in the filename
- [x]  Place copies of relevant docs in the gDrive folder
- [x] load notes to github
- [x] meet with website manager
- [x] include notes
- [x] Report

**Comment by AKM399** [comment]
2/2 from 3 - 4 with @RachelF and @gailsprinkle

**Comment by AKM399** [comment]
dashboard https://drive.google.com/file/d/1jhb70lW_AhwxenujzI5BQxHNgOemUVYP/view?usp=sharing

**Comment by AKM399** [comment]
508 is very clean.  https://wave.webaim.org/report#/accessibility.digital.gov

great seo, very few to no problems on the site  https://freetools.seobility.net/en/seocheck/accessibility.digital.gov

easy purpose - make your team accessible.

Why is there an edit button that directs me to their github?

**Comment by RachelF** [comment]
@AKM399 To your question about the edit button, all the digital.gov sites are federalist, and you can submit updates to the sites by clicking edit, and submitting an issue in github.

Interview folder: https://drive.google.com/drive/folders/1CIHv2g56E_UQGk80F1Kxw0JBv06rYsCP

**Comment by RachelF** [comment]
Met w/Toni today. Here are the [meeting notes](https://docs.google.com/document/d/1IQwVKZqVyq2K4eORE0dHGJGJxn6EqSLt6ErDhgzsrlM/edit) and [gSheet](https://docs.google.com/spreadsheets/d/1LSyQ7ecDonR438sHMYp9BBV6fv7gU3J3LQLIJO-jkzs/edit#gid=0).

Can we please rename this digital.gov? The other two sites (accessibility.digital.gov, connect.digital.gov) weren't really relevant to the discussion.

**Comment by RachelF** [comment]
Final report: https://docs.google.com/document/d/1TGbgnBsyH03Iuon9Ev32Hfj1PKgI4pNGsFA2otsOMso/edit#

**Comment by anatecture** [comment]
[Report package complete](https://drive.google.com/drive/folders/17X9RAMGLjnYhn2dGEdE0uys-abok4CRX)
