### ISSUE TITLE
Evaluation - acquisition.gov

### ISSUE THREAD

**Issue by AKM399** [GSA/EDX#178]
Website Evaluation of acquisition.gov - Heather Treadway

- [x] Set appointment
- [x] view dashboard
- [x] View website
- [x]  Create gDrive folder
- [x]  Make copies of relevant template docs and rename to include site name in the filename
- [x]  Place copies of relevant docs in the gDrive folder
- [x] load notes to github
- [ ] load additional lighthouse data
- [ ] meet with website manager
- [ ] include notes
- [ ] Report

**Comment by AKM399** [comment]
2/2 130 - 230

**Comment by AKM399** [comment]
dashboard https://drive.google.com/file/d/1Ib3azalEg1B5JGp5qc3u7zjrVSLsvqcQ/view?usp=sharing

**Comment by AKM399** [comment]
some very low hanging fruit 508 wise https://wave.webaim.org/report#/acquisition.gov

not great SEO - https://freetools.seobility.net/en/seocheck/acquisition.gov

site has a beta, makes me wonder what the timeline is.

clear purpose.  accessing the far.

site has a link to accessibility aids that is in itself not 100% on accessibility.  Thats going to frustrate some people.

**Comment by RachelF** [comment]
@AKM399 Heather was a no-show, so we'll need to reschedule.
