### ISSUE TITLE
Branding

### ISSUE THREAD

**Issue by monicas-d** [GSA/EDX#18]
Once scope is narrowed/approved, we want to think about how to brand this effort (i.e. how to promote the product(s) or service(s) by means of advertising and distinctive design). 

I encourage everyone to attend the upcoming Customer Experience Community of Practice session where Andrea Azarcon-Heller will present on branding best practices (Mar 23 from 2-2:45 pm EST).  @mvogelgesang @amstienstra @RachelF 

Also, if you haven't seen this video on GSA Change Management best practices from the transition from Lotus Notes to Google, I encourage you to watch, in particular 4:20-6:00): https://www.youtube.com/watch?v=gPyPKLkSm5c

The CIO who led the transition developed a brand of "Race to the Cloud". They used a race car to represent the change. Early adopters of the change were called "Pacers" as they helped to share how great Google was and get others on board.

Consider: When thinking about EDX in a visual, what comes to mind first?

Who is the main target audience you are using this brand to communicate? 

When speaking with political appointees to get their support, thinking about what they need to hear as to how this relates to their priorities so they put money/resources to it (ex: DEI and accessibility).

**Comment by ryanwoldatwork** [comment]
hi @monicas-d, 

I agree branding is important.

* [ ] Who is the user or users of this work?
* [ ] What is a Definition of Done for this story? How do we know when this work is complete?

**Comment by monicas-d** [comment]
Thanks @ryanwoldatwork . I think we should discuss this topic in a future comms meeting that Gail, Rachel, and I have this week.

**Comment by monicas-d** [comment]
This is why we are doing the DLP as a part of our own branding efforts.
