### ISSUE TITLE
Evaluation - fedidcard.gov

### ISSUE THREAD

**Issue by AKM399** [GSA/EDX#183]
Website Evaluation of fedidcard.gov - Shelia Dawson

- [x] Set appointment
- [ ] view dashboard
- [ ] View website
- [ ] load notes to github
- [ ] load additional lighthouse data
- [ ] meet with website manager
- [ ] include notes
- [ ] Report

**Comment by AKM399** [comment]
2/10 1230 to 100 with @mvogelgesang and @RachelF

**Comment by anatecture** [comment]
[Backstory](https://github.com/GSA/EDX/issues/126) with this team
[Current status] (https://github.com/GSA/EDX/issues/135) of this team's work with us

**Comment by mvogelgesang** [comment]
@anatecture I am copying your comment into #205 and closing this out as it is a dupe

> [Backstory](https://github.com/GSA/EDX/issues/126) with this team [Current status](https://github.com/GSA/EDX/issues/135) of this team's work with us
