### ISSUE TITLE
Evaluation - SFTools.gov

### ISSUE THREAD

**Issue by AKM399** [GSA/EDX#184]
Website Evaluation of sftools.gov - Michael Bloom

- [x] Set appointment
- [ ] view dashboard
- [ ] View website
- [ ] load notes to github
- [ ] load additional lighthouse data
- [ ] meet with website manager
- [ ] include notes
- [ ] Report

Summary
Howd it go?

Full notes from interview. <- Link

tl/dr:
big takeaways

Immediate To-Dos:
 
 
Reccs doc includes:
Interview data
Scan data
Design note: 
Design note:

**Comment by AKM399** [comment]
2/9 930 to 10 with @mvogelgesang and @AKM399

**Comment by mvogelgesang** [comment]
Looks to be a dupe of #206 closing
