### ISSUE TITLE
Evaluation - digitalcorps.gsa.gov

### ISSUE THREAD

**Issue by AKM399** [GSA/EDX#185]
Website Evaluation of digitalcorps.gsa.gov - Dave Skender

- [x] Set appointment
- [ ] view dashboard
- [ ] View website
- [ ] load notes to github
- [ ] load additional lighthouse data
- [ ] meet with website manager
- [ ] include notes
- [ ] Report

Summary
Howd it go?

Full notes from interview. <- Link

tl/dr:
big takeaways

Immediate To-Dos:
 
 
Reccs doc includes:
Interview data
Scan data
Design note: 
Design note:

**Comment by AKM399** [comment]
2/11 with @mvogelgesang and @RachelF

**Comment by RachelF** [comment]
Duplicate; closing this in favor of #207 which has more comprehensive info
