### ISSUE TITLE
Capture "Contact Us" information for websites

### ISSUE THREAD

**Issue by mvogelgesang** [GSA/EDX#188]
## Summary

Government services encompass a variety of help desks, phone numbers, and email addresses. All of which can contribute to a confusing experience for the customer/ consumer. I propose that we capture this information as a means of highlighting "forks in the road" of a customer journey. 

## Additional context and links

For example, if a customer journey involves websites A, B, C, D, and E- look to see if there are different email addresses, phone numbers, etc used along the journey. Is this a bad customer experience smell? How do we ensure folks land on the correct call center/ person on the first go?

## Checklist

List below the specific actions to be taken

- [ ] Review outputs from OCE's Call Center analysis which was conducted a few years back by John Kraden
- [ ] Save all email addresses, phone numbers, links
- [ ] Save content of any link that matches the "contact" regular expression 
https://github.com/GSA/EDX/blob/3981db936eb9668d3cc12f05500576c15a3201d6/Tools/edxcli/src/helpers/websites/it-performance-metric.ts#L47
  - [ ] #659

**Comment by AKM399** [comment]
Camille may have information on this.

**Comment by AKM399** [comment]
#491

**Comment by AKM399** [comment]
content review of websites - pre interview.  discuss with @RachelF

**Comment by mvogelgesang** [comment]
We doubled back on ourselves @RachelF , this will be a scanner task- pull back all emails and phone numbers on the page

**Comment by AKM399** [comment]
#491
