### ISSUE TITLE
apps.ocfo.gsa.gov - Feedback

### ISSUE THREAD

**Issue by mvogelgesang** [GSA/EDX#189]
## Summary

The apps.ocfo.gsa.gov team reached out regarding modernization efforts that they are undertaking. Let's look at how we engage such a team and provide the right level of feedback.

## Checklist

List below the specific actions to be taken

- [x] Provide set of recommendations back to apps.ocfo.gsa.gov team. These recommendations should be in the form an email style updates (USWDS use, CSS, HTML updates) and a conversation asking questions from the [website evaluation protocol](https://docs.google.com/document/d/1a6tPuAddnHWh4EG20a3FXl3KMjsPNHLmd758ZdwijXo/edit).  
  - [Recommendations](https://drive.google.com/drive/folders/1j8tfsptuEXCdn0axfczntpJF34P5RQTc)
- [x] Determine how we want to track these recommendations and the from/to state of a site. Having visual aids can say a lot. 
- [x] Before/ after Lighthouse scores
- [x] schedule conversation w/ team

**Comment by anatecture** [comment]
updates pushed to production.
