### ISSUE TITLE
Framework to manage GSA Digital Guidelines as versioned API

### ISSUE THREAD

**Issue by mvogelgesang** [GSA/EDX#19]
## Summary

Guidelines and policy memos often lack specific descriptions to determine compliance. For example, saying "site must use USWDS in full" is open for interpretation. This leads one site owner to set the bar at height X while another sets the bar much lower at height Y. Instead, we should think of our policy memo's and guidance similar to the way API's are introduced, versioned, and sunset. 

![image](https://user-images.githubusercontent.com/4053083/112867985-89197b80-9089-11eb-93a8-ed3f1e941fda.png)

## Additional context and links

Add any other context, screenshots, or links to working docs.

## Checklist

List below the specific actions to be taken

- [ ] item 1
- [ ] item 2

**Comment by ryanwoldatwork** [comment]
Outlining a gradual, phased approach makes a lot of sense.

The framework should be relatively easy to encode... just need to define the phases and align them with data available in the Inventory and Site Scanner.

**Comment by ryanwoldatwork** [comment]
Records in the following shape would allow for reporting on the `USWDS` attribute, over time.

Touchpoints Q1 - USWDS - 1.12
Touchpoints Q2 - USWDS - 2.20
Touchpoints Q3 - USWDS - 2.20
Touchpoints Q4 - USWDS - 2.11.2

Login.gov Q1 - USWDS - 2.12
Login.gov Q2 - USWDS - 2.30
Login.gov Q3 - USWDS - 2.9.1
Login.gov Q4 - USWDS - 2.10.10

---

I'd also like insight into specific sites that aren't up to date.
I'd like to see a task in a backlog outline work to get up to date. (Dependabot sends update notices automatically)

**Comment by mvogelgesang** [comment]
@ryanwoldatwork Some of the work to inform GSA IT performance metrics could be a good jumping off point for this. The IT metrics are looking for some baseline capabilities and standards conformance (captured as booleans), namely:

- Uses DAP
- HSTS
- Employs USWDS Banner
- Employs USWDS Identifier
  - Links to Privacy Policy
  - Links to FOIA
  - Links to Accessibility Statement
- Contact Us (link, email, phone)

Evaluation for each criteria has been automated (currently in https://github.com/GSA/EDX/blob/main/Tools/shell/run.sh) and will migrate into a larger scanning utility in a forthcoming pull request. 

Laying out a longer term roadmap will need proposals to and concurrence from Digital Council and Exec Steering Committee.
