### ISSUE TITLE
User path from Website Inventory main page to DLP intake form

### ISSUE THREAD

**Issue by anatecture** [GSA/EDX#190]
## Summary

As a user, I need a path from the GSA Website Inventory main or entry pages to the Digital Lifecycle Program (DLP) intake form so I can start the process of getting a new site. 

## Additional context and links

[DLP intake form](https://touchpoints.app.cloud.gov/touchpoints/e83b7c28/submit)

## Checklist

- [ ] Ask @ryanwoldatwork what he thinks about this path idea. 
- [ ] Work w/ @gailsprinkle to find out how she envisions this path working. 
- [ ] Create prototype. 
- [ ] Ask a 2-3 users, possibly sourced from DC members' divisions(?) to test proposed path.

**Comment by ryanwoldatwork** [comment]
I'm wondering how information is going to get from a Touchpoints form into the Website inventory.

My quick take is that some questions should live on the Website record and become a part of the existing form for a new Service.

Remember that the Websites feature is not GSA specific, and meant to support gov-wide (thus, common) attributes.

**Comment by anatecture** [comment]
The majority of the points in this intake form are to provide fodder for a first conversation with EDX, so they won't need to move from the form to the Inventory. 

While some of the fields might reasonably live in the Inventory, I also want to be conservative in adding fields to it, so we don't end up over-crowding the Inventory with datapoints.
