### ISSUE TITLE
Link employee departures to website manager field in Inventory

### ISSUE THREAD

**Issue by anatecture** [GSA/EDX#191]
## Summary

As a website manager in GSA, I need to know that my management will be assigned to another person when I leave my position. 

As a GSA employee, I need to know that the listed managers in the Inventory are correct and up to date. 

## Checklist

List below the specific actions to be taken

- [ ] Investigate: is this feature possible? 
- [ ] Talk to @gailsprinkle @monicas-d to get pointed to the right folks in HR to understand the hoops to jump through to do this
- [ ] Talk to @ryanwoldatwork to understand the Touchpoints needs or barriers to doing this. 
- [ ] Create prototype of feature
- [ ] Test

**Comment by anatecture** [comment]
@ryanwoldatwork  you talked about this feature back in the late summer, linking people's departures from GSA to the Inventory so we can track when managers leave. Could we revive this conversation? 

We're already starting to see the Inventory fall out of date, so it's clearly time to get serious about this feature.

**Comment by ryanwoldatwork** [comment]
Happy to chat.
The thread I remember is to process Separations reports (users who leave).

I'm guessing there are more cases here where sites and responsibilities are changing, but users and staying in the org.

**Comment by anatecture** [comment]
Exactly, and I'm not sure how to manage those. I'll put some time on our calendars.

**Comment by ryanwoldatwork** [comment]
Every system owner is responsible for managing their separations list, which is received monthly.

I process these for the Touchpoints system. 
\This might be as simple as giving Touchpoints users a heads up if a user is inactivated due to separation.

**Comment by anatecture** [comment]
Per conversation w/ @ryanwoldatwork on 02/08: We will ask people if they're still managing the websites via Touchpoints email approx every 6 months. 

Separations report: any website that's assigned to an inactive user will show up in monthly security list. We can run those reports on EDX side. Will coordinate w/ @AKM399 @mvogelgesang @hatfieldjm4 @anatecture

**Comment by anatecture** [comment]
Note from 08/09/2022: Still think this is a good idea, can't accomplish now. Continuing in icebox.

**Comment by monicas-d** [comment]
Yes! We discussed this (if it's what I"m recalling) and we decided that the back-up website manager would be that person's supervisor until/unless that supervisor tells us otherwise for a different person or future new hire...no? Thanks!

**Comment by ryanwoldatwork** [comment]
@monicas-d - that makes sense. 

A goal here is to ensure that website records are not assigned to people who are no longer at the organization, because that would be invalid and inaccurate.

There is an `event`; an employee's departure, which triggers an `action`. The action includes:

1. the reassignment of the website to another person, if necessary (this is an organizational decision/action)
2. updating of the record (this is technical recording and accounting)

---

As a System Owner,
I receive a monthly email report from Security with a list of emails that have left the org.

This list is how we're informed of employee departure events.

---

When Touchpoints finds a person who has departed 
AND is listed as a Website Point of Contact,
what should Touchpoints do?

For example, Touchpoints could add a flag on the record, indicating it needs attention.

**Comment by ryanwoldatwork** [comment]
I have a use case for this. A person assigned to 2 sites has left the org.

Something like an `employee_separated` event.

From an organizational standpoint, what happens next? Who takes action to resolve this?

**Comment by mvogelgesang** [comment]
@ryanwoldatwork @monicas-d @gailsprinkle my take is that it would be flagged and it would ask the supervisor to update it. Upon update, the flag clears. The supervisor may not have an immediate backfill and have to take on the responsibility themselves. 

```mermaid
flowchart TD
    A[Employee Departure] -->|notification| B(Supervisor update)
    B --> C{Assign Web Mgr}
    C -->|New Person| D[Assign to new person]
    C -->|Supervisor| E[Assign to Supervisor]
    D --> F{eval PD}
    E --> F
    F --> |Requires update| G[HR PD Update]
    F --> |No update needed| H[Done]
    G --> H

```

**Comment by mvogelgesang** [comment]
Ties to #631
