### ISSUE TITLE
Combine FISMA system and business application inventories - Communicate changes brought about by master inventory

### ISSUE THREAD

**Issue by hatfieldjm4** [GSA/EDX#197]
In order to eliminate duplication and confusion, the FISMA system/subsystem inventory in Archer is being compared to the business application inventory in GEAR. The goal is to have one inventory, since there is so much overlap between the two.

Communicate any relevant changes to ISSOs and ISSMs

**Comment by AKM399** [comment]
@hatfieldjm4 closable?

**Comment by hatfieldjm4** [comment]
While the comms docs have been created, the briefing of ISSOs, System Owners, etc. has not yet begun. I'm hoping this kicks off in the next month or 2.

**Comment by hatfieldjm4** [comment]
This is done with the exception of communicating changes to ISSOs and SOs, which won't occur until GEAR3 is ready to go live (in coordination with the IT security Archer team).
