### ISSUE TITLE
Present a document on Initial Findings to

### ISSUE THREAD

**Issue by mvogelgesang** [GSA/EDX#2]
## Summary

Produce a doc that presents some initial findings from the GSA Site analysis. This should present some top-level information and broad recommendations, suggestions, or areas for more investigation.

## Additional context and links

[Initial Findings 🔒 ](https://docs.google.com/document/d/1YTLmF4mk1c7krVwKs_uga5TMoHif5HjBhE8KQNDrXMw/edit#heading=h.4vtn2w4zo2ur)

**Comment by mvogelgesang** [comment]
Created Milestones for the following categories:

- [Current Digital Presence Policies](https://github.com/GSA/EDX/milestone/5)
- [Login Capabilities](https://github.com/GSA/EDX/milestone/3)
- [DNS Management](https://github.com/GSA/EDX/milestone/4)

Outstanding Categories include:

- Blogs
- Sub-Brands/ Products
- Content Heavy
- Redirects

**Comment by ryanwoldatwork** [comment]
Hi @mvogelgesang, is this still valid?

If so, who do you have in mind as the audience?
And what constitutes "done" for this work?

**Comment by ryanwoldatwork** [comment]
@mvogelgesang - what happens with these Recommendations?

Does somebody need to give them a blessing before we do work to improve things?

**Comment by mvogelgesang** [comment]
@ryanwoldatwork The initial findings doc was really just some foundational information and some potential next steps. I think DNS and login systems is still valid but difficult for EDX to directly affect. Login specifically is a worthwhile talk track and something to beat the drum about

**Comment by ryanwoldatwork** [comment]
noted this here too https://github.com/GSA/EDX/wiki/Research-notes
