### ISSUE TITLE
What are visitors looking for?

### ISSUE THREAD

**Issue by mvogelgesang** [GSA/EDX#201]
## Summary

In order to provide customers, vendors, and the public a quality experience when visiting GSA websites, we need to understand why someone visited the site in the first place. One way of gleaming this type of information is via search engine statistics which are provided by tools like Google Search Console and Bing Webmaster Tools (Yahoo's solution appears to have been deprecated in favor of Bing). By understanding which queries are driving traffic to sites, we can have a better understanding of potential dead ends or areas of confusion for visitors. For instance, if someone searches "buy lighthouse" and they receive search engine results pointing to 4 different GSA sites, it may indicate that there is duplicate information which could be consolidated 

- [ ] #202

## Additional context and links

Top search engine referrals to GSA sites from the past 30 days (Jan 5 - Feb 3) are:

![image](https://user-images.githubusercontent.com/4053083/152553389-42d45236-f263-4636-833c-fa694f82c149.png)

## Checklist

List below the specific actions to be taken

- [ ] Investigate what it would take to cover a broad swath of GSA sites with such tools. Are there means for adding Search Console or Webmaster tools via DNS or other means that would not require individual lifts by development teams?
- [ ] Who is already using these tools?
- [ ] Develop a list of potential outputs and aggregations that would be of benefit to GSA
- [ ] If warranted, propose to EDX and DC that next steps be taken

**Comment by AKM399** [comment]
possible linkage to website profile project this fall.

**Comment by AKM399** [comment]
need to find out who has their hands on google search console.

**Comment by anatecture** [comment]
this is related to Statistics from on-site search project https://github.com/GSA/EDX/issues/202
