### ISSUE TITLE
Statistics from on-site search 

### ISSUE THREAD

**Issue by mvogelgesang** [GSA/EDX#202]
By extension, having access to on-site search results would be valuable as well. Search.gov may be able to provide more information/ tooling. Would also be worthwhile to investigate ways to pull data from sites using native search capabilities like Solr.

Search.gov APIs are available for website consumers, not more broadly

To do
- [ ] Investigate Google Search Console API- we have access to all *.gsa.gov domains

**Comment by AKM399** [comment]
content strategy discussion.

**Comment by AKM399** [comment]
review dashboard with dawn mcclesky from search.gov.

**Comment by AKM399** [comment]
@hursey013 keep the issue or kill it?

**Comment by anatecture** [comment]
Don't have bandwidth to support this project in the near-term. Closing.
