### ISSUE TITLE
Onboarding GSA Website Manager - vltp.gsa.gov

### ISSUE THREAD

**Issue by mvogelgesang** [GSA/EDX#203]
Welcome to the GSA. 

As a Website Manager, responsibilities include:

* A number of conditions, described 21st Century IDEA

### Resources and trainings

* Digital.gov links

### How to get help

Contact EDX

### Information about the Website Inventory

https://touchpoints.app.cloud.gov/admin/websites/591

**Comment by AKM399** [comment]
@gailsprinkle and @monicas-d for your review and thoughts: the idea being we have a set communication for new sites.

**Comment by monicas-d** [comment]
I think this one requires a conversation first. Not sure what you're asking. Thanks Aaron.

**Comment by anatecture** [comment]
Building a [GSA Website Manager Orientation](https://docs.google.com/document/d/1J0ldDrO38g95fPyY2wZSuJeUfdCgjUnf1AfPhktqm-A/edit#heading=h.bj76r82jetcu) now as part of the PD work.

**Comment by monicas-d** [comment]
Awesome! Thanks for adding this link in here, @anatecture !

**Comment by mvogelgesang** [comment]
this will be addressed via web manager training, closing
