### ISSUE TITLE
Evaluation - SFTool.gov

### ISSUE THREAD

**Issue by AKM399** [GSA/EDX#206]
Website Evaluation of sftool.gov - Michael Bloom
**To Do**
- [x] Set appointment 2/9 9:30 - 10:00
- [x] assigned people @mvogelgesang and @anatecture 
**Progress**
- [x] [Scan](https://drive.google.com/file/d/1moeoP94Jh_IwZn5quucFK9IL8tl2GkBM/view?usp=sharing)
- [x] [ interview notes](https://docs.google.com/document/d/1D7gtm2jWivQtn6MrloB7VO3xVmDC6eCSipmoXZaFvhk/edit)
- [x] [Interview Spreadsheet](https://docs.google.com/spreadsheets/d/1NKtnZ-RdektHZ8RGEEX82xTwt5dDTVTSa_h_Do_Y5sE/edit#gid=0)
**Rec Docs Needed**
- [ ] Summary
- [ ] Tl:Dr
- [ ] immediate action
**Done** 
- [ ] [recc link](https://docs.google.com/document/d/19eok2Y7ESpn4lP57yrEm3ik7jneHQMWTxYp15HbjEe4/edit)

**Comment by anatecture** [comment]
needs scan data @mvogelgesang

**Comment by anatecture** [comment]
[report package complete](https://drive.google.com/drive/folders/1l8z6Rgxrsd-5W-NV2rJZkFJDyXfeQfNB)
