### ISSUE TITLE
Evaluation - Digitalcorps.gsa.gov

### ISSUE THREAD

**Issue by AKM399** [GSA/EDX#207]
Website Evaluation of digitalcorps.gsa.gov - Dave Skender
**To Do**
- [x] Set appointment 2/11 1:00 to 1:30
- [x] assigned people @RachelF and @mvogelgesang 
**Progress**
- [x] [Scan](https://airtable.com/appaxAzqTVnbOf7cm/tblsXuj825cfZwUPj/viwZICRqCbrw5G6VI/rec9809UHj635RhxT?blocks=hide)
- [x] [interview notes](https://docs.google.com/document/d/1yN7fwt2xmOhyPUOtts-q1kLD1jq6JhPMUGQsV41X99M/edit)
- [x] [Interview Spreadsheet](https://docs.google.com/spreadsheets/d/1geuqp-J3544R6FhP7w42P0aAxBKwuPyOfBuZMJtpKOs/edit)
**Rec Docs Needed**
- [x] Report
**Done** 
- [x] [recc link](https://docs.google.com/document/d/1uerG3dN-Thf9bdrj9BTaDMC8oI-V0x8lSfUKoHnhHTw/edit?usp=sharing)

**Comment by RachelF** [comment]
@RachelF and @mvogelgesang completed this interview and updated links to interview docs 2/11/2022.

**Comment by RachelF** [comment]
final report: https://docs.google.com/document/d/1G9fPqxscc3p0m_QGnkorIU10RyKK2s-9B45zq7Vfia4/edit#heading=h.cdardcvs3br3

**Comment by anatecture** [comment]
[Report package complete](https://drive.google.com/drive/folders/1F13f32TyJVHAL-QCDHvOBiyGzi1QjChF)
