### ISSUE TITLE
Evaluation - Cic.gsa.gov

### ISSUE THREAD

**Issue by AKM399** [GSA/EDX#208]
Website Evaluation of (site) - (Site manager)
**To Do**
- [x] Set appointment 2/8 4:00 to 4:30
- [x] assigned people @mvogelgesang and @hatfieldjm4 
**Progress**
- [x] [Scan](https://airtable.com/appaxAzqTVnbOf7cm/tblEc5CVjvlElEz8l/viwS3ASIi8GL74rI8/rec3Av3URhU4PBRtp?blocks=hide)
- [x] [interview notes](https://docs.google.com/document/d/11Jcazi4qRuxSAlgFLl3RsoIbFLPEZsBg_Xvu4bj-kSM/edit?usp=sharing)
- [x] [Interview Spreadsheet](https://docs.google.com/spreadsheets/d/1EjsQ5nW0wbhH-GZ-Q5OXcEE0qxVg8q8kM4rxSuMAoX0/edit?usp=sharing)
**Rec Docs Needed**
- [ ] Summary
- [ ] Tl:Dr
- [ ] immediate action
**Done** 
- [ ] [recc link ](https://docs.google.com/document/d/1uerG3dN-Thf9bdrj9BTaDMC8oI-V0x8lSfUKoHnhHTw/edit?usp=sharing)

**Comment by anatecture** [comment]
[report package complete ](https://drive.google.com/drive/folders/1FYrXCd8MQjm_kvEefLJM_m8CWYSYiU4o)
