### ISSUE TITLE
Digital Council - Are there types of sites that should not require search?

### ISSUE THREAD

**Issue by mvogelgesang** [GSA/EDX#210]
## Summary

We are finding many sites which are a single, public-facing login page with a large authenticated experience behind it. It would be silly to "ding" a website for not having search when it really doesn't make sense. Similarly, sites with very few pages may also be candidates for such a discussion.

## Additional context and links

The 21st Century IDEA Act states the following:

> digital service that is intended for use by the public, shall ensure to the greatest extent practicable....(4) contains a search function that allows users to easily search content intended for public use;

If the site does not have content intended for public use, search does not seem necessary. 

## Proposed Criteria

Sites that do not require search shall meet the following criteria:

- Public content is limited to a login and/or registration page, contact us page, user manuals/ help guides. Information beyond that requires a search component. 

## Checklist

List below the specific actions to be taken

- [x] Would like GSA Digital Council to take up the item and make a determination as to when search is required. 
- [x] Once determination has been made, update scans return correct status for sites that do/don't meet the criteria.

**Comment by RachelF** [comment]
I'm also contemplating the need for an additional filter to identify informational sites with login functionality. Sometimes these are tagged as info, sometimes as login -- so we need better criteria and maybe that 3rd category that is somewhere in between, when a site has a few pages, but functions basically as a login page with some supporting content.  THEN we could use the "app login" designation to say that sites in that category do not need search. (App sites also probably don't need search.) But if they have some content (even if not much) then they should have search. Thoughts @mvogelgesang ?

**Comment by mvogelgesang** [comment]
@RachelF thats a good point. I had been separating out this discussion from the website type definitions but bringing it together as you suggest would make sense. Those definitions might need to be tightened up (it's been a while since I looked at them). That being said, just because a site does not require search does not mean that it should not meet the other sections of the IDEA Act. 

I've got a short list below that I think represents the type of sites at GSA. ESRS.gov is a bit of a questionmark but the others seemed straightforward.

| Site Name | Type | Needs Search? | Rationale |
|-----------|------|---------------|-----------|
|1.usa.gov| infrastructure | No | Site serves as a shortUrl redirect hub. No meaningful content lives. at "/" |
|gsasolutionssecure.gsa.gov | ? | No | Site used for webpage representations of marketing emails and event registration signups | 
| cic.gsa.gov | informational | Yes | Site contains many pages of content|
| secure.login.gov | infrastructure | No | Simply an authentication page, any relevant content would be hosted on the referring site |
| fairs.reporting.gov | Application Login | No | Very little content- most all is contained in PDF links. Login and Registration is primary purpose |
| apps.ocfo.gsa.gov | informational | No | Single page website | 
| esrs.gov | ? | ? | More than a handful of pages but primary focus seems to be getting feds or contractors to login. A lot of links to content on other sites. |

**Comment by mvogelgesang** [comment]
A very brief deck that can be used to highlight this issue to DC and get some input: https://docs.google.com/presentation/d/1sy5r0CT_EjfdBqQbf6vKo8VGu0xAx87Hl3I47HeEbho/edit#slide=id.p

**Comment by RachelF** [comment]
RF briefed DC on this issue on 3/22. 
Proposed criteria for sites not requiring search:
- Public content is limited to 1-2 pages
- Login and/or registration page
- User manuals/ help guides (pdf, doc)
- Applications that require someone to log in.

DC was fine w/most of the proposed recs , but requested that sites w/1-2 html pages but lots of pdf content should also contain search, to help people search for the right PDF.

After further consideration, RF proposes the following criteria for sites that don't need search functionality:

- Public content of the site is limited to no more than 2 pages total (including html, documents, pdfs)
- Sites tagged as "application" in Touchpoints (require login and/or registration before content/features can be accessed)

Thoughts @mvogelgesang ?

**Comment by mvogelgesang** [comment]
@RachelF I think this makes sense, will be submitting a draft pull request shortly which encodes this logic into the scanner. I'll take an initial pass at the website list but we may have to iterate on it a few times before it is solid.

**Comment by mvogelgesang** [comment]
@RachelF to clarify, should it be sites tagged as "application" or "application login"? I think you meant the latter but I wanted to be sure.

**Comment by mvogelgesang** [comment]
@RachelF this has been merged in PR #330 we can close
