### ISSUE TITLE
Subbrand Guidance

### ISSUE THREAD

**Issue by mvogelgesang** [GSA/EDX#218]
## Summary

In speaking with many website managers, we are learning more about the various individualized brands within GSA. Regulations.gov and sftool.gov are ready examples. Many times, these sites perform governmentwide functions and are funded partially by other agencies. In many cases, other agencies have significant input into the direction of the web property. These types of sites contrast sharply with some of the traditional GSA business sites such as advantage.gsa.gov, buy.gsa.gov, lop.gsa.gov. 

## Checklist

List below the specific actions to be taken

- [ ] What definitions exist within GSA's existing web guidelines to identify which category a site falls into?
- [ ] Do those definitions require expansion or revision?
- [ ] Somewhat related, a memo from 2003 identifies a URL strategy which advises "gsa{sitename}.gov". This seems to contradict recent guidance around stopping the proliferation of top level domains. [OSC 1808.3](https://www.gsa.gov/cdnstatic/Directives/OSC_18083_GSA_Visual_Information_Program_Posted_Version_-_August_30__2017.pdf) supersedes this previous memo but does not speak to the naming and creation of domains.

**Comment by mvogelgesang** [comment]
@AKM399

**Comment by RachelF** [comment]
Definition for "type of site" is defined in [GSA's Guidelines](https://docs.google.com/document/d/1E0K_LDlDqEgHKESTqHKlKN50OJAxCcl_FcKB-qLL13A/edit#bookmark=id.r8dq7fg5gdl0). 

Current site types are:
- GSA business sites
- Hybrid - general public, partnership, and advisory sites
- External websites
- Mobile apps

The type of site you're describing here fits under "hybrid" when it's a partnership between GSA and another agency or agencies.

The Guidelines also cover [Domain guidance](https://docs.google.com/document/d/1E0K_LDlDqEgHKESTqHKlKN50OJAxCcl_FcKB-qLL13A/edit#heading=h.5q501h5enbh) and direct GSA teams to this [InSite page for guidance on requesting a new domain](https://insite.gsa.gov/employee-resources/information-technology/it-assistance-and-help-desk/service-catalog/it-service-catalog-domain-names).
The InSite page points to a [GSA Order from 2013](https://insite.gsa.gov/cdnstatic/insite/CIO_21412_General_Services_Administration_%28GSA%29_Web_Domain_Names_%285-30-2013%29_%28Revised_2-19-2019%29.pdf) that looks like it needs to be updated.

Tagging @gailsprinkle so we can incorporate these as needed into our DLP comms planning.
