### ISSUE TITLE
Evaluation - Calc.gsa.gov

### ISSUE THREAD

**Issue by AKM399** [GSA/EDX#219]
Website Evaluation of calc.gsa.gov - Brad Powers
**To Do**
- [ ] Set appointment 3/16 3:00 to 3:30
- [ ] assigned people @anatecture and @RachelF 
**Progress**
- [ ] Scan
- [ ] [interview notes](https://docs.google.com/document/d/1sRBIe-_hb389tm-nTcorQ7CKLSJEPaEBoRGr8mVSd0Y/edit?usp=sharing)
- [ ] [Interview Spreadsheet](https://docs.google.com/spreadsheets/d/1kzFNHQHOfVXz3hhFWyn_dj1vS2qMHt695qpjHyVTWx4/edit?usp=sharing)
**Rec Docs Needed**
- [ ] Summary
- [ ] Tl:Dr
- [ ] immediate action
**Done** 
- [ ] [recc link](https://docs.google.com/document/d/1CfnHJ1qMBciUQbE28Qj3zaLJ_E2DBJ8dBRo8XNE-lxU/edit?usp=sharing)

**Comment by anatecture** [comment]
- This is the new host for the Contract-Awarded Labor Category (CALC) tool helps federal contracting officers and others find awarded prices to use in negotiations for labor contracts. It offers ceiling prices, fully burdened costs, services data, and worldwide rates.

- Stakeholders: Tina Burns, Brad Powers, Charles Burton

_Ana Note: In his interview on 3/16, Brad said this site would become a redirect on 4/26. Let’s make sure that this is that redirect. If it’s not, let’s find out why this site isn’t going away on 4/26 as planned_

**Comment by anatecture** [comment]
Email brad to see if this is still going to be shut down
