### ISSUE TITLE
Sprint Planning

### ISSUE THREAD

**Issue by mvogelgesang** [GSA/EDX#22]
## Summary

Create a roadmap for the next 3 months which includes milestones that are shipped in two week intervals

## Additional context and links

Add any other context, screenshots, or links to working docs.

## Checklist

List below the specific actions to be taken

- [ ] item 1
- [ ] item 2

**Comment by ryanwoldatwork** [comment]
Hi @mvogelgesang - is this still valid?

Is there something you'd like to see done or practiced?

**Comment by ryanwoldatwork** [comment]
Closing this issue.

But also cc'ing @anatecture and @RachelF, as this relates to work planning and recent backlog conversations.
(Let's revisit high-level plans and milestones. The backlog tasks can align to support those)
