### ISSUE TITLE
Evaluation - blog.usa.gov

### ISSUE THREAD

**Issue by AKM399** [GSA/EDX#225]
Website Evaluation of blog.usa.gov - Russel O'neil
**To Do**
- [ ] Set appointment #172 
- [ ] assigned people
**Progress**
- [ ] Scan
- [ ] [interview notes](https://docs.google.com/document/d/10stel3gPlV38bEhYWao6k1O2Urm-Bxp3ogMqAYdoXuA/edit?usp=sharing)
- [ ] [Interview Spreadsheet](https://docs.google.com/spreadsheets/d/15Rsh4z0955wNrtFfn_AgMRdJ6XL8Z0Qv0LusVD6Jjms/edit?usp=sharing)
**Rec Docs Needed**
- [ ] Summary
- [ ] Tl:Dr
- [ ] immediate action
**Done** 
- [ ] recc link

**Comment by anatecture** [comment]
Site is related to [usa.gov, issue 172](https://github.com/GSA/EDX/issues/172). closing this issue for now, as we need to coordinate w/ russell o'neill further.
