### ISSUE TITLE
Evaluation - Connect.usa.gov

### ISSUE THREAD

**Issue by AKM399** [GSA/EDX#230]
Website Evaluation of connect.usa.gov - russel o'neil
**To Do**
- [ ] Set appointment #172 
- [ ] assigned people
**Progress**
- [ ] Scan
- [ ] [interview notes](https://docs.google.com/document/d/1tnwlv_P1gas_ffsGkfQ_XJHoCgMlqFgf8yRXkBSnigs/edit?usp=sharing)
- [ ] [Interview Spreadsheet](https://docs.google.com/spreadsheets/d/11jK8z6OiLYkKtRjRi-G9Fj9sX9mFUAKrIP8zKPvMRYg/edit?usp=sharing)
**Rec Docs Needed**
- [ ] Summary
- [ ] Tl:Dr
- [ ] immediate action
**Done** 
- [ ] [recc link](https://docs.google.com/document/d/1Thn0OPNWKSLcDxpNtduMb68wfMUrpUZH9-8s7vz54kU/edit?usp=sharing)

**Comment by hatfieldjm4** [comment]
Recommendations document available [here](https://docs.google.com/document/d/1Thn0OPNWKSLcDxpNtduMb68wfMUrpUZH9-8s7vz54kU/edit#).
