### ISSUE TITLE
Evaluation - connect.digital.gov

### ISSUE THREAD

**Issue by AKM399** [GSA/EDX#236]
Website Evaluation of connect.digitalgov.gov - Toni Bonnito
**To Do**
- [ ] Set appointment #177 
- [ ] assigned people
**Progress**
- [ ] Scan
- [ ] [interview notes](https://docs.google.com/document/d/1IQwVKZqVyq2K4eORE0dHGJGJxn6EqSLt6ErDhgzsrlM/edit?usp=sharing)
- [ ][ Interview Spreadsheet](https://docs.google.com/spreadsheets/d/1LSyQ7ecDonR438sHMYp9BBV6fv7gU3J3LQLIJO-jkzs/edit?usp=sharing)
**Rec Docs Needed**
- [ ] Summary
- [ ] Tl:Dr
- [ ] immediate action
**Done** 
- [ ] recc link

**Comment by hatfieldjm4** [comment]
@AKM399 Connect.digital.gov gives an ERR_EMPTY_RESPONSE. A very similar site, Connect.digitalgov.gov, is critical infrastructure so not in scope for sprint 3
