### ISSUE TITLE
Real Property Disposal FASTA Engagement

### ISSUE THREAD

**Issue by mvogelgesang** [GSA/EDX#24]
## Summary

Present website framework to Real Property Disposal office for potential new Federal Assets Sale and Transfer Act (FASTA) site. Use this as an opportunity to test the framework in a real world scenario and identify gaps or areas within the agency that do not provide for a soft landing spot if it is determined that this content should live on an existing web property. 

## Additional context and links

The Real Property Utilization & Disposal program has a number of sites currently

* https://www.gsa.gov/real-estate/real-estate-services/real-property-utilization-disposal (Drupal)
* https://disposal.gsa.gov (Salesforce)
* https://www.gsa.gov/policy-regulations/policy/real-property-policy/asset-management/federal-assets-sale-transfer-act-fasta (Drupal)
* https://pbrb.gov (Wordpress)
* https://realestatesales.gov/gsaauctions/gsaauctions/ (tech stack unknown)

## Checklist

List below the specific actions to be taken

- [ ] Map out the user journey from one site to another
- [ ] identify different users/ personas 
- [ ] determine desired end state

**Comment by mvogelgesang** [comment]
Questions
- What other web properties are out there that could hold their content? 
- How is the data/content captured today? Is it sitting in a spreadsheet, word docs, etc?

**Comment by ryanwoldatwork** [comment]
Is there any product guidance or consultative intake that happens for a customer like this?

**Comment by mvogelgesang** [comment]
@ryanwoldatwork thats a good point, there are various intake mechanisms across GSA IT. Often, what I have seen is that offices have preferred groups within GSA IT to work with and turn to them first. Sometimes this leads to a solution being picked not because it is a best fit but because that is who they asked first. 

At this point, I don't know if they have made a formal request to an IT team just yet.

**Comment by ryanwoldatwork** [comment]
@mvogelgesang - is this still valid?
If so, would you like to revisit? Or should another person pick this up?

**Comment by ryanwoldatwork** [comment]
ping @mvogelgesang

**Comment by anatecture** [comment]
Is this issue still on the board or are we archiving it for now @mvogelgesang?

**Comment by mvogelgesang** [comment]
Closing this issue as the gsa.gov team has addressed the need with the creation of new content types, https://www.gsa.gov/real-estate/real-estate-services/real-property-utilization-disposal/property-sales
