### ISSUE TITLE
Draw GSA-wide org chart

### ISSUE THREAD

**Issue by ryanwoldatwork** [GSA/EDX#241]
Use HR data to generate a GSA-wide org chart.
The org chart becomes a standard report; a map of sorts.

Atop the org chart,

* [ ] enable users to flag issues and opportunities about job descriptions, needs, and capabilities
* [ ] flag their own skills
* [ ] flag skills they want to know
* [ ] indicate workload/morale/sentiment?

Use the insights to support ongoing organizational change efforts.

This idea stemmed from a conversation related to reporting on hiring needs, and more broadly, org design.

#### Minimal data to gather

* Organization structure (hierarchy) - who manages who?
* Person data
  * First name
  * Last name
  * Email
  * Position title
  * Classification
  * Step
  * Start date
  * Supervisor (similar or duplicative to Organizational structure above)

### Nice to have data

* More org hierarchy; Department/Division/Program/Section (eg: TTS Data Portfolio or Feedback Analytics program)
* Tenures (if possible)
* Historical ins and outs
* End date (if we decide to look backward)
* URL to position title (based on the Title & Classification)

**Comment by ryanwoldatwork** [comment]
hi @gailsprinkle and @monicas-d, 

I wanted to get your thoughts on this effort,
and hopefully, find a contact that can start a discussion about the specific data, access, and uses.

**Comment by patriciacheng** [comment]
OAS has an organizational manual that should contain org charts in PPT
form.  I believe it will be available to the entire agency once it
completes the CDT process.  Matt Plaus is the person I worked with on that.

Patricia

U.S. General Services Administration


*Patricia Cheng *(she/her/hers)

Acting Chief of Staff

Office of Customer Experience

C: 202-536-6891 | ***@***.***

***@***.***

**Comment by ryanwoldatwork** [comment]
Thanks @patriciacheng!
I just emailed Matt and cc'd you and @anatecture.

**Comment by patriciacheng** [comment]
Also, GEAR has an org chart.  @hatfieldjm4

**Comment by RachelF** [comment]
Coincidentally, I needed an org code last week, so just happened to pull down from D2D a copy of GSA's entire org code list/structure. I'll  email it to you, @ryanwoldatwork (not sure if it should be published here?).

**Comment by hatfieldjm4** [comment]
@patriciacheng Thank you, Patricia. Here is a link to the [GEAR org chart](https://ea.gsa.gov/#!/organization_model) which makes it easier to see the hierarchy. D2D's [list of all GSA organizations](https://d2d.gsa.gov/dataset/gsa-organization) is likely more up-to-date at any given point because I populate the GEAR org data off of it.

**Comment by ryanwoldatwork** [comment]
update:

GEAR draws a collapsed org chart that looks very complete, except
it doesn't have any actual staff and seems to stop at an organizational level above individuals and teams.

**Comment by anatecture** [comment]
No active work on this; closing for now.
