### ISSUE TITLE
Grab Search Engine Result Screenshots

### ISSUE THREAD

**Issue by mvogelgesang** [GSA/EDX#250]
## Summary

When performing site scans, grab a screenshot from one or more common search engines and show the results that appear when the website name is searched. For instance, searching "fedspecs.gsa.gov" in Bing returns: 

![image](https://user-images.githubusercontent.com/4053083/154341619-d91a60b6-58b1-49f9-bc66-bd6af5e553f0.png)

Google returns:
![image](https://user-images.githubusercontent.com/4053083/154341846-1cc88f2a-581c-4727-90e0-ffb7db8acccf.png)

Duckduckgo returns:
![image](https://user-images.githubusercontent.com/4053083/154342374-4d336e95-dc7e-47da-9e74-d9d9e0a28d49.png)

This could be a way to provide better context to website managers as to why investment in SEO is worthwhile.

## Additional context and links

While screenshots are A means for conveying this information, having the actual content would be handy too. 

- Google does not provide a Search API.
- Bing offers an API (https://docs.microsoft.com/en-us/bing/search-apis/bing-web-search/overview) but its TOU generally prohibits caching or storing the content
- Duckduckgo offers an API for their instant search (https://duckduckgo.com/api)

## Checklist

List below the specific actions to be taken
- [x] update web evals report template to include space for this. Goal being to search the domain name in Google, Bing, DuckDuckGo, etc and screencap the results.
- [x] write up common responses to different things we see in search results.

**dev tasks will be completed in another ticket**
- [x] #693
- [-] determine steps required for puppeteer
- [-] develop naming convention for files
- [-] add to output json file
- [-] implement

**Comment by AKM399** [comment]
@mvogelgesang inbox or icebox?

**Comment by mvogelgesang** [comment]
@AKM399 Inbox I would say. Ideally this information can be expressed as an image and JSON. Grabbing the image is the lightest lift though

**Comment by mvogelgesang** [comment]
@AKM399 I have updated this content in 🔒 [Google Docs](https://docs.google.com/document/d/15wZekXrzh9li1HH8vxAr6VwZhEIfbx1Zh7QjVeJAT5w/edit#heading=h.ipa74kw6xngf)

Since we already produced templates for Sprint 1, say we include this in sprint 2 or should we retrofit existing docs (not a crazy lift)?

**Comment by AKM399** [comment]
sprint 2.

**Comment by AKM399** [comment]
In scans. Just has to be included in analytics package.
