### ISSUE TITLE
Evaluation - dev.identitysandbox.gov

### ISSUE THREAD

**Issue by AKM399** [GSA/EDX#251]
Website Evaluation of dev.identitysandbox.gov - Julia Elman
**To Do**
- [x] Set appointment 6/23 2:30 to 3:30
- [x] assigned people @hatfieldjm4 and @RachelF 
**Progress**
- [ ] Scan
- [ ] [interview notes](https://docs.google.com/document/d/1JtMRDzbNOo6Ycmba3iuhzrfW15n1cllv41mq0VpHweQ/edit?usp=sharing)
- [ ] [Interview Spreadsheet](https://docs.google.com/spreadsheets/d/1eDwLGQcmxGPd432bqDYu_LS7vnvC4nhzG6utynWJt9Q/edit?usp=sharing)
**Rec Docs Needed**
- [ ] Summary
- [ ] Tl:Dr
- [ ] immediate action
**Done** 
- [ ] recc link

**Comment by RachelF** [comment]
@AKM399 Any site with "dev" in the name should not be included in a review. It's not public-facing, dev sites are typically behind the firewall and used for development/testing purposes.

**Comment by AKM399** [comment]
it looks like a public demo site.  i dont mind killing it, but worth
looking at.

**Comment by RachelF** [comment]
login.gov has a bunch of sites in the inventory - most are critical infra but several are test/demo. Wondering if we should, as a general practice, just lump all the ancillary sites (such as this one) into the interview when the primary site (in this case, login.gov) comes up for review? (So don't meet with them just about this... include this as a discussion item when we meet w/the login.gov team). Thoughts?

**Comment by mvogelgesang** [comment]
should this be closed? @AKM399
