### ISSUE TITLE
Evaluation - buy.gsa.gov

### ISSUE THREAD

**Issue by AKM399** [GSA/EDX#256]
Website Evaluation of discovery.gsa.gov - Tina Burns
**To Do**
- [x] Set appointment 6/28 1:30 to 2:00
- [x] assigned people @hatfieldjm4 and @RachelF  
**Progress**
- [x] Scan
- [x] [interview notes](https://docs.google.com/document/d/1SIq3l0ATlzkbvhuyNt7xuCtLY-ywlqULHQJ8FB7ryh4/edit#heading=h.6kd2t1lw7o4d)
- [x] [Interview Spreadsheet](https://docs.google.com/spreadsheets/d/1BWPOHUyeroc-K0HVp1qeevHkmTtkDPXD_rO8YFnOxyY/edit#gid=0)
**Rec Docs Needed**
- [x] Summary
- [x] Tl:Dr
- [x] immediate action
**Done** 
- [x] [recc link](https://docs.google.com/document/d/1n8MYjBZdb8Cj_rxQhtFBAQr8wtSb_w7Z0dRiB0Jf8m0/edit#)

**Comment by AKM399** [comment]
Site name changed to reflect sunsetting the old url sunsetting to a new domain

**Comment by RachelF** [comment]
@hatfieldjm4 I think we definitely should proceed with the interview. You're right that the earlier we can catch them in the dev process, the easier it might be to pivot if needed and keep them on the right track. (They probably are, BUT it's always good to just check in.)

**Comment by RachelF** [comment]
[Reccommendation report](https://docs.google.com/document/d/1n8MYjBZdb8Cj_rxQhtFBAQr8wtSb_w7Z0dRiB0Jf8m0/edit#) drafted 7/14

**Comment by RachelF** [comment]
@AKM399 can we close this? interview done, report written
