### ISSUE TITLE
Website Inventory

### ISSUE THREAD

**Issue by mvogelgesang** [GSA/EDX#27]
## User Stories

As a Digital Council member,
I want to answer a handful of business questions about websites across the GSA
So I can be informed and advised appropriately

As a GSA Website Owner,
I want to be able to edit information on my website at any given time,
So that..

As a GSA Website Owner,
I don't want to complete another data call and submit redundant information and not know what is happening with that information after I submit it

## Acceptance Critieria

Given an existing spreadsheets of websites exists
When Touchpoints Website inventory goes live
Then all websites will be migrated into Touchpoints

Given a website exists in Touchpoints
AND given my Touchpoints user account's email address matches the website's Site Contact or Site Owner email fields
When I click on a website from the publicly read-only list
Then I can edit and update specific websites that I have access to.

**Comment by ryanwoldatwork** [comment]
This has been shipped.

https://touchpoints.app.cloud.gov/admin/websites
