### ISSUE TITLE
Rough estimates of 'cost of change' per website

### ISSUE THREAD

**Issue by ryanwoldatwork** [GSA/EDX#270]
Goal

* better organizational understanding of where bottlenecks exist in operations (where websites and applications cannot be readily modified (less than 2 days, asap)

Idea

* query website managers to guesstimate the cost of change.  maybe this could be "how many days would it take to update html on your site/app". 

Assumptions

* where bottlenecks exist in operations, additional administrative overhead is introduced, creating its own management burden   #coordinationcosts

**Comment by ryanwoldatwork** [comment]
for example

https://touchpoints.app.cloud.gov/touchpoints/cce8c595/submit

**Comment by mvogelgesang** [comment]
I like this as a proxy for so many things. Perhaps giving an example of something to implement such as a [Site Alert](https://designsystem.digital.gov/components/alert/). A team that can update quickly likely has one or more of the following:

- direct access to the codebase
- a CMS with pre-built widgets
- Google Tag Manager

Prompt might be, "a new national holiday has been created and all federal websites must display an informational alert on all pages of the site."

**Comment by mvogelgesang** [comment]
Attempting to address this via the digital lifecycle program. Ability to create a banner message quickly (and without outsized administrative burden) should be table-stakes for websites

**Comment by ryanwoldatwork** [comment]
Curious where the conversation landed.

I like the idea of having each team accurately assess the amount of effort and time required to publish a banner on their site.

Example:

For a website, it'd entail:

* grabbing the USWDS [Site Alert](https://designsystem.digital.gov/components/site-alert/) component
* editing the text
* inserting the banner into the existing website
* deploying the website changes
* verifying the changes

This is a good example of a minimal change that is indicative of the cost/burden of deploying a basic change.

As @mvogelgesang mentioned, this could be done via Google Tag Manager, but I'm guessing most sites aren't setup for GTM use (beyond basic DAP), and most website managers/teams aren't familiar with the tool.
