### ISSUE TITLE
Evaluation - GSA.gov

### ISSUE THREAD

**Issue by AKM399** [GSA/EDX#277]
Website Evaluation of GSA.gov - Sarah Bryant
**To Do**
- [x] Set appointment 8/24 3 to 4
- [x] assigned people EDX Team
**Progress**
- [ ] Scan
- [ ] [interview notes](https://docs.google.com/document/d/1vGKvUDQUF5_iRN8BrYt8K3fOdd-QIR48cQtnoxjiEp0/edit?usp=sharing)
- [ ] [Interview Spreadsheet](https://docs.google.com/spreadsheets/d/1IOPChDWYFmpTYU20PieUtUp_o6yzngkfkn9szroJYc8/edit?usp=sharing)
**Rec Docs Needed**
- [ ] Summary
- [ ] Tl:Dr
- [ ] immediate action
**Done** 
- [ ] recc link

**Comment by anatecture** [comment]
[Notes from Interview ](https://docs.google.com/document/d/1Otn0m1OJMLlPrI2TFpy6cgRRyfxx2G9eS3Yf8xFsOqk/edit#heading=h.6kd2t1lw7o4d)w/ SB
