### ISSUE TITLE
Submit addition websites to Site Scanning Team

### ISSUE THREAD

**Issue by mvogelgesang** [GSA/EDX#287]
## Summary

In the past months, we have added a number of websites to GSA's inventory which were not previously listed in Site Scanning. Crosscheck the lists and submit updates to Site Scanning via pull request. File in question is, https://github.com/GSA/federal-website-index/blob/330e9ecda4859e10794b2a026d5017f6b556586f/data/site-scanning-target-url-list.csv

## Additional context and links

Add any other context, screenshots, or links to working docs.

## Checklist

List below the specific actions to be taken

- [ ] item 1
- [ ] item 2

**Comment by AKM399** [comment]
@AKM399 update from @RachelF

**Comment by mvogelgesang** [comment]
Original PR has yet to be merged (https://github.com/GSA/federal-website-index/pull/20). Suggest rebasing the changes and submitting updated PR
