### ISSUE TITLE
Crosswalk Website Lists

### ISSUE THREAD

**Issue by mvogelgesang** [GSA/EDX#291]
## Summary

A number of websites were recently added into Touchpoints and may not have been scanned. Compare the list of sites captured in our output reports with those in Touchpoints. Likewise, cross-check the Site Scanner list to see if we need to add additional sites.

## Checklist

- [x] Scan all sites present in TP but not in our current output, upload results
- [x] Compare list of sites in Site Scanner, submit PR with any updates (https://github.com/GSA/federal-website-index/pull/20)
- [x] Make/request relevant updates in TP if sites are out of date or require modifications (https://docs.google.com/spreadsheets/d/1OR-wxk11qmwF67zxAkf8U3vhzEe607Vcgu-qOv8P0jk/edit#gid=0)
- [x] Discuss website manager interview schedule with @AKM399 if changes are required

**Comment by mvogelgesang** [comment]
Scanned the following:

- 400yaahc.gov
- app.cloud.gov
- apps.ocfo.gsa.gov
- buy.gsa.gov
- content.fai.gov
- dashboard.data.gov
- federalist-builder.18f.gov
- files.18f.gov
- fleet.gov
- fmitservices-external.gsa.gov
- fmitservices.gsa.gov
- fmseec.fas.gsa.gov
- gsaadvantage.gsa.gov
- gsafleet.gov
- identitysandbox.gov
- labs.usa.gov
- markdown-helper.18f.gov
- open.sam.gov
- pivcac.prod.login.gov
- preview.login.gov
- resque.search.usa.gov
- roads.fas.gsa.gov
- slc.gsa.gov
- usdaadvantage.gsa.gov

**Comment by RachelF** [comment]
By definition, anything with "dev" in the URL should probably be excluded and tagged as "in_development" rather than production.
