### ISSUE TITLE
www.moss-slc.com

### ISSUE THREAD

**Issue by mvogelgesang** [GSA/EDX#293]
## Summary

moss-slc.com came onto our radar and we are working with PBS and OSC to find the site content a new home. 

## Additional context and links

Add any other context, screenshots, or links to working docs.

## Checklist

List below the specific actions to be taken

- [ ] item 1
- [ ] item 2

**Comment by mvogelgesang** [comment]
Met with all parties involved today ([notes](https://docs.google.com/document/d/1wK_ftFc5YsBwiTjlazK7l4_Rkl_FgmswdIFjR9FuaRk/edit)). Next steps are for the PBS team to work with the gsa.gov team. Some help may be needed down the road to setup proper redirects from the .com site to gsa.gov

**Comment by anatecture** [comment]
Getting redirected.
