### ISSUE TITLE
Follow article for InSite on change management

### ISSUE THREAD

**Issue by RachelF** [GSA/EDX#300]
## Summary

Publish a followup article on InSite about change management and share materials from the presentation by Gail/Monica.

## Additional context and links

[Draft article](https://docs.google.com/document/d/12gI5t4eeO_wLtjMLDQJfjZdf8GNp-vH_FSVc0pO0IuI/edit)
[To be linked here](https://insite.gsa.gov/services-and-offices/staff-offices/office-of-customer-experience/cx-happenings/customer-experience-community-of-practice)

## Checklist

List below the specific actions to be taken

- [x] Draft article
- [x] First round of edits
- [ ] Finalize
- [ ] Publish

**Comment by monicas-d** [comment]
I'm fine with it if you're good with it. Just reviewed Patricia's edits. Thanks!
