### ISSUE TITLE
Port Google Analytics data condenser to edxcli

### ISSUE THREAD

**Issue by mvogelgesang** [GSA/EDX#309]
## Summary

Migrate the existing [Web Analytics](https://github.com/GSA/EDX/tree/main/Tools/web-analytics) script into the new edxcli folder. 

This could benefit the team performing AMP scans across GSA websites.

## Additional context and links

This will require migrating the script into Typescript and adding flags/args for easier customization.

## Checklist

List below the specific actions to be taken

- [ ] Migrate to Typescript, pass all lint checks
- [ ] Incorporate flags (-n, number of top pages per domain, -o, output directory)
- [ ] Incorporate args (input file)

**Comment by AKM399** [comment]
@mvogelgesang still active on this?  can we move it back to inbox?

**Comment by AKM399** [comment]
work completed.
