### ISSUE TITLE
Write blog post on Organizational Change (from 2 perspectives)

### ISSUE THREAD

**Issue by ryanwoldatwork** [GSA/EDX#32]
Write blog post on Organizational Change (from 2 perspectives)

* HR/Change Management
* Agile/Software

Potential topics

- Commonalities
- Differences
- Synergies
- Vocabulary

[Working Draft](https://docs.google.com/document/d/1VzUSZiIT_oAJO9WHQZRKX_kDAY9BIC94LRKgYhCVXMs/edit) 🔒

**Comment by gailsprinkle** [comment]
Ryan, can you add me as an assignee? Or is there a way I can do that? Thanks

**Comment by ryanwoldatwork** [comment]
Hi @gailsprinkle, clicking the gear icon near "Assignees" in the right-hand column will display a list of users available to assign.

I've added you 😄

**Comment by gailsprinkle** [comment]
@ryanwoldatwork  Thanks! I actually don't see a gear icon near Assignees. Wonder if that is because you "own" this post and perhaps I don't have permission to add people?

**Comment by monicas-d** [comment]
I had the same challenge as I was trying to assign here and didn't see
anything.


-- 

U.S. General Services Administration

*Monica Suber-Duffy*, GCDF <http://www.cce-global.org/GCDF> and Federal
Internal Coach
<https://insite.gsa.gov/topics/training-and-development/developmental-services/coaching-services>

Organizational Development Consultant
<https://insite.gsa.gov/topics/training-and-development/developmental-services/organizational-development>

GSA  | OHRM Talent Development

Pronouns: She/Her/Hers

Office of Human Resources Management (OHRM)

1800 F St, NW

Washington, DC 20526

Mobile: (202) 701-8197

E-mail: ***@***.***

Join the Yoga & Mindfulness Chatter Group
<https://gsa.my.salesforce.com/_ui/core/chatter/groups/GroupProfilePage?g=0F9t0000000aU0i>,
and see our page on InSite
<https://insite.gsa.gov/topics/training-and-development/continuous-learning/yoga-mindfulness>

Between stimulus and response there is a space. In that space is our power
to choose our response. In that response lies our growth and our
freedom.-Viktor
E. Frankl

<https://insite.gsa.gov/topics/hr-pay-and-leave>

**Comment by ryanwoldatwork** [comment]
It sounds like a permissions issue. So it makes sense that you would not see the gear, in that case.
You are an assignee however.
