### ISSUE TITLE
Website Evaluation - sites that need replacement

### ISSUE THREAD

**Issue by AKM399** [GSA/EDX#320]
Create a list where people can add sites for replacement in the website evaluation project- and have the team see it has happened, when it has happened.

- [ ] Dev.identitysandbox.gov - replaced with agile.18f.gov
- [ ] Developers.login.gov - replaced with cdo.gov
- [ ] asis.search.usa.gov - replaced with apps.ocfo.gsa.gov
- [ ]  CAO.gov - replaced with analytics.usa.gov
- [ ] discovery.gsa.gov - replaced with api.data.gov

**Comment by AKM399** [comment]
I have a meeting with Clayton S. in FAS this monday that could impact what sites we slide in here.

**Comment by AKM399** [comment]
https://docs.google.com/spreadsheets/d/1pWKbjGi4KPebDFWWMZiLELgswA4xoo-uKpZ-Vl99fT0/edit?usp=sharing

if its pink, to be added

**Comment by RachelF** [comment]
Actually @AKM399 , if column B is pink, that means we need to delete it, because the site has either been decommissioned or is mis-categorized in Touchpoints. (Ignore the pink.) :)

**Comment by AKM399** [comment]
my bad, i think i understood it but it got jumbled on paper.  Working the list now, update coming.

**Comment by AKM399** [comment]
all sites added on github or airtable.   Keeping this issue active since we're likely to get more to add later.

**Comment by AKM399** [comment]
closed, new issue to be made  in year 2
