### ISSUE TITLE
Performance Plan Template

### ISSUE THREAD

**Issue by mvogelgesang** [GSA/EDX#34]
## Summary

Could we as an EDX team publish a template performance plan competency model for website owners and program managers.

**Comment by ryanwoldatwork** [comment]
Any ideas on what this might look like?

* being online
* using modern USWDS
* having a (to be defined) accessibility score per an automated checker
* have a backlog; a place where work to be done is reliably tracked and processed
* has basic website things:
  * web analytics; DAP
  * a customer feedback mechanism
  * usa-banner
  * common footer
  * no obvious offenses of GSA branding guidelines

After indicating and automated tracking of some basic characteristics,
the organization needs to design and enact a process to address gaps.

**Comment by mvogelgesang** [comment]
I had proposed the following performance metric- very similar to what you outlined above:

> **Description**: Percentage of externally-facing websites managed by IC which employ core USWDS and GSA Branding principles or have been consolidated into sites which meets specification. (this covers us for the fai.gov migration to acquisition.gov). This first year goal will advance GSA's sites into greater compliance using binary criteria (has HTTPS, USWDS Banner, etc) whereas future years would address compliance areas that have degrees of maturity (accessibility, mobile friendliness, user centered design)
> 
> **Website Population**: At least 30 sites, potentially 60 total. By best count 2 sites currently in compliance.
> 
> **Details**: Sites must: 
> - Use USWDS Identifier (https://designsystem.digital.gov/components/identifier/)
>     - Appropriate FOIA, Privacy, Accessibility, and Linking Policy links
>     - Identifies the site as managed by GSA & other agencies as applicable
> - Use USWDS Banner (https://designsystem.digital.gov/components/banner/)
> - Use USWDS Footer (https://designsystem.digital.gov/components/footer/)
>     - Email, phone, or weblink for contact
> - Provide Search function
> - Utilize Digital Analytics Platform, DAP (https://digital.gov/guides/dap/add-your-site-dap/)
> - Default to HTTPS (HSTS)
> 
> **Measurement**: Automated tooling via TTS Site Scanning and scripts can provide consistent and repeatable results for IC provided we have a list of IC managed sites."

**Comment by ryanwoldatwork** [comment]
@mvogelgesang, is this work in place? or still moving forward?

cc @gailsprinkle, @monicas-d, and @RachelF, as this story has to do with `professional-development` and performance plans.

**Comment by mvogelgesang** [comment]
@ryanwoldatwork yes, it has been included in GSA IT-wide performance plans.

**Comment by AKM399** [comment]
@mvogelgesang once its included in gsa-it wide performance plans, is there next steps?   Should we close for now?  reach out to GSA-IT on how people scored as a part of our performance metrics?

**Comment by monicas-d** [comment]
@mvogelgesang Can we see a sample of what it looks like in the GSA-IT perf plan? Thanks!

**Comment by monicas-d** [comment]
Linking these together: https://github.com/GSA/EDX/issues/113

**Comment by mvogelgesang** [comment]
@monicas-d same text as was proposed but not specific to the 60ish sites managed by IC but the total GSA IT portfolio. The actual metric (numbers) have yet to be established

**Comment by monicas-d** [comment]
@mvogelgesang met with @gailsprinkle and I today. The language that landed into GSA-IT performance plans included: Language in the GSA-IT perf plans: % of GSA IT-supported websites complaint with 21st Century Digital IDEA Act Principles

They haven't finalized the measurement and are working on it. 

Mark said each office should establish their own baseline and then work towards what % they want to accomplish each year in their performance plans.

Next steps:
- Gail to consult with Allie Peterman & Rachel Surick - IDR to discuss the mechanics of how GSAIT got this language in their perf plans
- Gail & Monica to meet with Mike Seymour - CSE about how to get such language in website manager perf plans
- Gail & Monica can talk with Star about this idea: Explore how Dave Shive can present this idea to Dave Z to make TTS-wide (to present to Christina Brydges and Star)

**Comment by AKM399** [comment]
notes from gail:   Two levels.   SES working on one side, getting it into their performance plan.   needs their strategic plan.   Pt2.  GSA staff level - website manager level.   Did not ask questions on their roles.   As follow up occurs with interviews questions about their role occurs.   PDs range from technical to generic.  Awaiting synthesis.

**Comment by anatecture** [comment]
How does this work stand @monicas-d @gailsprinkle? Did we accomplish this through our work putting together the [qualities of website manager for PDs](https://github.com/GSA/EDX/issues/113)?

**Comment by monicas-d** [comment]
We haven't been able to revisit it yet. We've been focused on our
interviews. Thanks for your patience!


-- 

U.S. General Services Administration

*Monica Suber-Duffy*, GCDF <http://www.cce-global.org/GCDF> and Federal
Internal Coach
<https://insite.gsa.gov/topics/training-and-development/developmental-services/coaching-services>

Organizational Development Consultant
<https://insite.gsa.gov/topics/training-and-development/developmental-services/organizational-development>

GSA  | OHRM Talent Development

Pronouns: She/Her/Hers

Office of Human Resources Management (OHRM)

1800 F St, NW

Washington, DC 20526

Mobile: (202) 701-8197

E-mail: ***@***.***

Join the Yoga & Mindfulness Chatter Group
<https://gsa.my.salesforce.com/_ui/core/chatter/groups/GroupProfilePage?g=0F9t0000000aU0i>,
and see our page on InSite
<https://insite.gsa.gov/topics/training-and-development/continuous-learning/yoga-mindfulness>

Between stimulus and response there is a space. In that space is our power
to choose our response. In that response lies our growth and our
freedom.-Viktor
E. Frankl

<https://insite.gsa.gov/topics/hr-pay-and-leave>

**Comment by anatecture** [comment]
Thanks for the update @monicas-d; let us know if we need to discuss before deciding a path forward as well.
