### ISSUE TITLE
recycling.gsa.gov

### ISSUE THREAD

**Issue by anatecture** [GSA/EDX#341]
## Summary

New DNS request for recycling.gsa.gov came through ServiceNow.

**Comment by anatecture** [comment]
@mvogelgesang reached out to connect w/ Greg W (requester) and Joshua M

Josh got back; they're just the tech side. Y W-C and Terry F are the program side. Josh wanted to know what we're measuring. Ana replied wit the following: 

In answer to your question, our team is measuring the following parameters of websites: 

1. USWDS header, footer, banner, identifier implementation from web crawlers + human review (qualitative + quantitative data)
2. Mobile Performance from Google Lighthouse (quantitative data)
3. Accessibility scored by AMP (quantitative data)  [not applicable at this time in your case]
4. HCD interview data (qualitative data) [not applicable at this time in your case]
5. Connectivity with related teams through interview and DAP (qualitative + quantitative data) [not applicable at this time in your case]
6. Required links from web crawlers + human review (quantitative data)  

The crawlers are a combination of data pulled from TTS' Site Scanner tool and some custom crawlers. Let us know if you have any questions about this data and the methodology driving it; we're happy to answer. 

For your new site, right now, we're interested in finding out the following: 

1. What's the date for the new page to go live? 
2. Who can we list in [GSA's Website Inventory](https://touchpoints.app.cloud.gov/admin/websites) (log in required) as the website manager and the website contact? We prefer the program person be listed as the manager, while a technical person could be listed as the contact. 
3. What's the plan for the old [ncrrecycles.gsa.gov](http://ncrrecycles.gsa.gov/) once the new page goes live? Are you planning a redirect? If yes, what's the timeline on the redirect coming down? 
4. Who's the primary customer for this new site? Feds? Public? Industry? A mixture of audiences? 
5. What type of site is the new site? Is the site informational or will customers be able to complete transactions on it?

**Comment by anatecture** [comment]
Y W-C answered: 

What's the date for the new page to go live?   [recycling.gsa.gov](http://recycling.gsa.gov/) will go live tentatively mid-April.  **We are currently working with security and AppOps to make this available outside of VPN.**

Who can we list in [GSA's Website Inventory](https://touchpoints.app.cloud.gov/admin/websites) (log in required) as the website manager and the website contact? We prefer the program person be listed as the manager, while a technical person could be listed as the contact. 
**Website manager - Yuk Wong-Chiu, Website contact - Yan Zeng**

What's the plan for the old [ncrrecycles.gsa.gov](http://ncrrecycles.gsa.gov/) once the new page goes live? Are you planning a redirect? If yes, what's the timeline on the redirect coming down?  **A re-direct from old URL to new URL when [recycling.gsa.gov](http://recycling.gsa.gov/) goes live and re-direct will be in place for a few months.**

Who's the primary customer for this new site? Feds? Public? Industry? A mixture of audiences?  **A mixture of audiences.**

What type of site is the new site? Is the site informational or will customers be able to complete transactions on it?   **No, it is only a read-only site and customers can generate a report.**

**Comment by anatecture** [comment]
Site is live https://recycling.gsa.gov/ but the team has not pulled down ncrrecycles. 

Reach out to team @AKM399

**Comment by mvogelgesang** [comment]
ncrrecycles.gsa.gov is no longer live, closing
