### ISSUE TITLE
Redirect Service

### ISSUE THREAD

**Issue by mvogelgesang** [GSA/EDX#35]
## Summary

As more and more sites are put through the operational framework, there will be sites where content needs to be migrated to a new home. Under such a circumstance, the previous URL's should redirect users to the new content location.

### Scenarios

Old|New|Description
---|-----|-----------
blah.gsa.gov/about blah.gsa.gov/task/dosomething|gsa.gov/blah/about gsa.gov/blah/task/dosomething|blah.gsa.gov has been decommissioned and all relevant pages now live at a subdirectory of the gsa.gov site
bloop.gsa.gov/info1 bloop.gsa.gov/info2 | gsa.gov/bloop | content from bloop.gsa.gov has been moved to gsa.gov but completely reorganized in the process. Direct page redirects do not make sense so users should be redirected to the base directory on the new site (gsa.gov/bloop).
bleep.gsa.gov/this bleep.gsa.gov/that | gsa.gov/something/this digital.gov/that | bleep.gsa.gov contained content that was dispersed to other GSA-managed web properties. /this went to a gsa.gov directory, /that went to digital.gov

### Existing GSA Services

- The ICE organization within GSA IT manages this service for a number of domains
- 18F has a managed capability at https://github.com/18F/pages-redirects

## Checklist

Research existing redirect solutions at GSA
- The ICE organization within GSA IT manages this service for a number of domains

Further research [pages-redirects](https://github.com/18F/pages-redirects) solution

Ensure GSA IT's process includes the good parts from the TTS checklist (or consider using the same checklist). So, conduct an audit with GSA IT about the existing process.

- Search Engine Optimized
- Permanent Redirects

### Develop Acceptance Criteria

- [ ] GSA IT receives TTS staff member's `DNS requests` and routes request to TTS Staff with (existing) GitHub Issue Template

- [ ] Touchpoints receives any GSA staff member's "Website Sunset" request and routes request to EDX Staff
- [ ] potentially: GSA IT adopts github/terraform as a way to manage DNS

**Comment by ryanwoldatwork** [comment]
@mvogelgesang - is there a way to move this forward?

And, is there a Definition of Done for this story?

The next identified task appears to be answering the question: is it something that could be used by GSA writ large? 
Engaging ICE and TTS would need to occur to review processes and choose a unified way forward.

**Comment by ryanwoldatwork** [comment]
update: @mvogelgesang emailed IT and a meeting will occur to chat about this.

Notably:

> I anticipate a major component of consolidating this into a single enterprise service would be to engage with the IT Service Desk to establish a service catalog item with associated workflow

**Comment by ryanwoldatwork** [comment]
met today to chat about this.

there appears to be an opportunity to standardize requests around this, as follows:

---

Allow all users to request DNS assistance via the helpdesk.
This will also allow GSA IT become acquainted with GitHub and more TTS processes.

![Screen Shot 2021-09-29 at 10 30 43 PM](https://user-images.githubusercontent.com/64987852/135392935-0ec8a8f7-5c26-4061-b4eb-f3b60c08b996.png)

**Comment by AKM399** [comment]
revived if there is a site where it is needed.   TTS is moving towards service now (note from ryan)
