### ISSUE TITLE
Digital Council Discussion Topic - "archived" sites

### ISSUE THREAD

**Issue by mvogelgesang** [GSA/EDX#358]
## Summary

Topic of discussion for the Digital Council. How should archived sites such as https://www.usability.gov/ be handled? Should we encourage the content to move into another site? Remove it altogether? 

## Additional context and links

Add any other context, screenshots, or links to working docs.

## Checklist

List below the specific actions to be taken

- [ ] item 1
- [ ] item 2

**Comment by AKM399** [comment]
moved to in progress because its a DC topic today.

**Comment by AKM399** [comment]
via @ryanwoldatwork there is some existing work around if content stays or goes in archived.  please reword if this is not accurate.

**Comment by ryanwoldatwork** [comment]
* https://handbook.tts.gsa.gov/launching-software/infrastructure/
* https://github.com/18F/tts-tech-portfolio/blob/main/.github/ISSUE_TEMPLATE/decommission.md
* https://www.archives.gov/records-mgmt/policy/managing-web-records-index.html

**Comment by mvogelgesang** [comment]
@RachelF the TTS Tech Portfolio guide has some good info that could inform the decommissioning side of DLP >> https://github.com/18F/tts-tech-portfolio/blob/main/.github/ISSUE_TEMPLATE/decommission.md

On July 12, 2022, the GSA Digital Council had folks from records management attend and discuss our duties as they relate to websites. 

> GSA’s Records Officer joined us to discuss web records management. He developed this [updated guidance for web teams](https://docs.google.com/document/d/1s9nOtc_V86Z_z8z9449367b3h6tKoad7JfE9aUhCYhc/edit). Teams should also review [GSA’s Web Records Primer (InSite)](https://insite.gsa.gov/cdnstatic/insite/Records_Management_Primer_for_Website_Development%2C_Use%2C_Maintenance_and_Decommissioning_8-31-2020.pdf)

If this information has been included into the DLP, I think this issue can be closed.
