### ISSUE TITLE
HSSOs (SES) Performance Plans - FY23 Proposed Language & Next Steps

### ISSUE THREAD

**Issue by monicas-d** [GSA/EDX#362]
4/14/2022
Meeting attendees: Karla Hester, Gail Sprinkle, and Monica S-D

- Gail: We are ready to put language into SES performance plans; Katy is on board; we now need to define the steps we need to take next to make this happen
- We’ll send language to you, and then clear through Robin and Katy
- This is not the language, but what we want to do in GitHub under [Milestones](https://github.com/GSA/EDX/milestone/10):
HSSOs should prioritize digital stewardship and thus create a culture at GSA that improves management and governance of GSA's digital properties, and deliver a more consistent, clear, and helpful experience to our customers. EDX team hopes to achieve that culture change by establishing draft language to include in HSSOs' performance plans around digital stewardship.

- Karla: Is it a proposal for all SES or select SES and who?
- https://docs.google.com/document/d/1BmfqxEPlr_wfwA_EYXrob0uHEgpsBTHhmSC768Zqvg8/edit
- Karla's SES Performance Plan Template Copy: 
https://docs.google.com/document/d/1vx9iz0R7g7zjF0cJ4fyo8XhhphuRCvFErbkB5V3qq-E/edit

- Gail: we need to figure out the roster for those involved. HSSOs: Who runs an org that has public facing websites?

Exec Board signing members:
Katy Kale - does she have in hers? I imagine so…?
Ed Walters
Teressa Wykpisz-Lee - Channing Gate? Not yet; she’s a political appointee
David Shive
Crystal Philcox - who replaces her?
Allison Azevedo
Dan Pomeroy
Dave Zvenyach
Anyone else?

- Karla: Which section in their perf plan would this fit into? Websites? Customer Experience? What?

- Karla: I would consider flesh this out and consider propose this for FY23 language into per plans rather than FY22; if this is the case, you’ll need to have it completed **_by no later than July_**!

ACTION ITEMS: 
Gail/Monica:

- [x] Share the draft language with Karla
- [x] Finalize the roster for which SES should be included in this and share with Karla
- [x] Set up meeting with Karla again in two weeks## Summary

**Comment by RachelF** [comment]
Thanks for the update @monicas-d ! My opinion is that ALL SESers should have it in their perf plans, because ALL GSA offices (even the IG) host content somewhere, even if it's just a few pages on GSA.gov, so they need to also be accountable for their section of the site, and follow all the GSA guidelines and federal web policies (PL, 508, etc), just like everyone else.

**Comment by monicas-d** [comment]
Hi Team, I'll allow @gailsprinkle to elaborate more on this as she's been working mostly on it but we started out with one metric to include, Leading People. Then, we added a draft for Business Acumen. Upon talking with Karla Hester and Ana M F, we decided to include only Leading People for FY23 perf plans, and consider Business Acumen for FY24 perf plans. 

Gail and I still feel we start in FY23 with only select SESers of those public facing sites we know are impacted. I realize Ana MF and Rachel F want it in all SESers plans.

Note - this doc reads FY22 but noting this is only a FY22 performance plan template - 

https://docs.google.com/document/d/1RZGyWRM_dEifks4IWe8bJZT7654CAG4TCZKiRuDzmPU/edit

**Comment by monicas-d** [comment]
Monica Suber-Duffy - CSDPA <monica.suber@gsa.gov>
Thu, Jul 14, 3:21 PM (2 days ago)
to Mark, Rachel, Ana, Jonah, Aaron, Gail

Hi EDX team,

Gail and I are excited to announce that we have completed our current draft of the SES performance plan language. Kudos to those who worked together in ironing out a lot of these details!

I am attaching the draft language [here](https://docs.google.com/document/d/14fZFpmoO_cOV7NZkvu6IyHwtfuvOPqhHQkEXLY1oPNE/edit) for your review. ***We are not asking for feedback unless there is something glaring at this point.***

What we plan to do next is to share with Peter, Sarah, and Rachel to review and discuss how:

- They would like to share back with the Digital Council
- Ask them for their input around the Digital Council approval process (see level 5 in the link above for more as this could be a massive project if the DC has to approve)
- Once number 2 above is ironed out, we'll then share with Ed for his review, and up to Katy (copying Karla Hester) for final review/approval. From there, we plan to present to the Executive Board in August.

**Comment by monicas-d** [comment]
In terms of to whom we include this language into their performance plans, we are still discussing. As of now it sounds like all HSSOs but likely will not be limited to them. Thanks!

**Comment by anatecture** [comment]
DC co-chairs have agreed that simple submission of the action plans to the DC will be sufficient for approval this first year.

**Comment by monicas-d** [comment]
Today Ana and I spoke with Ed and he approved the SES language. We made slight edits here: https://docs.google.com/document/d/14fZFpmoO_cOV7NZkvu6IyHwtfuvOPqhHQkEXLY1oPNE/edit

Next steps include: 

- [ ] Share with the Digital Council next week
- [ ] Share with Katy Kale 
- [ ] Share with the Executive Board
- [ ] Share with Karla/Executive Resources
- [ ] Karla will share then with the Performance Review Board for review and updates if necessary
- [ ] Publish into their performance plans

There is room to update them before mid-year so that is something to consider if we need to also. Thanks!

@anatecture @gailsprinkle

**Comment by monicas-d** [comment]
@RachelF Does even Ed as head of OCE have a public facing website for GSA? We are talking with Karla in Exec Resources on this. Thanks!

**Comment by RachelF** [comment]
@monicas-d  Even if they don't have their own website, pretty much every office in GSA has at least some public-facing content on GSA.gov, which needs to follow GSA guidance. Granted, the internal facing offices such as OCE are less likely to have their own websites since the scope we're focusing on is public-facing. Now that I'm thinking this angle thru... you have a point that including internal-facing teams may be problematic. Most of their web content is internal- (not public-) facing. Lots of those internal-facing teams have google sites... but they are not public-facing.
