### ISSUE TITLE
Transactional Websites

### ISSUE THREAD

**Issue by mvogelgesang** [GSA/EDX#363]
## Summary

Need to further parse "what is a transactional website?". Today we lump websites into categories such as informational, application, and application login. However, a finer grain of detail may be required to cover sites such as [8astars](http://8astars.fas.gsa.gov/) which doesn't require a login but immediately requires user interaction.

## Additional context and links

Add any other context, screenshots, or links to working docs.

## Checklist

List below the specific actions to be taken

- [ ] item 1
- [ ] item 2

**Comment by AKM399** [comment]
@mvogelgesang closed but feel free to open if you feel not done.  @RachelF is sharing definitions with DC today.
