### ISSUE TITLE
Prototype Status Card implementation

### ISSUE THREAD

**Issue by mvogelgesang** [GSA/EDX#366]
## Summary
@anatecture produced some area charts (https://codepen.io/anatectureatwork/pen/VwymwoX?editors=1100) which can be used as a way to express a websites shape. 

## Additional context and links

Add any other context, screenshots, or links to working docs.

## Checklist

List below the specific actions to be taken

- [x] Establish a data structure which can inform the charts
- [x] create subsequent tickets to automate the fetching of this data #378

**Comment by AKM399** [comment]
@anatecture and @mvogelgesang does this fit in a larger issue?  If not should we move to in progress?

**Comment by mvogelgesang** [comment]
Merged via #380
