### ISSUE TITLE
a130.cio.gov

### ISSUE THREAD

**Issue by anatecture** [GSA/EDX#369]
- Stakeholders?
   - US GSA

- DNS Subtype: 
   - Change Record

_Ana Note: I think this is a long standing redirect? If yes, maybe we need to reach out to this team and ask when they plan to take it down_

**Comment by anatecture** [comment]
Dm alicia yozzi as the manager of cio.gov

**Comment by AKM399** [comment]
@AKM399 talk to them about redirect, check and see if it has hits

**Comment by mvogelgesang** [comment]
Ran GA looking at the past year- no referrals from a130.cio.gov. This can be removed.

**Comment by AKM399** [comment]
@AKM399 talk to alycia see if we can get it turned  off.

**Comment by AKM399** [comment]
emailed 5/10

**Comment by mvogelgesang** [comment]
site no longer resolves, closing
