### ISSUE TITLE
ag-dashboard.gsa.gov

### ISSUE THREAD

**Issue by anatecture** [GSA/EDX#370]
- This the new Acquisition Gateway admin interface. Acquisition Gateway is a workspace for acquisition professionals and federal buyers to connect with resources, tools and each other to improve acquisition government-wide.

- Stakeholders?
   - Maggie Podgwaite - QT3, Charles J Burton

**Comment by anatecture** [comment]
Email Maggie to see what site(s) this is taking the place.

**Comment by anatecture** [comment]
emailed 05/09

**Comment by mvogelgesang** [comment]
redirects to OMB Max for login, closing
