### ISSUE TITLE
sourcedata.gsa.gov

### ISSUE THREAD

**Issue by anatecture** [GSA/EDX#371]
- This is for the FAS Source Data Automation application, an application to build automation for FAS Source Data and be the sources of truth for data related to the schedule SIN table.

- Stakeholders?

   - DX-Tina Burns
   - CALM-Keonia Cobbins
   - Catalog-Zach Lerner
   - SRP-Derek Tribble
   - FSS19-April Kestyn
   - MRAS-Kevan Kivlan
   - IRAN-Lillian Miller
_Ana Note: This seems right, but I’d like to know what sites they’re shutting down once this one is stood up_

**Comment by anatecture** [comment]
Email Brad and ask what sites this is taking the place of

**Comment by AKM399** [comment]
@AKM399 check prev brad responses

**Comment by AKM399** [comment]
I think I'm going to try to call brad and ask more about it?

**Comment by mvogelgesang** [comment]
Website record created in touchpoints, closing https://touchpoints.app.cloud.gov/admin/websites/629
