### ISSUE TITLE
ussm.gov

### ISSUE THREAD

**Issue by anatecture** [GSA/EDX#372]
_Ana Note: This site is from OSSPI and is not in our inventory. Let’s find out why. They requested a cert renewal. _

**Comment by anatecture** [comment]
This is in touchpoints as ussm.gsa.gov. Website manager needs to be updated. @anatecture will email RW to see who manager can be updated to.

**Comment by hatfieldjm4** [comment]
ussm.gsa.gov already exists. 
ussm.gov is not set up yet (it currently redirects to www.ussm.gov)

**Comment by mvogelgesang** [comment]
ussm.gov and www.ussm.gov redirect to ussm.gsa.gov. Closing, no action needed
