### ISSUE TITLE
calm.gsa.gov

### ISSUE THREAD

**Issue by anatecture** [GSA/EDX#373]
- Purpose: CALM is an Acquisition Management and Contract Writing System specifically designed to support Federal Government agencies. It is used to manage procurement actions through all phases of the acquisition life cycle, from procurement planning to contract close-out, using agency-specific guidelines and policies. CALM incorporates the Federal Acquisition Regulations (FAR) and facilitates accountability and transparency within an agency’s GSA acquisition of goods and services. As a browser-based enterprise-wide application, CALM requires no footprint on a user’s workstation. GSA CALM integrates two COTS products to meet the overall objectives of the CALM solution, Unison PRISM and Bizagi Cloud, and a third custom IaaS solution called Octo CALI. 

- Currently, each CALM component has its own URL and users need to click a separate, difficult to remember URL to enter each component. The new [calm.gsa.gov](http://calm.gsa.gov/) URL’s purpose is to provide users with a more uniformed and bette experience with one, easy to remember path to all 3 components.

_Ana Note: This has been a big deal. Since components are being tied together, what sites if any will be shut down because this is coming online?_

**Comment by anatecture** [comment]
Email Brad and ask what sites this is taking the place of

**Comment by AKM399** [comment]
emailed 4/28

**Comment by AKM399** [comment]
@AKM399 needs to update

**Comment by mvogelgesang** [comment]
Added to Touchpoints, https://touchpoints.app.cloud.gov/admin/websites/631

**Comment by AKM399** [comment]
its a brand - subject to OSC, team is not responsive to request on information.
@mvogelgesang  added to non compliance list.

**Comment by AKM399** [comment]
bring to charlotte.  claims to have launched internally.  Its public.

**Comment by AKM399** [comment]
still pending.

**Comment by AKM399** [comment]
closed due to lack of options.
