### ISSUE TITLE
Track Backlog URL

### ISSUE THREAD

**Issue by AKM399** [GSA/EDX#376]
## Summary

I want to employ backlog practices and backlog examination as a data point in EDX.   This is because it is a fundamental practice in all web practices.

How do we make it easy so people don't feel like we're looking for their dirty laundry?

How do we turn the practice of backlog visibility into directing work efficiently across many lines.  All backlogs direct to practice groups instead of turning all managers into mini practice units.

## Checklist

List below the specific actions to be taken

- [ ] Prepare to discuss in EDX meeting
- [ ] Consider in meet up event

- [ ] get the backlog data
- [ ] make it easy to navigate and standardize high level practices?

**Comment by ryanwoldatwork** [comment]
What are next steps here?

I think it is reasonable for the organization to know where the work for a given product is, and also know (be able to answer the business question of) if a product even has a defined backlog (list of work) or not.

**Comment by AKM399** [comment]
refer to ryans working group
