### ISSUE TITLE
IAELibrary.end.ds.gsa.gov

### ISSUE THREAD

**Issue by anatecture** [GSA/EDX#377]
This is a record for a IAE Tape Library so we can configure a certificate for SSL.

Stakeholders: Matthew Schmaus - [matthew.schmaus@gsa.gov](mailto:matthew.schmaus@gsa.gov)

**Comment by AKM399** [comment]
@AKM399 email forward - tell us about your site, intro, internal or external.  self deadline end of week

**Comment by AKM399** [comment]
reply from matthew:

<html>
<body>
<div class="aju" style="cursor: default; float: none; padding: 0px 16px; align-items: center; display: flex; height: 80px; min-width: 40px; color: rgb(34, 34, 34); font-family: Roboto, RobotoDraft, Helvetica, Arial, sans-serif; font-size: medium; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><div class="aCi" style="position: relative;"><img id=":mx_27-e" name=":mx" src="https://ssl.gstatic.com/ui/v1/icons/mail/profile_mask2.png" class="ajn" jid="matthew.schmaus@gsa.gov" data-hovercard-id="matthew.schmaus@gsa.gov" data-name="Matthew Schmaus - IDT-C" aria-hidden="true" style="display: block; width: 40px; height: 40px; border-radius: 50%; background-color: rgb(164, 194, 244);"></div></div><div class="gs" style="margin: 0px; padding: 0px 0px 20px; width: 1844px; color: rgb(34, 34, 34); font-family: Roboto, RobotoDraft, Helvetica, Arial, sans-serif; font-size: medium; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><div class="gE iv gt" style="font-size: 0.875rem; padding: 20px 0px 0px; cursor: auto;">

Matthew Schmaus - IDT-C | Matthew Schmaus - IDT-C | Thu, Apr 28, 4:03 PM (12 days ago) |   |  
-- | -- | -- | -- | --
Matthew Schmaus - IDT-C
to me, Ana | to me, Ana
to me, Ana

</div><div id=":9yz"><div class="qQVYZb"></div><div class="utdU2e"></div><div class="lQs8Hd" jsaction="SN3rtf:rcuQ6b" jscontroller="i3Ohde"></div><div class="btm"></div></div><div class=""><div class="aHl" style="margin-left: -38px;"></div><div id=":9ym" tabindex="-1"></div><div id=":9yx" class="ii gt" jslog="20277; u014N:xr6bB; 4:W251bGwsbnVsbCxbXV0." style="direction: ltr; margin: 8px 0px 0px; padding: 0px; position: relative; font-size: 0.875rem;"><div id=":9yy" class="a3s aiL " style="font: small / 1.5 Arial, Helvetica, sans-serif; overflow: hidden;"><div dir="ltr">Aaron,<div><br></div><div>This is a DNS record being generated so we can create an SSL certificate for a tape library.  This will only be internally used and only by support staff of that tape library. Let me know if you have any further questions.</div></div></div></div></div></div>
</body>
</html>

**Comment by AKM399** [comment]
not in touchpoints. recommend killing the issue @anatecture

**Comment by mvogelgesang** [comment]
not a public site, closing
