### ISSUE TITLE
Perform an audit or data collection or website cost data

### ISSUE THREAD

**Issue by ryanwoldatwork** [GSA/EDX#38]
### User Story

As a GSA finance staffer,
I want to know the cost to maintain each site
And I want to know the cost to update each site to be in accordance with 21st Century IDEA

### Acceptance Criteria

To be clarified.

Website managers can enter their cost data.
Digital Council members can view cost data.

**Comment by ryanwoldatwork** [comment]
@RachelF - is there a specific use or requirement for this work?

I'm concerned cost data is a slippery slope to address within Touchpoints. Costs vary and should happen at the business level, perhaps above the Website Manager.

**Comment by RachelF** [comment]
@ryanwoldatwork GSA doesn't have a good handle on how much we currently spend on our websites; I'd like to have at least a ballpark so we can show cost savings as we consolidate.
BUT this is not a super high priority right now, so I'll close this for now
