### ISSUE TITLE
Website Archetypes

### ISSUE THREAD

**Issue by anatecture** [GSA/EDX#394]
## Summary

@AKM399 has noticed a pattern in our website evaluations that there are a few broad customer personas seeking a few broad website types. These include: 

- **Marketing** customers - people who need to be pointed where to go to do business
- **Developer** customers - show me code and standards
- **Contract and finance** customers - technical but money oriented
- **Physical product** customers - show me the technical detail of physical products I can buy through GSA 

@anatecture proposes the Service Design team takes this on for an autumn 2022 project. The project can center on tagging each website in the Inventory with a persona. This can also work w/ @hatfieldjm4's FEAF work and tying each website to a service.

**Comment by anatecture** [comment]
Possible fall project manifestation of this: 
Massive card sort idea for a fall project: we talk to 9 GSA teams and 9 public customers and 9 federal customers in the fall and figure out if this would be a welcome change and how it would look.

**Comment by ryanwoldatwork** [comment]
Recently, Touchpoints add support for [Personas](https://touchpoints.app.cloud.gov/admin/personas/), which is a very basic and exploratory feature at this time.

I added the 4 Personas above to Touchpoints.
I will be adding more instruction and context to improve guidance. (Feedback welcome)

Personas can be associated with Websites to enable reports like:

* Which Personas does a Website serve?
* What Websites serve a Persona?



![Screen Shot 2022-06-14 at 1 38 26 PM](https://user-images.githubusercontent.com/64987852/173684365-ae3d4897-caf5-4ca3-ae16-cf97a1e33371.png)

**Comment by AKM399** [comment]
project is redefined as website archtypes.  looking for points of comparison between pages

**Comment by AKM399** [comment]
https://app.asana.com/0/1202817062418327/timeline

**Comment by AKM399** [comment]
What is Project:  A way to provide context around content, users, functionality and help us identify more ways to streamline and improve the user experience

Why is the Project:  The website personas project will allow GSA to understand our websites in a new way and to group them together by service area, which we haven’t been able to do before. 

How the Project:  We’ll do this in 12 weeks, spending 4 weeks parsing and validating our taxonomy, 4 weeks reaching out to teams for clarification, and 4 weeks creating a map and grouping the sites. Output will be a field in the inventory and possibly a visualization?

**Comment by AKM399** [comment]
spoke with Jonah, focusing on keyword over capabilities and services for now.

Searching for people to test against the "who is your cohort" question.

**Comment by AKM399** [comment]
https://www.figma.com/file/aGg3C1ITZMPtnMFHE3lpPc/Untitled?node-id=0%3A1

**Comment by AKM399** [comment]
Interview guide  https://docs.google.com/document/d/1Tb8Th2qQSpK5_DAjPo0loIrzFRFsoMp4pefVGSIwP3I/edit?usp=sharing

**Comment by AKM399** [comment]
documentation  https://docs.google.com/document/d/14_1-m53kk961lBPLWhPjCb-d09V8UOnWo1N8mEpIZD0/edit?usp=sharing
