### ISSUE TITLE
How to account for sites in Touchpoints that are no longer public-facing

### ISSUE THREAD

**Issue by hatfieldjm4** [GSA/EDX#395]
As a Touchpoints website inventory user, I want to track the websites that were once public but have recently been converted to non-public (e.g. you must be on GSA's VPN in order to access the DNS) so that I can distinguish it from the sites that were removed from the inventory due to decommissioning. 

For example, roads.fas.gsa.gov is no longer public-facing. The only option I currently have in Touchpoints is to either delete it completely from the inventory or to mark it as decommissioned. I don't want to delete it completely because it was once public-facing, and I want to know which public-facing sites were eliminated from the production inventory.  I don't want to mark it as decommissioned because it technically is not decommissioned; it's just not publicly accessible. 

One possible solution would be to include an option in the production status field, like "Converted to non-public site". What do you think @ryanwoldatwork ?

**Comment by ryanwoldatwork** [comment]
@hatfieldjm4 - Websites now display their "Event Log" which show changes in status. That might help convey changes to sites, but likely wouldn't satisfy the requirement above.

I'm not sure what the appropriate status or state transition is for these no-longer-public-facing web properties, but happy to chat.

**Comment by AKM399** [comment]
awaiting meeting with @ryanwoldatwork.

**Comment by ryanwoldatwork** [comment]
@AKM399 - if a site is no longer public facing, is there a requirement to inventory it?

**Comment by RachelF** [comment]
@AKM399 I don't think we need to track these in TP; recommend closing this

**Comment by AKM399** [comment]
leaving open for further meetings.

**Comment by AKM399** [comment]
closed per reccomendation.
