### ISSUE TITLE
Websites required by name in policy

### ISSUE THREAD

**Issue by mvogelgesang** [GSA/EDX#398]
## Summary

A number of domains are called out by name in OMB policy, legislation, or other memoranda. Review our list of sites for ones that meet said requirement. Goal is to spur a discussion about the time and resources used by these sites and identify any potential ways to reduce organizational impact.

## Policy/ Law Examples

code.gov (OMB [m-16-21 page 7](https://www.whitehouse.gov/wp-content/uploads/legacy_drupal_files/omb/memoranda/2016/m_16_21.pdf)
> Make Custom-Developed Code Available: Agencies shall make custom-developed code
available for Government-wide reuse and make their code inventories discoverable at
https://www.code.gov (“Code.gov”), pursuant to the limited exceptions outlined in
Section 6 of this policy.

## Examples of sites mention in policy but not a named requirement

usa.gov ([EGovt Act of 2002](https://www.congress.gov/107/plaws/publ347/PLAW-107publ347.pdf))
* Does not call out usa.gov by name. Clearly outlines the goals for usa.gov but does not require such a site to be called usa.gov.

search.digital.gov (OMB [m-17-06](https://www.whitehouse.gov/wp-content/uploads/legacy_drupal_files/omb/memoranda/2017/m-17-06.pdf))
> Agencies’ public websites must contain a search function that allows users to easily search
content intended for public use. GSA maintains a search solution that meets this requirement
and that is available to all agencies at http://search.digitalgov.gov.

## Sites we are aware of

* code.gov

## Checklist

List below the specific actions to be taken

- [ ] sizing sites named by EO or other forms of policy - how many

**Comment by AKM399** [comment]
seperate from sites unfunded from OMB such as the cloud.gov site etc @mvogelgesang need card on it

**Comment by AKM399** [comment]
we need a general kill list? @anatecture

**Comment by mvogelgesang** [comment]
updated with a couple of examples. By my brief review, many laws/ policies state something to the effect of "{agency} shall make available/ collect information regarding law/ policy XYZ" but do not explicitly mention the name of a website. Still more to review

**Comment by mvogelgesang** [comment]
@anatecture @RachelF @AKM399 Reviewing the list from our data call further, I don't think sites are called out by name very often. Instead, I think the second use case we discussed; sites requested or handed over to GSA, are more common. I think we begin to look at sites like that as opportunities for consolidation and savings.

**Comment by AKM399** [comment]
take it from a policy perspective

**Comment by AKM399** [comment]
find is that the service is frequently required but not the website.  Closing a site or domain should not be an issue.

**Comment by djharrity** [comment]
Some examples of direct/indirect references to website or database:

40 U.S. Code § 3318: Availability of Federal building project information 
41 U.S. Code § 2313 - Database for Federal agency contract and grant officers and suspension and debarment officials -- re: database - see (a), (d), (e)
E.O. 14005  § 6, [Executive Order on Ensuring the Future Is Made in All of America by All of America’s Workers](https://www.whitehouse.gov/briefing-room/presidential-actions/2021/01/25/executive-order-on-ensuring-the-future-is-made-in-all-of-america-by-all-of-americas-workers/ )
