### ISSUE TITLE
Sites missing managers

### ISSUE THREAD

**Issue by AKM399** [GSA/EDX#400]
I want to find managers for unassigned or incorrectly assigned websites so that the touchpoints inventory can be improved and future communications/evaluations can happen

**To Do**
- [x] FInd bandwidth in website evaluation project sprint schedule
- [x] Size the issue - get a lst of sites
- [x] chase them down
- [ ] implement the change

**Comment by mvogelgesang** [comment]
this is being addressed by the Website Manager PD work conducted by @monicas-d and @gailsprinkle #443

**Comment by monicas-d** [comment]
Yes - we (@gailsprinkle and I) plan to "chase them down" on Friday if 28% are not fully identified by then. Thanks!

**Comment by monicas-d** [comment]
@RachelF @gailsprinkle @mvogelgesang - want to update stuff here? I know we had a lot of back and forth emails... :( THanks!

**Comment by RachelF** [comment]
I think we can close this; you've chased them down @monicas-d and @gailsprinkle  and I've updated touchpoints with the most current list of names
