### ISSUE TITLE
Web Maturity Indicator - Anchor Links and ToC

### ISSUE THREAD

**Issue by mvogelgesang** [GSA/EDX#404]
## Summary

Many of our sites are content heavy and could benefit from using well structured HTML to enhance searchability when using Google, Bing, etc. For example, we could look for proper anchor tags, the presence of JSON-LD, etc.

USWDS uses https://github.com/bryanbraun/anchorjs to implement the anchors.

https://www.sebkln.de/en/tutorials/seo-jump-links/ speaks to the importance of anchors.

## Additional context and links

The idea for this came about when searching for the Touchpoints API documentation in Google. The right site was identified as a top link but the destination URL required more scrolling to get to the result I wanted. This has been raised with the open.gsa.gov team in https://github.com/GSA/open-gsa-redesign/issues/513

## Checklist

List below the specific actions to be taken

- [ ] item 1
- [ ] item 2

**Comment by AKM399** [comment]
how to make it a generalized practices teams can follow without handholding.

**Comment by AKM399** [comment]
part of the GSA content strategy.  touched upon with Ryan Johnson.  Possible discussion with OSC who is looking at an Enterprise content strategy.

**Comment by AKM399** [comment]
@anatecture out of scope or partner with OSC?

**Comment by anatecture** [comment]
Out of scope. thanks @AKM399
