### ISSUE TITLE
OMB orphan sites

### ISSUE THREAD

**Issue by RachelF** [GSA/EDX#410]
## Summary

GSA is often tasked by OMB to stand up a new website for certain initiatives or policies.
Unfortunately, OMB is not great at maintaining these sites over time, so GSA is left with a lot of sites that were commissioned by OMB, but are no longer supported.

We need a way to communicate with OMB about cleaning up/closing/consolidating these sites, and take them down, or resource them.

[Analysis of MY sites](https://docs.google.com/document/d/1BL0m4FIsG1EgAtxnfNtOAbnq_HaZR9bm_7DTrc0SLmE/edit#heading=h.1nvioducx0jp)

## Checklist

- [x] Identify which websites fit this category (e.g., some *.data.gov and *.cio.gov sites)
- [x] Meet with OGP/MY to discuss
- [x] Determine which sites are actually under GSA control versus those which occupy domain name space (OGP is simply the "putter upper" and has no control over content) 
- [x] Update inventory to recategorize OMB sites as "external" brand category
- [x] Determine with OGP whether/how to raise this issue w/OMB
- [x] Communicate with OMB about this (email from Earl)
- [x] Advise OGP to remove GSA branding from "external" sites 

### GSA Control

|URL| Github Repo|
|---|------------|
|[federation.data.gov](https://federation.data.gov)|[github.com/GSA/us-data-federation](https://github.com/GSA/us-data-federation)|

### OMB Manages Repository

|URL| Github Repo|
|---|------------|
|[management.cio.gov/](https://management.cio.gov/)|[github.com/WhiteHouse/CIOmanagement](https://github.com/WhiteHouse/CIOmanagement)|
|[software.cio.gov](https://software.cio.gov/)|[github.com/WhiteHouse/software-policy](https://github.com/WhiteHouse/software-policy)|

**Comment by mvogelgesang** [comment]
@RachelF I started added a couple of sites which I am aware of and split them into two categories

**Comment by AKM399** [comment]
#398

**Comment by RachelF** [comment]
EDX met with Earl Pinto, Dana Fowler, Alycia Yozzi, Kelly Cox from MY on 6/15 to discuss MY sites, particularly in relation to OHRM request to identify web managers. Good discussion, will continue working w/MY to improve categorization of sites, and work toward a proposal we can make to OMB to improve long-term management of these sites.

**Comment by anatecture** [comment]
Breakdown of sites from OMB and what we're doing with them [OGP/MY Website Inventory Updates - August 2022](https://docs.google.com/document/d/1gFyxT30_zvMFVUe8gHqu9GEUKYdAEoCPonbzFRfFlcA/edit#heading=h.qkxko1y5ktca)

**Comment by RachelF** [comment]
Updated touchpoints to change designation for several OGP sites to "external" and denote management lead is OMB.

**Comment by RachelF** [comment]
OGP will remove GSA branding from all "external" sites once they notify OMB, and work into their backlog.
