### ISSUE TITLE
PIPs for websites

### ISSUE THREAD

**Issue by anatecture** [GSA/EDX#414]
**Summary**

- Develop PIPs for websites if they're struggling. Came from 18f struggles with supporting all their websites. 
- Would require collaboration from OHRM.

**Comment by AKM399** [comment]
consultation needed from @gailsprinkle and @monicas-d

**Comment by anatecture** [comment]
this seems like it needs more thought than a fall project.

**Comment by anatecture** [comment]
Pulling @monicas-d's email into this shared platform: 
`As mentioned to the team, I think it might be helpful if we liaised and brought Mike Seymour into this - not of establishing official PIPs but rather, learning best practices.`

`Thoughts [@Gail Sprinkle - CSC](mailto:gail.sprinkle@gsa.gov) . Agreed with [@Ana Monroe Fitzner - O](mailto:ana.monroe@gsa.gov) that this is a big project and at least from me and Gail's standpoint, something we cannot prioritize any time soon given the PD work is a lot bigger than we initially thought.`

Totally agree that the project is massive, so that's why it's tagged with the Potential New Project label. We're thinking this might be a CY 23 project, if we take it on at all.

**Comment by anatecture** [comment]
Good idea; not feasible.
