### ISSUE TITLE
Launch revamped CX Awards program

### ISSUE THREAD

**Issue by RachelF** [GSA/EDX#424]
## Summary

Redesign and launch a reimagined GSA CX Awards program.

## Additional context and links

[CX Award Operations Guide for OCE](https://docs.google.com/document/d/1DRWfO99keRL3qcZWnr5XwY12sNArkaaOTonRR9G82eg/edit#)

## Checklist

List below the specific actions to be taken

- [x] Redesign the program
- [x] Document new processes
- [x] Design new logo and certificate
- [x] Present to Ed and gain his approval to proceed
- [x] Update guidance for GSA employees
- [x] Develop comms plan, marketing emails
- [x] Update InSite
- [x] Schedule a briefing for Robin
- [x] Conduct Robin briefing and gain her approval on our plan
- [x] Announce to GSA
- [x] Collect nominations
- [x] Recruit Chiefs of Staff to help review/validate nominations
- [x] Review and select finalists
- [x] Submit finalists to Exec Panel for review
- [x] Announce first winners on CX Day 10/4/22
- [x] Send certs to winners

**Comment by RachelF** [comment]
Nominations close today; almost 30 nominations received. Mark, Patricia and Rachel will review and make the first cut by this Friday 8/5

**Comment by RachelF** [comment]
@mvogelgesang Hi, have the certs gone out yet? If so, we can close this.

**Comment by mvogelgesang** [comment]
@RachelF Not yet, still working through the CDT process
