### ISSUE TITLE
Pull in Google Search Console results

### ISSUE THREAD

**Issue by mvogelgesang** [GSA/EDX#425]
## Summary

Currently, a handful of GSA sites leverage Google Search Console which provides insights into top keywords, most viewed pages, and performance issues. Pulling this data programmatically could be a nice supplement to the existing Web Evals.

## Checklist

List below the specific actions to be taken

- [ ] Do we raise this with Digital Council and make it a website requirement?
- [ ] Review and prototype https://github.com/googleapis/google-api-nodejs-client

## 2022-07-20 Update

- Coordination with Google Cloud team will be required to establish appropriate service accounts. Some preliminary steps:
  - enable the search console api
  - Install gcloud SDK, https://cloud.google.com/sdk/docs/install-sdk
  - Complete login/ auth
  - https://googleapis.dev/nodejs/googleapis/latest/searchconsole/index.html#using-api-keys

**Comment by AKM399** [comment]
maybe for year 2 website evals?

**Comment by AKM399** [comment]
@mvogelgesang do we have the bandwidth?  already adding  search results.  We have 1 week to refine and tweak between sprints.  can you fit it?

**Comment by anatecture** [comment]
Not pursuing
