### ISSUE TITLE
Scanner > Condenser > Airtable

### ISSUE THREAD

**Issue by mvogelgesang** [GSA/EDX#431]
## Summary

The Condense operation in Scanner takes a set of Scan outputs and turns them into a CSV file. Take that CSV file and push to Airtable
## Additional context and links

Add any other context, screenshots, or links to working docs.

## Checklist

List below the specific actions to be taken

- [ ] item 1
- [ ] item 2

**Comment by AKM399** [comment]
@hursey013 old cli issue, can it be closed?

**Comment by anatecture** [comment]
this is OBE w/ GEAR
