### ISSUE TITLE
Redirect policy for DC-->EB

### ISSUE THREAD

**Issue by anatecture** [GSA/EDX#434]
@mvogelgesang @AKM399 write bullet points for a redirect policy to present to the DC. @anatecture can write the intro/outro. 

@mvogelgesang presents. 

Due 06/14

[Working Doc](https://docs.google.com/document/d/1UJqHMzkHITHdyHD3zqG0dYhx00ZeufCnJB0CnuEzkpM/edit)

**Comment by mvogelgesang** [comment]
@AKM399 I have posted a working doc

**Comment by AKM399** [comment]
@mvogelgesang to link to guidance

**Comment by mvogelgesang** [comment]
#660 >> make this a recommendation to teams implementing redirects
