### ISSUE TITLE
Website Manager Identification Meetings / Emails

### ISSUE THREAD

**Issue by monicas-d** [GSA/EDX#442]
@gailsprinkle and I worked from April 13-June 16 meeting with Touchpoints' POCs to determine who their public-facing digital properties' website managers are according to the EDX set criteria below:

We define a website manager as:

This person must be a Federal employee and not a contractor 

The one who directs the work with the program, GSA-IT, etc. 

This Fed should be responsible and accountable for this website and can answer questions such as:

- The state of the site's 508 compliance
- The plan to adopt USWDS
- What your customers are asking for
- What your survey goals are

We captured those names in this spreadsheet: https://docs.google.com/spreadsheets/d/1Cczm6X_1KYOaq9AxcSjKkrhW4oiuQiPWob68PeQEKuU/edit#gid=183079397

Specific actions to be taken next

- [x] Follow up with POCs that have not identified the website manager for their properties. That list is being captured in tab called "Unidentified-SiteMgr-6-8-2022" in the linked spreadsheet above; we hope to get all the website managers names captured by the end of June
- [x] Gail is capturing those names in the most updated version of the BU Status Supervisor Email spreadsheet (@gailsprinkle please link here)
- [x] We will send an email to supervisors of those people who self identified to confirm they are in fact the correct website manager in our draft email here (https://docs.google.com/document/d/1U6QUjBQY7_VQwxFWVWAMdcwdmv5GFXg2XmNrjPTSmbc/edit) (Spreadsheet capturing that info here: https://docs.google.com/spreadsheets/d/1t1SpUnWL5PggaRsMgOy_eis_S77S1C3pMOgkfI__O3w/edit#gid=0)
- [x] NOTE: Sarah Bryant and Stephanie Joseph are reviewing that draft email to supervisors, along with Charlotte Watson and Manuela Martinez (Classification) to provide us with edits before we send out
- [x] Once the email is sent out, we are asking for confirmation by COB 6/24

Monica will start a second issue and link it with this one regarding website manager position description work

**Comment by monicas-d** [comment]
Gail and Monica spoke with Charlotte, Manuela, and Manuela's supervisor, Reonna Shannon, this week and they believe that for any PDs that are only "other duties as assigned" we will need to reassign website managers to new PDs; there should be no change to grade (with caveat below???) @gailsprinkle can you please share here if it will impact series, title, or position? I think they said it could/may but not grade/pay...Thanks! ...I pulled our language from the draft email to supervisors below, which doesn't align with what I heard from Reonna this morning...

The HR Classification experts do not expect the additional language to impact position titles, series, or grades, unless 1) the website manager is on a PD with other employees who have no website management responsibilities;  2) if website management duties are determined to be of greatest importance but are not clearly defined in the PD (i.e., listed as “other duties as assigned”); or 3) the PD is outdated and requires a new PD which accurately captures the assigned major duties. In the event of these anomalies, a new PD would be created.

**Comment by monicas-d** [comment]
Linking this issue with #443

**Comment by monicas-d** [comment]
See "Unidentified Site Managers 6-8-2022" tab for updates: https://docs.google.com/spreadsheets/d/1Cczm6X_1KYOaq9AxcSjKkrhW4oiuQiPWob68PeQEKuU/edit#gid=1321778304

**Comment by AKM399** [comment]
overcome by events
