### ISSUE TITLE
Website Manager Position Description Work

### ISSUE THREAD

**Issue by monicas-d** [GSA/EDX#443]
In collaboration with the GSA Digital Council, the Enterprise Digital Experience (EDX) Team in OCE is working to identify employees who are responsible for the proper functioning of GSA’s public-facing websites and digital properties, and are accountable for the programmatic direction of those properties. The team interviewed the point(s) of contact listed in GSA’s Touchpoints website inventory to identify the website manager for each property. See Issue #442   
 
A GSA Website Manager:

- Must be a Federal employee and not a contractor, but may direct and oversee contractors
- Must direct the work with the program, GSA-IT, etc.

Should be responsible and accountable for the website and can provide information about the site such as:

- The state of the site's 508 compliance
- The plan to adopt the U.S. Web Design System (USWDS)
- The customer feedback mechanisms (i.e. surveys, other) used on the site
- What the site’s customers are asking for
 
These responsibilities are frequently classified in Position Descriptions (PDs) as “other duties as assigned,” or simply absent, and building a definitive roster of these employees in GSA (and the federal government) has never been attempted. In collaboration with OHRM Classification experts, the team is exploring options to include website management functions in the incumbents' PDs. This will ensure website managers get the credit they deserve for the work they do around GSA’s public facing websites, and it ensures an accurate PD for the employee. It will also help to formalize governance and improve management of our websites and digital services.

The HR Classification experts do not expect the additional language to impact position titles, series, or grades, unless 1) the website manager is on a PD with other employees who have no website management responsibilities; 2) if website management duties are determined to be of greatest importance but are not clearly defined in the PD (i.e., listed as “other duties as assigned”); or 3) the PD is outdated and requires a new PD which accurately captures the assigned major duties. In the event of these anomalies, a new PD would be created.

Specific actions to be taken:

- [x] Monica and Gail have been working with Charlotte Watson and Manuela Martinez about this since Fall 2021.
- [x] Monica and Gail brought Manuela's supervisor, Reonna Shannon, into the conversation on 6/9/22 as TTS Talent Managers called her concerned about it (Monica/Gail spoke with Star Vanamali in detail about this project yesterday, and Star advised TTS Talent Management)
- [x] Monica and Gail will speak with Audrey Peel, HR Services Director in OHRM to discuss involvement of Classification staff reviewing identified website manager PDs as a big project for the remainder of FY22 (and into Q1 of FY23/December) on June 21 at 11 am ET
- [x] We will meet with supervisors of classifiers on Jun 29
- [x] We will then meet with the classifiers in the Classification Community of Practice July 12
- [x] Cheryl Cato will email classification to share in writing information about our project (TBD)

@gailsprinkle What did I miss here? Thanks!

**Comment by monicas-d** [comment]
https://docs.google.com/document/d/1lVbfpYM7h_36H42zQCb2ehmv-za_2RgKEtAUrDgH3VY/edit

Next Steps according to Gail, Monica, and Cheryl Cato - this is draft and work-in-progress

**Comment by monicas-d** [comment]
@gailsprinkle Let's revisit the above doc on classification - process in tomorrow's 1:1. Thanks!

**Comment by monicas-d** [comment]
DRAFT language that should be included in ALL website manager PDs: _The incumbent serves as a website manager who is programmatically responsible and accountable for the proper functioning of a GSA public-facing digital property, as required by the Digital Lifecycle Program_.

Questions: 1-does this language incapsulate compliance and customer experience through the phrase "proper functioning"? Anything else from our definition need to be included here? 2-do we need to include language about them being a government employee and not a contractor? 3-is mention of the DLP too specific for a PD?

@gailsprinkle @mvogelgesang @anatecture @gailsprinkle @hatfieldjm4 @AKM399 

Link to #548

**Comment by anatecture** [comment]
@monicas-d great questions. Here are some answers from @gailsprinkle and I: 

1. We think this encapsulates compliance and CX perfectly through the phrase "proper functioning". 
2. We don't think language calling out gov employee versus contractor is necessary because contractors won't have a PD and contractors aren't allowed to control a gov property. 
3. Slight edit to the final sentence in regards to DLP reference. We suggest:  "_...responsible and accountable for the proper functioning of a GSA public-facing digital property, as required by GSA policy, federal policy, and law_."

**Comment by monicas-d** [comment]
Per our conversation today - please correct me / and @gailsprinkle if we're wrong, we are changing this language to "The incumbent serves as a **digital property manager** who is programmatically responsible and accountable for the proper functioning of a GSA public-facing digital property, as required by GSA policy, federal policy, and law." 

Thus changing from website manager to digital property manager. 

Wouldn't we want to define what that means in parentheses? ex: digital property manager (to include websites, applications, log-ins, etc.)?

cross referencing comment from @anatecture "I like both that phrasing and the parenthetical definitions"

**Comment by AKM399** [comment]
to be updated with notes from crit https://docs.google.com/document/d/1TC_X1w1j-faBFc_GRQ_5cixpVfW5tZOrPvapEOr3rzk/edit?usp=sharing

**Comment by AKM399** [comment]
per gail:  Incumbent serves as a website manager and is programmatically responsible and accountable for the proper functioning of GSA digital properties by collaborating with other teams to ensure compliance with GSA policy and Federal regulations, resulting in a successful customer experience.

**Comment by AKM399** [comment]
@gailsprinkle can we close this ticket down?

**Comment by AKM399** [comment]
work complete, verified with @gailsprinkle

**Comment by AKM399** [comment]
#631
