### ISSUE TITLE
Current websites that could be replaced with a widget

### ISSUE THREAD

**Issue by mvogelgesang** [GSA/EDX#450]
## Summary

As we look through more and more sites, it seems that a number of distinct websites were established due to technical limitations that existed at the time of development. Today though, functionality can be replicated via simple widgets. 

Rather than teams investigating how to redesign the current site, what are the pathways for teams to instead build widgets (something like a web component) and incorporate those features on a new site?

## Additional context and links

Example site being https://cpsearch.fas.gsa.gov/cpsearch/search.do

## Checklist

List below the specific actions to be taken

- [ ] Are there SEO or other challenges that may be presented by moving in this direction? For instance, can you get results in a search engine today if you say "City Pairs ATL to DCA"? If not, should that feature exist?
- [ ] is there the desire to make the widget available more broadly to agencies? Dept of Defense has a large travel site which links to City Pairs, would there be value in providing them the widget for placement on their site?

**Comment by AKM399** [comment]
too many roadblocks to implementation
