### ISSUE TITLE
18F Guidance and Content sites 

### ISSUE THREAD

**Issue by anatecture** [GSA/EDX#459]
## Summary

18F controls a variety of sites for whom neither customers nor managers are validated. At our current count (June 2019) these sites are: 

1. 18F Accessibility Guide
2. 18F Agile Guide
3. 18F Brand / Visual Identity
4. 18F Content Guide
5. 18F Derisking Guide
6. TTS Engineering Practices Guide
7. 18F Engineering Hiring Guide
8. 18F Methods
9. 18F Product Guide
10. 18F UX Guide
11. 18F chat sign up (google form)

Although the sites are presumed to be of value to customers, no customer has been identified aside from TTS itself. 

## What we've done so far

We've worked with Anne Petersen and others to talk through this issue, but unfortunately have not found any common path towards satisfying both supporting and evolving 18F's digital assets as well as meeting the standards of GSA's website management. 

We first met with Anne Petersen and Julie Strotham back on February 1 to talk about this and were asked if we could give them some weeks to reach out to customers and figure out a product ownership strategy for the wide family of sites. We did so, scheduling a workshop for May 19th to consider the 10 sites as a unique, 18F product vertical. On May 16th, we received 18F's 44 page qualitative research report on TTS's (no outside customers were reached) use of the sites and redesigned our workshop with this report taken into consideration. 

[You can see the figma from that workshop](https://www.figma.com/file/FlSwhcDhEZk07wLWmPDsSZ/18f-Workshop), where we jotted pros and cons of different management paradigms for 18F's sites and tied challenges from the report to levels of effort. Although we didn't expect the workshop to produce "a solution", we were surprised and somewhat challenged by the lack of engagement with the core issues at hand. While some folks on the team clearly took away thoughts and ideas on how to better manage 18F's sites, some folks seemed to consider the workshop as the subject of critique in itself, instead of as part of a larger, more strategic conversation about the future of 18F's digital assets. 

Which brings us to this conversation. [While we remain convinced of the general value of 18F's guidance writing](https://docs.google.com/presentation/d/1t4lHQ7BZ_WlO7h7f8_JHqXc4O8UC2iRVKwCr-NDD5_E/edit#slide=id.g119c4f38999_0_0), we have to develop a realistic, explicit plan to manage and measure the value those sites are providing to GSA and to the federal space. Our goal here is to evolve 18F's digital asset management practice while respecting its collaborators and at the same time attaining agency, federal, and 18F's own high standards.

**Comment by anatecture** [comment]
Tomorrow, 06/17, @AKM399 and I will meet w/ acting director and acting deputy director of 18F for 30 minutes. Here's what I'd like to go over: 

### Problem
Our problem is not that 18F has all these sites; it's that the org is clearly struggling, by its own admission in its report on itself, to manage them properly. This pertains to content and technical patches. 

**Identifying website manager(s)**
As part of the Enterprise Digital Experience work, we're identifying website managers for each GSA digital property. The reasons we're doing this are: 

1. **Equity:** currently the people doing this work are uncredited for website management work. Uncredited and/or unpaid labor is a core equity issue, so we want to correct this issue. 

2. **Public Trust:** The public is entitled to hold the government responsible for the management of assets funded with taxpayer dollars. To create this transparency and accountability, we must identify website manager(s) for digital assets and ensure that those assets are providing value to the public.

3. **Compliance:** As an organization, GSA needs to be compliant with the 21st Century IDEA, OMB Circular A-11 Section 280 on Customer Experience, and other policies. In order to provide excellent digital customer experience, we must know the customer(s) for our digital offerings so that we can understand those customer(s) needs. 

For this first year of review, the bar for defining customers for GSA websites is low: do you serve other agencies, the public, GSA itself, or a combination? Building on that, what customer feedback mechanism do you use to ensure that your service is meeting the needs of your identified audience. 

Currently, 18F can only answer that some of its sites are used by TTS, and provide some ad hoc stories of appreciation from public users, but there is no recurrent, replicable, external feedback mechanism in place to validate the usage of the public.  


### Our Proposals
**Alleviating technical burden:** 
Keeping redirects in place so links don't break, we'd like to see the 18F sites combined into a single site named something like guides.18f.gov/name-of-guide. This would alleviate some of the rote technical work of pushing patches and updates to different sites, so that 18F staff can concentrate on the higher value work of content creation and maintenance. 

---more----





Following the model of https://playbooks.idmanagement.gov/,

**Comment by monicas-d** [comment]
@gailsprinkle I loved Ana's framing of the conversation with 18F. Very well done, Ana! 

@RachelF I'd like us to look at this framing for future comms moving forward. Let's discuss in a meeting just for EDX comms please among you, me, Gail, and Ana if she has some time. Thanks!

**Comment by AKM399** [comment]
comments via email from Ana to Lauren:

only addition that I see after a review of the [GSA Website Inventory](https://touchpoints.app.cloud.gov/admin/websites) is [chat.18f.gov](http://chat.18f.gov/), which is google form. I know that TTS wants public folks to be able to sign up for the community channels on slack, but a google form isn't allowed as a public facing website, so that flow will need to be changed. I'll add it to [the issue.](https://github.com/GSA/EDX/issues/459) 

In answer to the question that I think might be part of your question, we sorted the GSA Website Inventory alphabetically by second- or third-level (for sites called [some-name.gsa.gov](http://some-name.gsa.gov/)) domain name. This means that all 18F sites came under review in this round, but not all TTS sites, which of course come at different points in the alphabet according to their second level domain name. If you'd like a review of TTS sites specifically, we can work together to scope that. It would depend on the depth of the review, but we could definitely put something together, esp if we can pull in some other TTS-ers to aid in the work. 

Understand that LBS doesn't need to be in the meetings. I'll get some meets up for 

-[ ] Friday, August 12th
-[ ] Friday, October 7th
-[ ] Friday, December 2nd

**Comment by mvogelgesang** [comment]
#546 

Broader notes about the guides 🔒 https://docs.google.com/document/d/1MFFbXu7XP69aSo41cW7iMGZ6ApnnnJP_vA3eLk9kpdA/edit

**Comment by AKM399** [comment]
11/02 Meeting with Claire Annon to discuss google analytics - specifically location reports.

**Comment by AKM399** [comment]
@anatecture thoughts on where we go from here?

**Comment by AKM399** [comment]
@anatecture Reach out to Joe and see if work will be  funded

**Comment by AKM399** [comment]
in progress.  Included as direct recommendation in [FAS compilation deck]([https://docs.google.com/document/d/1L8_0Xeo9zUxFbket_Lf5muw0PmOnC0X5NePqyOXrX1Q/edit?hl=en&forcehl=1#](https://docs.google.com/document/d/1L8_0Xeo9zUxFbket_Lf5muw0PmOnC0X5NePqyOXrX1Q/edit?hl=en&forcehl=1))

**Comment by AKM399** [comment]
meeting with charlotte on the 28th

**Comment by AKM399** [comment]
awaiting conversation with Star

**Comment by AKM399** [comment]
open question, have they finished?

**Comment by AKM399** [comment]
closing because they are following actions.
