### ISSUE TITLE
Check-ins w/Board members

### ISSUE THREAD

**Issue by RachelF** [GSA/EDX#463]
## Summary
One-on-one check-ins with Exec Board members to get feedback on the Council and Board, their experience, program representation, ideas for how we can improve communication and outcomes.

## Checklist
List below the specific actions to be taken

- [x] Schedule 20-min mtg with Dan Pomeroy to launch
- [x] Hold meeting w/Dan
- [x] Incorporate Dan's feedback
- [x] Schedule 30-min meeting with Allison A
- [x] Schedule meeting with David S
- [x] Schedule meeting with Channing G
- [x] Schedule meeting with Katy K
- [x] Schedule meeting with Charlotte P
- [x] Schedule meeting with Camille
- [x] Meet w/Dan
- [x] Meet w/Allison
- [x] Meet w/Camille
- [x] Meet w/David
- [x] Meet w/Channing
- [x] Meet w/Charlotte
- [x] Meet w/Katy
- [x] Synthesize findings
- [x] Share with DC to determine next steps

**Comment by RachelF** [comment]
Alison was a no-show; need to reschedule

**Comment by RachelF** [comment]
Alison meeting has been rescheduled twice; now scheduled for 8/31

**Comment by RachelF** [comment]
Dan - complete 6/24
Alison - complete 8/31
Camille - complete 10/25
Notes https://docs.google.com/document/d/1E7MazVaANJs-LMP5zz4K91zdt506Z3mA2z6lhfoQJ50/edit#heading=h.blurxtvcnr0h

**Comment by AKM399** [comment]
@RachelF Closable?

**Comment by monicas-d** [comment]
We finished Katy's meeting, and now need to analyze data/set up a briefing
to share back. Please do not close yet as we need to do the briefing first.
Thanks!


-- 

U.S. General Services Administration

*Monica Suber-Duffy*, Federal Internal Coach
<https://insite.gsa.gov/topics/training-and-development/developmental-services/coaching-services>

Organizational Development Consultant
<https://insite.gsa.gov/topics/training-and-development/developmental-services/organizational-development>

GSA  | OHRM Talent Development

Pronouns: She/Her/Hers

Office of Human Resources Management (OHRM)

1800 F St, NW

Washington, DC 20526

Mobile: (202) 701-8197

E-mail: ***@***.***

Join the Yoga & Mindfulness Chatter Group
<https://gsa.my.salesforce.com/_ui/core/chatter/groups/GroupProfilePage?g=0F9t0000000aU0i>,
and see our page on InSite
<https://insite.gsa.gov/topics/training-and-development/continuous-learning/yoga-mindfulness>

Between stimulus and response there is a space. In that space is our power
to choose our response. In that response lies our growth and our
freedom.-Viktor
E. Frankl

<https://insite.gsa.gov/topics/hr-pay-and-leave>

**Comment by AKM399** [comment]
report including slide deck is in share drive

**Comment by RachelF** [comment]
We've not yet briefed the Board on our findings, reopening

**Comment by monicas-d** [comment]
Friendly reminder: We need to take into consideration their recommendations for the future state of the Executive Board.
