### ISSUE TITLE
Project - How might we continually assess digital maturity over time and express it

### ISSUE THREAD

**Issue by mvogelgesang** [GSA/EDX#476]
## Summary

In FY22, we began the process of assessing websites using quantitative attributes which were informed by our Scanner. Accessibility data was layered in from GSA's accessibility testing tool, AMP. In addition, we started interviewing each website team to better understand how they organize their work, solicit and consume feedback, the last time they upgraded the site, and USWDS implementation. This allowed us to start representing websites via shapes (example below). While this is a helpful representation to look at a handful of websites, we need a means to represent the whole of GSA's web presence.

![image](https://user-images.githubusercontent.com/4053083/175033909-41c03dd1-2480-46d2-950d-32195b814de6.png)

Early sketches of how an overall view might work used scatter plot diagrams that could represent the overall shift from quarter to quarter.

![image](https://user-images.githubusercontent.com/4053083/175033814-1640f385-7462-4354-b5b0-e0eb60a14d6c.png)

## Additional context and links

Websites and web applications have a lifecycle that must be accounted for in this model. For example, a website that is developed today _should_ utilize a recent and actively maintained application stack. In an ideal case, that application stack can be upgraded over time to stay current with patch and minor version upgrades (0.0.x and 0.x.0 in [SemVer](https://semver.org/) parlance). Major versions (x.0.0) are likely to require a substantial cost and may be at the discretion of the IT and business offices whether or not to upgrade. 

As a result, a website built 5 years ago may be unable to meet criteria that is currently considered best practice (speaking broadly to include accessibility, mobile friendliness, security, performance, etc). A certain tolerance level must be established to determine at which point a website relying on legacy application stacks must be upgraded. This may also be informed by the underlying web application and its maintenance schedule.

```mermaid
gantt
    todayMarker on
    title Lifespan of Drupal Versions
    dateFormat  YYYY-MM-DD
    section Drupal 6
    Initial Release           :milestone, a1, 2008-02-13, 0d
    D6 Lifespan.              :after a1, 2933d
    End of Life               :milestone, a3, 2016-02-24, 0d
    section Drupal 7
    Initial Release           :milestone, b1, 2011-01-05, 0d
    D7 Lifespan.              :after b1, 4683d
    End of Life               :milestone, b3, 2023-11-01, 0d
    section Drupal 8
    Initial Release           :milestone, c1, 2015-11-19, 1d
    D8 Lifespan               :after c1, 2190d
    End of Life               :milestone, c2, 2021-11-17, 1d
    section Drupal 9
    Initial Release           :milestone, d1, 2020-06-03, 0d
    D9 Lifespan               :after d1, 2000d
```

## Checklist

List below the specific actions to be taken

- [ ] Investigate and determine a means by which we can visualize the health/ maturity of websites over time. 
  - https://observablehq.com/@d3/contours && https://github.com/d3/d3-contour
  - https://observablehq.com/@mbostock/inequality-in-american-cities
- [ ] Expressing the information is one thing, gathering insights and adjusting course is another. What kind of insights could be provided as this data grows over time? What data points are needed to make it meaningful?
  - Could it help drive stronger technical support for websites utilizing the same application framework? 
  - What are the characteristics of sites which maintain high index scores over time?
  - Are there websites whose index scores fall faster than expected?
  - Do we consider end of life dates for an application stack as a metric when evaluating sites?

**Comment by mvogelgesang** [comment]
Conversation with @AKM399 could we infer which sites are aging/ decreasing in age faster than others. What is it about those sites which could be a cause?

**Comment by AKM399** [comment]
@AKM399 to look up clustering scheme that could help infer this data point.

**Comment by mvogelgesang** [comment]
Figma from EDX Crit: https://www.figma.com/file/ptqL6gVgqlRpSMv5QxZ0WC/Websites-over-time

**Comment by AKM399** [comment]
data narratives
