### ISSUE TITLE
DC - proposed PBS site

### ISSUE THREAD

**Issue by anatecture** [GSA/EDX#478]
## Meeting 1 w/ PBS team

**Problem:** want to show properties for rent via a map (think: zillow) 

- Region 8's already got a GIS tool built 
- recommend that they look closer at the existing platform
- if turns out existing is not feasible, we can put together a business case for them (DLP proposal phase) 
- they're doing research internally and found some things that work, as well as some existing capabilities that they would need to add data to it 
- gave them the DLP assets, focusing on the Proposal phase, for them to reference

**Comment by RachelF** [comment]
[Meeting notes](https://docs.google.com/document/d/1nqvVWlogWs4QMYgaVv9aj6q8Xpr1UrEpNCKYRT5ptPo/edit)
Also shared [DLP Overview](https://docs.google.com/document/d/1FcqhtB0PNvYE-rM5iYcR8Bu2G7Gfmupb2wo5nSCwO0c/edit#) with the team

**Comment by mvogelgesang** [comment]
GIS seems like overkill if they just want to plot points on a map. Open source tools like Leaflet may be a lighterweight choice. The map would need to be enclosed in another site- just having a map feels underwhelming.

**Comment by AKM399** [comment]
+1 mark, i used to run an enterprise license for google maps for EPA.  They're cheap, they're way easier.  A lot more sustainable if you're not doing actual GIS related sciences.

**Comment by RachelF** [comment]
Sent a followup email asking for a status

**Comment by AKM399** [comment]
service delivery team is continuing work
