### ISSUE TITLE
Project - Website Management Anti-Patterns

### ISSUE THREAD

**Issue by mvogelgesang** [GSA/EDX#481]
## Summary

In our conversations with various teams, we have uncovered a number of website management practices which produce situations where folks from the business unit and their IT counterparts lack clear definition with roles and responsibilities. This rears its head when implementation of USWDS is discussed and both the business and IT counterparts point at the other as the one responsibile for writing the requirement. In other cases, the business side feels that USWDS is an IT initiative and IT must bear the cost. In others, the actual prioritization of work occurs by an IT lead with the business at arms length from the work.

Goal of this project will be to identify common anti-patterns and provide recommended solutions to them. 

## Additional context and links

Add any other context, screenshots, or links to working docs.

## Checklist

List below the specific actions to be taken

- [ ] item 1
- [ ] item 2

**Comment by AKM399** [comment]
reference mike bloom conversation

**Comment by AKM399** [comment]
addressed by  PD work
