### ISSUE TITLE
Tying websites to services to customers to life events not to policies

### ISSUE THREAD

**Issue by anatecture** [GSA/EDX#483]
## Summary

As a user, I want to understand what a website does by simply reading its domain name and/or title. 

Given this need, @hatfieldjm4 @anatecture have been using exploring websites and tagging them with business capabilities, the terms of which started with the FEAF.

At the same time, sites like code.gov have come into EDX conversations as sites that are not supported but exist because they are either: 

1. called out in law or policy by name
2. law or policy has been answered by standing up a new website 

For the above reasons, policy- and law-based sites like code.gov exist, but they are not tied to supported services, customers, and/or life events. So the business capabilities work and the website evaluation work has come together. 

Additionally, there's a recent push to pull together a better technology site for GSA. We believe that, given the grounding research outlined above, we can inform this push. This issue describes how we might best do that. 

- [ ] @mvogelgesang writes up v1 draft of what to do about sites like code.gov (~..5 or 1 page or figma board or whatever)
  - 🔒 https://docs.google.com/document/d/1TmIcnvL0qosFvvnbVQCBYoQ9FBeQt8HB40UUa8fadXo/edit#
- [ ] @hatfieldjm4 writes up 4 or 5 rules for business capabilities tagging work
- [ ] @anatecture reads AD from ITC into tagging work for help on finishing out the list
- [ ] @anatecture writes up the history of business capabilities work (~.5 page) 
- [ ] @hatfieldjm4 writes up case study application of the business capabilities work inclusive of sites that use the same word in different ways, contributing to customer confusion. Ex. "requirements" (~.5-1 page) 

After that, wrap MV, JH, and AM's work together into history + path forward for DC in general but DZ, LM,(TTS); ML (IT); EW (OCE); VM, WJ, KK, RC (A) in particular.

**Comment by ryanwoldatwork** [comment]
"Life Events" are also referred to as "Occasions" in some documents.

Are there any Life Events or Occasions you'd like to link to Websites?

**Comment by anatecture** [comment]
Have not been able to get OMB traction on this collab. Good idea - too far down the road for now.
