### ISSUE TITLE
Tracking maintenance status of USWDS Themes

### ISSUE THREAD

**Issue by mvogelgesang** [GSA/EDX#490]
## Summary

A number of websites at GSA are using USWDS theme implementations which are in varying states of maintenance. At the individual website team level, there are a variety of factors which limit their ability to contribute to an open source theme implementation (cost, time, expertise to name a few). As a result, these websites are beholden to the maintainers of the themes. For example, there are no USWDS themes which are currently maintained for Wordpress - both are considered stale.

USWDS has a list of "stale" and "archived" implementations https://designsystem.digital.gov/documentation/implementations/

## Other thoughts and considerations

- Should this be measured in EDX reports? How might we best assess what themes are being used?
  - GitHub repos would be great but are not always accessible

```html
<!-- HOME PAGE MARKUP -->
<!-- wordpress -->
<link rel="preload" href="https://corporateapps.gsa.gov/wp-content/themes/benjamin/assets/frontend/css/benjamin.min.css?ver=6.0" as="style">
<!-- salesforce -->
<img role="img" src="/resource/1642615752000/uswds_2_x/img/icon-dot-gov.svg" alt="" aria-hidden="true" class="usa-banner__icon usa-media-block__img" data-aura-rendered-by="364:0">
```

```gem
# GEMFILE
# 18f.gsa.gov
uswds-jekyll (5.3.0)
```

```json
/* package.json */
"uswds": "^2.13.3"
```

- Should GSA consolidate around one or two primary content management systems and aid in the development and ongoing maintenance of those themes?
- How does the long term care for a theme play out? Who contributes funds or code?
- Is there an appetite for such an undertaking?

## Checklist

List below the specific actions to be taken

- [ ] item 1
- [ ] item 2

**Comment by AKM399** [comment]
discussed with @anatecture seems like  a problem not  a  project - will  review

**Comment by AKM399** [comment]
@mvogelgesang will post on github and chat with GSA IT people about his own theme.  On the broader issue - could be a CTO task.  Will be discussed between @anatecture and service delivery team

**Comment by AKM399** [comment]
out of scope
