### ISSUE TITLE
GSA Today article on CFC

### ISSUE THREAD

**Issue by RachelF** [GSA/EDX#504]
## Summary

Draft a short article on GSA's Award for CFC

## Additional context and links

[DRAFT article](https://docs.google.com/document/d/1UJqRCPtdCYwm8d_C3-Fxs_Rd8O5XwaVeX8y45Bk12_4/edit#)

## Checklist
- [x] draft article
- [ ] get new pic of new place with correct agency name
- [ ] Submit to OCE for review
- [ ] Publish

**Comment by RachelF** [comment]
updated todo list

**Comment by AKM399** [comment]
is this ready to close?

**Comment by RachelF** [comment]
we're not going to publish this -- instead, we'll share with the 2023 team and let them use as part of their kickoff for the new year's campaign
