### ISSUE TITLE
Add "Staging" and "decommissioned" to production statuses for the Touchpoints to airtable sync

### ISSUE THREAD

**Issue by mvogelgesang** [GSA/EDX#509]
## Checklist

List below the specific actions to be taken

- [ ] Sites in Touchpoints that transition from "Production" to another status should have that new status reflected in AT
- [ ]

**Comment by mvogelgesang** [comment]
Upon further investigation, the Touchpoints API returns only websites with a `production_status: "production",`. This leaves a gap when sites leave the production status- they would not be updated properly in Airtable.

Consuming a CSV of all website records and iterating over it may be a better solution (albeit not one that can be automated)

**Comment by mvogelgesang** [comment]
Update, TP API now returns all websites, need to update accordingly

**Comment by RachelF** [comment]
@AKM399 do you know if this is done? If so, can we close this? 

Current Touchpoints filters:
Production status = archived, production
Type of site = all except API, critical infrastructure 
Digital brand category = all except external

**Comment by AKM399** [comment]
@RachelF the agreement i believe is that we dont have to decommission because if a site is taken out of the register thats our signal that it is not in production.  Does that ring true enough to close?

**Comment by RachelF** [comment]
This is such an old ticket I think we can close it -- BUT we still have to apply manual filters when we download the inventory and most people don't know to do that, or know what filters to apply. So we should have a issue for working w/Ryan to figure out a solution in TPs -- and also should validate that the data transitions from TP to airtable (which I believe was the original reason for this ticket)

**Comment by AKM399** [comment]
OBE
