### ISSUE TITLE
Add sites from Sprint 4 and 5 into the design consults /charts.html page

### ISSUE THREAD

**Issue by mvogelgesang** [GSA/EDX#517]
## Additional context and links

Add any other context, screenshots, or links to working docs.

## Checklist

List below the specific actions to be taken

- [ ] item 1
- [ ] item 2

**Comment by mvogelgesang** [comment]
Looks like this is not a coding update but an update to Airtable

**Comment by AKM399** [comment]
double check and close

**Comment by AKM399** [comment]
@mvogelgesang ensure data is in there for 4 and 5, not to synch with design consults

**Comment by AKM399** [comment]
OBE
