### ISSUE TITLE
Website evaluation thank yous, asks for advice, and actions

### ISSUE THREAD

**Issue by anatecture** [GSA/EDX#519]
## Summary

A list of website teams who have done any of the following:

1. Thanked the EDX team for our work.
2. Told us they're immediately forwarding the eval to their dev teams or related teams for action.
3. Asked us questions about the eval.
4. Asked us for advice on how to move forward or take action.
5. Taken action.

Running tally of teams: 

- aas.gsa.gov
- acquisition.gov (by way of fai.gov showing our work)
- buy.gsa.gov
- cfo.gov
- challenge.gov
- code.gov
- d2d
- disposal.gsa.gov
- evaluation.gov
- gsaauctions.gov
- paymentaccuracy.gov
- pic.gov
- section508.gov
- ussm.gsa.gov

**Comment by AKM399** [comment]
is there any sort of recognition or thank you for participation we should send them?   call out the especially good actors to a-suite?

**Comment by AKM399** [comment]
blog post or digital.gov newsletter?

**Comment by RachelF** [comment]
added aas and re-ordered list (alpha order) so it's easier to see which sites are on the list

**Comment by RachelF** [comment]
Should we close this for FY22 and open a similar issue for tracking FY23? (I received a new request today from a team to review their in-progress uswds implementation)

**Comment by anatecture** [comment]
yes- thanks @RachelF - closing this issue and [opening a FY23 one](https://github.com/GSA/EDX/issues/613).
