### ISSUE TITLE
Website approval process

### ISSUE THREAD

**Issue by ryanwoldatwork** [GSA/EDX#52]
### Proposed process

Each week,
the GSA Digital Council
reviews a list of `newly_requested` websites from Touchpoints.

A user can request a new website domain at the Touchpoints page [/admin/websites/new](https://github.com/GSA/touchpoints/wiki/Websites).

New websites are "approved" or "denied" by users who have an "Organizational Website Manager" permission role in Touchpoints.

**Comment by ryanwoldatwork** [comment]
![Screen Shot 2021-09-03 at 2 46 10 PM](https://user-images.githubusercontent.com/64987852/134216310-ad86e987-c1d9-4a4f-813d-58f5dc975c97.png)

**Comment by anatecture** [comment]
How does this approval process work with teams to build compliant websites prior to their request in touchpoints? or does this process assume that compliance work has already been done? Who reviews and/or mentors teams through that compliance? How can teams track their work? Envisioning this as the role of the Statuscard. Thoughts?

**Comment by ryanwoldatwork** [comment]
The request in Touchpoints is the _technical_, ahem.. touchpoint, or point of interaction for the _organizational_ process around Website governance; digital lifecycle.

Similar to how creating a GitHub issue is the start of a specific process.

---

Ultimately, for a website that has already been created, create the website record in Touchpoints to account for the unaccounted digital property. The "approval" would be like a 'rubber stamp' since it'd be after the fact and not subject to the process.

**Comment by ryanwoldatwork** [comment]
@RachelF - a Website object currently has the field `notes` which a user can enter free-text.

To support this `Approval Process`, is another field needed/desire to track text related to justifying a website? Maybe something along the lines of "business_justification" which would be text describing the purpose of the website in terms of user and business value.

**Comment by AKM399** [comment]
@AKM399 add any lessons learned from techradar session, what worked what didnt etc?  recognizing that site is already in development.

**Comment by ryanwoldatwork** [comment]
`newly_requested` sites are easily reportable from Touchpoints. Digital Council can look at this each week, etc.

![Screen Shot 2021-10-29 at 1 17 38 PM](https://user-images.githubusercontent.com/64987852/139496717-7070bcc3-1f43-417a-9709-c752e0fc700b.png)
