### ISSUE TITLE
Update "Contact" IT Performance Metric scan criteria

### ISSUE THREAD

**Issue by mvogelgesang** [GSA/EDX#522]
## Summary

fapiis.gov recently came back with a `true` finding for Contact when no such section appeared on the site. Upon further examination, there was a CSS class `-webkit-contacts-auto-fill-button` which tripped the scan. 

## Checklist

List below the specific actions to be taken

- [x] update regex
- [x] create test case to ensure this works as expected

**Comment by AKM399** [comment]
@mvogelgesang to be addressed

**Comment by AKM399** [comment]
#491 related issue?
