### ISSUE TITLE
Add Basic Header to /design-consults

### ISSUE THREAD

**Issue by mvogelgesang** [GSA/EDX#533]
## Summary

Add a USWDS Basic Header to the design-consults site. https://designsystem.digital.gov/components/header/#basic-header

Include links to:
- design-consults/
- charts/
- website-list/

## Additional context and links

Add any other context, screenshots, or links to working docs.

## Checklist

List below the specific actions to be taken

- [ ] item 1
- [ ] item 2

**Comment by AKM399** [comment]
updates not made to site
