### ISSUE TITLE
Key stakeholder discussions: TTS

### ISSUE THREAD

**Issue by monicas-d** [GSA/EDX#54]
Ana, Aaron, Monica, Gail, Ed, and Patricia working on strategizing how to engage key stakeholders, and for now TTS.

**Comment by ryanwoldatwork** [comment]
What are the goals here?
Any idea what this work looks like yet?
I have ideas.

**Comment by monicas-d** [comment]
We would love to hear your ideas and we do not want to include any points here in GitHub due to sensitivities as this is public. Thanks!

**Comment by ryanwoldatwork** [comment]
Generally, I'd like to see specific agenda items, with asks for specific teams or poeople.
This seems important to inform how to engage key stakeholders.

**Comment by monicas-d** [comment]
One of the ways in which we can support improved relationships with TTS is to continue to state in all of our meetings about our work that we will "use what is here" (a part of our Guiding Principles), and that often we use tools from TTS (thus giving TTS the credit). I know Ana does this, and I want to make sure that we are **all** stating this, and giving recognition where due (and to their Digital Council - examples: 1-"Decommission Decision Tree: Required Site-No"; 2-edesign form; 3-Guidelines for new websites; 4-and questionnaire). We want to give them gratitude for their hard work, and credit.

**Comment by ryanwoldatwork** [comment]
* support better public services
* provide insights regarding the GSA-wide IT and Service ecosystem
  * inventory Websites
  * inventory Services
  * inventory Data Collections
  * identify staffing bottlenecks
  * identify technology duplication
  * identify underperforming solutions
* provide support to the Web Modernization project
* provide 1:1 guidance or Web Modernization support

**Comment by anatecture** [comment]
Who in TTS should we reach out to? Natalie has all the information from EDX, since she sits on the DC, but it doesn't seem like she's sharing the 

- inventory
- services
- data collection 

things with the rest of TTS. 

For staffing, I understand TTS is hiring a bunch right now; is that happening? 

Do you think EDX perspective in TTS conversations around technology duplication and underperforming solutions is desired by TTS? Given our relationship with them so far, which to me seems shaky, I don't know that our perspective would be welcomed on these topics.

**Comment by ryanwoldatwork** [comment]
It sounds like we're still in the exploratory phase, rather than proposing some type of work.

Does EDX have a specific value prop or method of engagement for TTS as a customer?

With a specific ask, I'd follow up with Ashley Mahan.

**Comment by monicas-d** [comment]
This is an ongoing discussion and requires lots of different pieces. I'm recommending we close this ticket. If anyone agrees, please let me know. Thanks! @anatecture @RachelF @gailsprinkle

**Comment by RachelF** [comment]
Agree @monicas-d we should close this. It's not specific enough and has been sitting out here for a long time.
