### ISSUE TITLE
fairs.reporting.gov

### ISSUE THREAD

**Issue by anatecture** [GSA/EDX#542]
Site lacks any elements of compliance.

**Comment by mvogelgesang** [comment]
@anatecture this looks like a bad redirect is in place. I submitted REQ0710887 in ServiceNow asking that the team address it. Navigating to https://www.fairs.reporting.gov/FAIRS/s/login/ results in a much nicer looking page.

**Comment by mvogelgesang** [comment]
@anatecture  Got a notification that the ServiceNow ticket had been closed and verified that fairs.reporting.gov redirects properly. Closing
