### ISSUE TITLE
Update Workflow to Close Issues when placed into the EDX Closed column

### ISSUE THREAD

**Issue by mvogelgesang** [GSA/EDX#544]
## Summary

https://github.com/GSA/EDX/tree/main/.github/workflows/opened-issues-inbox.yml

Update this to cover scenarios where a ticket gets moved to the closed column

## Additional context and links

Add any other context, screenshots, or links to working docs.

## Checklist

List below the specific actions to be taken

- [ ] item 1
- [ ] item 2

**Comment by AKM399** [comment]
not possible
