### ISSUE TITLE
Website Manager PD Review by EDX Technologists

### ISSUE THREAD

**Issue by mvogelgesang** [GSA/EDX#548]
## Summary

Review existing website manager PD's. Check for existing language that may be applicable to the management of a website, highlight. If no language present, flag it for additional review.

## Additional context and links

[Review Web Manager Position Descriptions for requirements (Skills, Competencies, Training) #113
](https://github.com/GSA/EDX/issues/113)

[Website Manager Position Description Work](https://github.com/GSA/EDX/issues/443)

[(figma) Defining Website Managers to Build PDs](https://www.figma.com/file/8Da4QI2kwYAelC1wEhxRNZ/Defining-Website-Managers-to-Build-PDs?node-id=0%3A1)

[(sheet) Web Manager Working Roster](https://docs.google.com/spreadsheets/d/1qkKrkeVltP0XHTC-W4sJU979B1Vh__0jamSewYes6r8/edit#gid=455384883) - the PD's will be in varying formats, Gail will update them into Google Doc format and will link them to the sheet

**Comment by anatecture** [comment]
Next step: schedule meetings w/ supervisors. [See asana for this schedule](https://app.asana.com/0/1202817062418327/1202872671736235).

**Comment by anatecture** [comment]
Report out to Exec Board the PDs that have been changed to reflect website manager status. 

We could just let the supervisors go up their own chain, but [@Gail Sprinkle](https://app.asana.com/0/1199679778556279/list)'s thought is that it should come through EDX. This is documentation that the SES has met this performance metric, so this is why this has to come from outside of the chain of command, and it should probably go to the HSSO. 

We can draft a simple paragraph and put the SES-er, the Supervisor, the Website Manager, and the Digital Property for each.

**Comment by mvogelgesang** [comment]
Reviews complete
