### ISSUE TITLE
Edit and publish HCD Guides

### ISSUE THREAD

**Issue by RachelF** [GSA/EDX#551]
## Summary

Review and edit HCD Guides, adapt for publication on InSite.

## Additional context and links

[Add any other context, screenshots, or links to working docs.](https://drive.google.com/drive/folders/1fstFjJQgzcaU2EMAjPaGHNzoL2IfaDnZ)

## Checklist

- [x] Create discovery guides as gDocs
- [x] Create design guides as gDocs
- [x] Review and edit discovery-why
- [x] Review and edit discovery-how
- [x] Ensure "how" and "why" content is in alignment (use the same labels/naming conventions for steps and process, present in the same order, etc.)
- [x] Meet with Katie to determine where content will live in IA and how it should be organized
- [x] Create a landing page containing HCD overview and links out to all guides content
- [x] Submit landing page for publication
- [x] Submit discovery ops for publication
- [x] Submit discovery concepts for publication
- [x] Review and edit design-why
- [x] Review and edit design-how
- [x] Ensure design "how" and "why" content is in alignment (use the same labels/naming conventions for steps and process, present in the same order, etc.)
- [x] Submit design concepts for publication
- [x] Submit design ops for publication
- [x] Review and edit glossary
- [x] Submit glossary for publication
- [x] Review and edit background page
- [x] Submit background page for publication

**Comment by RachelF** [comment]
Updated checklist to include more detail about scope of work and amount/type of content

**Comment by anatecture** [comment]
@lilaconlee and I will format the images in the upcoming week.

**Comment by anatecture** [comment]
- [ ] @lilaconlee looking into the image requirements for Insite and Google Sites. 
- [ ] @anatecture @lilaconlee will reformat images to fit requirements in upcoming week

**Comment by RachelF** [comment]
[gDoc Template for new HCD Guides content](https://docs.google.com/document/d/1FJQhyNoOo1O3OG07gfZsLaG2QC6zkWTKnXNuPp7Xel8/edit#heading=h.9shpbyeheghb)

**Comment by RachelF** [comment]
Met w/Digital.gov team and we'll work w/them to publish under DG umbrella.

**Comment by AKM399** [comment]
on hold at the moment.  Needs implementation plan next.

**Comment by RachelF** [comment]
Met with Digital.gov team this week to discuss project reqs and how it might fit into the new site IA they're designing; also discussed looping CFA Intern into this work once he's onboard

**Comment by RachelF** [comment]
Content is with Digital.gov team; @jacksonmoody is working with that team to build a framework to host the content
