### ISSUE TITLE
Scanner - GSA Guidelines for Digital Presence 

### ISSUE THREAD

**Issue by mvogelgesang** [GSA/EDX#557]
## Summary

Create a new section in the report for compliance criteria based off of GSA's Guidelines for digital presence.

## Additional context and links

Include evals for the following:
- About Page
- Linking policy
- Privacy
- FOIA
- Accessibility
- etc

## Checklist

List below the specific actions to be taken

- [ ] item 1
- [ ] item 2

**Comment by AKM399** [comment]
#451

**Comment by AKM399** [comment]
closed due to lack of context
