### ISSUE TITLE
forms.gov

### ISSUE THREAD

**Issue by anatecture** [GSA/EDX#558]
## Summary

Came up via this chat: 

In other news, I just got a DNS request for [portal.forms.gov](http://portal.forms.gov/). I'm still reeling that [forms.gov](http://forms.gov/) is going to be a thing 😞

Ana Monroe Fitzner - O, Jul 8, 9:13 AM
...annnnnd [submission.forms.gov](http://submission.forms.gov/). why. why?

Mark Vogelgesang - O, Jul 8, 10:07 AM
**they might be creating unique DNS for parts of the service that is being built - not necessarily a user facing location**

for instance, when I log into my ba[n]k, I go from [truist.com](http://truist.com/) to [auth.truist.com](http://auth.truist.com/) and back to [truist.com](http://truist.com/)

they do that so they can have discreet services

on paper, it smells strange

but **practically speaking, makes sense**

Aaron Meyers - O, Jul 8, 10:09 AM
have you tried clicking the links in [forms.gov](http://forms.gov/) yet?

half of them go to agency form pages, half of them go to agency front pages

some of them just go to random news pages, its rando

Ana Monroe Fitzner - O, Jul 8, 2:57 PM
point well made, @Mark Vogelgesang - O. it's tough because we want to stop new dns-es before they go online, but also, as you say, there are structural reasons to build that way. so how do we know, from this POV, which to reach out about and which to not to? Sometimes the DNS gives us a clue, like the portal.forms one seems like it might be just structural, but on the other hand, we've seen so many wacky structures that I guess my default is to treat them all like they're user-facing. It's a bit of a pickle.

And yes @Aaron Meyers - O the randomness of the forms is one of the perennial problems with the [forms.gov](http://forms.gov/) concept. It's been an issue for years now. It's such a good idea, but it's built on the assumption that the team can impose organizing principles around what are, in all honestly, a random collection of forms, most of which no one will ever need. It's a huge conceptual issue being treated as a technical one, IMHO

**Comment by anatecture** [comment]
from @mvogelgesang:  

Dug into the prior chat threads about [forms.gov](http://forms.gov/) (https://mail.google.com/chat/u/0/#chat/space/AAAAABdwBjc/P8o3QjNjYfI) and both [portal.forms.gov](http://portal.forms.gov/) and [submissions.forms.gov](http://submissions.forms.gov/) are not resolving in the browser. 

I believe [portal.forms.gov](http://portal.forms.gov/) was the site that had the login experience. I dug through github as well and am not finding a public home to this stuff at the moment.

**Comment by anatecture** [comment]
So is it safe to conclude @mvogelgesang, that these DNS-es will be structural and not publicfacing? Should we code them as infrastructure in the Website Inventory?

**Comment by mvogelgesang** [comment]
@anatecture yes, I think we mark these as infrastructure. Once you confirm, we can close

**Comment by AKM399** [comment]
to contact team and get a statement of whether or not these will go public

**Comment by anatecture** [comment]
**Thinking these have been rolled back, per email:** 

IT Service Desk | IT Service Desk | Mon, Sep 26, 12:00 PM 
to me


This message has been deleted. Restore message
Please be aware that the following DNS request has been requested:
 
Number: RITM1002111
Short description: Employees can request unique website identifications or .gov domain names. for James P Moy - [james.moy@gsa.gov](mailto:james.moy@gsa.gov)
DNS Type: External DNS
DNS Subtype: Delete Record
Business Justification: Removing Forms Service 1.1 domain names
Additional Information: https://portal.forms.gov/
https://submission.forms.gov/
https://sign.forms.gov/
https://api.forms.gov/
https://portal-dev.forms.gov/
https://submission-dev.forms.gov/
https://sign-dev.forms.gov/
https://api-dev.forms.gov/
https://portal-test.forms.gov/
https://submission-test.forms.gov/
https://sign-test.forms.gov/
https://api-test.forms.gov/
https://epa.submission.forms.gov/
https://epa.submission-dev.forms.gov/
 
*.[sign.forms.gov](http://sign.forms.gov/)
*.[sign-test.forms.gov](http://sign-test.forms.gov/)
*.[sign-dev.forms.gov](http://sign-dev.forms.gov/)
 
Please have a nice day.
 
Ref:MSG28302876
