### ISSUE TITLE
sites with custom privacy policy

### ISSUE THREAD

**Issue by mvogelgesang** [GSA/EDX#561]
## Summary

The Vote.gov team currently directs to the privacy policy on usa.gov and long term will have their own privacy policy. The site offers translations in multiple languages and the new privacy policy will do just that. 

Code.gov also has a unique privacy policy.

Update scanner to denote code.gov, vote.gov has its own.

## Additional context and links

Add any other context, screenshots, or links to working docs.

## Checklist

List below the specific actions to be taken

- [ ] item 1
- [ ] item 2

**Comment by AKM399** [comment]
work complete
