### ISSUE TITLE
edxcli - default logging

### ISSUE THREAD

**Issue by mvogelgesang** [GSA/EDX#570]
## Summary

Recent scans on 9/20 and 9/21 resulted in a handful of sites failing to complete their scan. Suggest switching the default logging posture and writing files locally for reference. 

## Additional context and links

Add any other context, screenshots, or links to working docs.

## Checklist

List below the specific actions to be taken

- [ ] item 1
- [ ] item 2

**Comment by RachelF** [comment]
OBE
