### ISSUE TITLE
Bug - sites which error out when scanning

### ISSUE THREAD

**Issue by mvogelgesang** [GSA/EDX#571]
## Summary

A handful of sites consistently error out when scanning and stop the scan altogether. Suggest identifying where those breaks occur, enhancing the resiliency, and ensuring that even partial files can be written.

## Additional context and links

Add any other context, screenshots, or links to working docs.

## Checklist

List below the specific actions to be taken

- [ ] item 1
- [ ] item 2

**Comment by AKM399** [comment]
input for website selection #559

**Comment by AKM399** [comment]
will open new issues if problem is persistent
