### ISSUE TITLE
Reply to DNS requests and Touchpoints registrations

### ISSUE THREAD

**Issue by anatecture** [GSA/EDX#572]
## Summary

As a receiver of DNS requests and Touchpoints registrations, I need a way to quickly reply to registrants. Boilerplate below

**Comment by anatecture** [comment]
Thanks for registering your intention to have a website! To help ensure your site's long term success, including having the proper resources and maintaining compliance with GSA and federal website policies and regulations, GSA's Enterprise Digital Experience (EDX) Team has implemented the Digital Lifecycle Program. 

This series of questionnaires and checklists covers the approximately 102 OMB policy and legal requirements you'll need to fulfill to maintain a federal digital property.* Start with the Proposal Phase (8 questions) to make sure you've got your ducks in a row to support this site in terms of staffing and funding. 

After you've submitted the proposal, EDX will schedule a 30 minute discussion so we can go over anything you might have concerns on and make a plan for your build. 

Please note, if you or your team takes a look at the DLP and would like to discuss alternatives to an independent website to avoid the burden of supporting one while still meeting the team's digital mission, we're happy to discuss those alternatives. Some options include microsites, which are groups of pages on larger sites that are tailored to specific programs, individual pages on [gsa.gov](http://gsa.gov/) or other gsa sites, and/or pages on Insite (depending on your audience) 

Looking forward to chatting!

W/r,

*Please note that the EDX team did not create any of these requirements; the DLP simply untangles the requirements that are embedded in federal policy and law.

**Comment by RachelF** [comment]
Created a [folder to host content related to website submissions](https://drive.google.com/drive/folders/1jILco8aZOvOnDm4D-fLYffqNjo1ccLBa) and a gDoc with [content for the pre- and post-interview emails](https://docs.google.com/document/d/1lrVaugsu2Cy9IWt_NeJqG7by2XdpEfgqvOXR7xkg9tk/edit#) with teams who submit a website proposal, so we have a central place to keep track of all these conversations. Feedback welcome @anatecture @mvogelgesang

**Comment by anatecture** [comment]
Please use document folder for outreach. 

Note that [there's an issue with first drafts](https://github.com/GSA/EDX/issues/514) of an outreach email and an interview guide for talking to teams.

**Comment by anatecture** [comment]
folding this into issue #636
