### ISSUE TITLE
OGP sites SSL cert and other issues

### ISSUE THREAD

**Issue by anatecture** [GSA/EDX#581]
## Summary

We've gotten several notifications of OGP sites not in compliance w/ 21st Century IDEA and/or lacking SSL certs. They are: 

[reginfo](https://github.com/GSA/EDX/issues/535) 
[mobile.reginfo.gov](https://github.com/GSA/EDX/issues/541)

buyaccessible.gov - it's a redirect to app.buyaccessible.gov, but still needs an SSL cert 

**Action 09/27**
After end of fiscal year, check on these sites, reach out to Linel and Jen Hanna to bring these up to compliance.

**Comment by mvogelgesang** [comment]
Checking on these sites today, 10/17

reginfo has a new and valid cert with the following dates:
Issued On	Sunday, August 21, 2022 at 8:00:00 PM
Expires On	Wednesday, September 20, 2023 at 7:59:59 PM

buyaccessible returns a valid cert as well. 

@anatecture seems like these are SSL cert update requests. Suggest closing
