### ISSUE TITLE
NCSW 2022

### ISSUE THREAD

**Issue by RachelF** [GSA/EDX#582]
## Summary
Work with Genevieve and Dionne to develop content and shepherd through OSC approvals for publication first week of October, celebrating National Customer Service Week (NCSW) and CX Day.

## Additional context and links
[Timeline and links to all OCE content for NCSW](https://docs.google.com/document/d/1slCXvy21MaQn9PwxxuGgt0Wbl8C0aZFW0rEHXOodK2g/edit#)
Add any other context, screenshots, or links to working docs.

## Checklist

- [x] Identify what we want to publish
- [x] Draft content
- [x] Identify timeline for what gets published and when
- [x] Coordinate with OSC
- [x] Finalize content
- [x] Publish content

**Comment by AKM399** [comment]
okay to close?

**Comment by RachelF** [comment]
Closing; OSC is looking for some data on impact of our campaign
