### ISSUE TITLE
Establish standard GSA Website contract language

### ISSUE THREAD

**Issue by mvogelgesang** [GSA/EDX#583]
## Summary

When it comes to Section 508 and security, there are clear contract clauses available for inclusion into a future website contract. On the design side, such language is not as stringent or consistent. Propose establishing a contract clause that all website teams can use. In addition to saying "contractor shall" we should also look at ways to say "this will be measured/ approved by edxcli, OSC, etc"

## Additional context and links

USWDS has some suggested language: https://designsystem.digital.gov/documentation/sample-contract-language/

## Checklist

List below the specific actions to be taken

- [ ] confirm which legal teams can help w/this (OCE rep; new tech team in OGC)
- [ ] ask DC members to share contract language as a model for others?

**Comment by RachelF** [comment]
sounds like https://app.buyaccessible.gov/ but for security... agree that standardized language around security requirements would be useful

**Comment by AKM399** [comment]
could be included by reference with IT policies and memos.  Should be cross checked against 508 ART tool.

**Comment by AKM399** [comment]
@hursey013 does this possible link to the continuous integration projects?

**Comment by AKM399** [comment]
needs legal point person.

**Comment by RachelF** [comment]
Service Delivery is working on this
