### ISSUE TITLE
legacy.digitaldashboard.gov

### ISSUE THREAD

**Issue by anatecture** [GSA/EDX#590]
## Summary

Subdomain for digital dashboard team

## Additional context and links

Rachel reached out to Marina Fox, this is the framing, September 2022: 

`This is a short term solution (till about January) to ensure that we have legacy digital dashboard environment and data while the new environment is being worked on. It’s taking longer than we hoped so we need to continue our operations in legacy. We need a new subdomain because it’s a completely different environment and not part of OGP It dashboard. I requested this domain.`

## Checklist

List below the specific actions to be taken

- [ ] Check in with Marina in January to see if they're on schedule to pull this down. If not, ask why and if they need to seek a longer term solution.

**Comment by anatecture** [comment]
Site is still up; we need to reach out to M Fox and see when they're looking to sunset this. Depends on some backend work they're doing. Pinning this outreach to February.

**Comment by AKM399** [comment]
@AKM399 add to touchpoints

**Comment by RachelF** [comment]
migration expected by July 1

**Comment by AKM399** [comment]
@AKM399  has not migrated.  goes into year 3 evals.

**Comment by AKM399** [comment]
@beharti future decommissioning candidate

**Comment by RachelF** [comment]
Now that ITDashboard is live, OGP is likely going to decommission this, but no date identified yet

**Comment by RachelF** [comment]
Marina reported that OGP will be closing digitaldashboard soon, now that ITDashboard is live

**Comment by anatecture** [comment]
Site is down!
