### ISSUE TITLE
Blog post / talk track re: enhancing your site via what is available to you

### ISSUE THREAD

**Issue by mvogelgesang** [GSA/EDX#598]
## Summary

The 21cIDEA was passed without funding which has left some teams saying "well I can't do anything because I don't have money". While it may be true that they cannot make development changes at this moment, they can listen to user needs, audit content, establish a backlog of accessibility updates, etc.

Further, we need to better explain the business value of IDEA act to all parties involved
## Additional context and links

Add any other context, screenshots, or links to working docs.

## Checklist

List below the specific actions to be taken

- [ ] item 1
- [ ] item 2

**Comment by AKM399** [comment]
subsumed by #388
