### ISSUE TITLE
Shut down identity-dev-docs.18f.gov

### ISSUE THREAD

**Issue by anatecture** [GSA/EDX#60]
## Summary

Decommission identity-dev-docs.18f.gov, per website manager amos stone. Bring this to next Digital Council Meeting, 10/05, for recommendation for shut down

## Additional context and links

Convo in slack, 9/24: 
Hi Amos! My name is Ana Monroe; I work w/ Ryan Wold on the Enterprise Digital Experience Team. Checking in on some website manager stuff: are you the manager for identity-dev-docs.18f.gov?

J. Amos Stone (login.gov/sqa/he)  3:10 PM
:wave:
3:10
I suppose I am
3:10
it should be retired

Ana  3:10 PM
oh great!
3:10
thanks for your quick reply! i'll let the team know

## Checklist

List below the specific actions to be taken

- [x] Check [TTS decommissioning docs](https://handbook.tts.gsa.gov/launching-software/infrastructure/#decomissioning)
- [X] determine whether site needs to be archived - [no. it is already offline.]
- [X] determine if any parts of content need to be reallocated to other sites - [no. it is already offline.]
- [x] the determinations above should be generalized and made part of our v1 Digital Lifecycle Program

**Comment by ryanwoldatwork** [comment]
related:

Remove entries from https://github.com/18F/dns/blob/main/terraform/18f.gov.tf

**Comment by ryanwoldatwork** [comment]
https://github.com/18F/dns/pull/537

**Comment by ryanwoldatwork** [comment]
@anatecture, @gailsprinkle - is there work left related to:

> the determinations above should be generalized and made part of our v1 Digital Lifecycle Program

Generally, this may imply GSA IT adopting some part of the TTS decommissioning process. But I'm not sure if/where it'd go in the DLP. Thoughts?

**Comment by gailsprinkle** [comment]
@monicas-d and I requested that Natalie share the TTS decommissioning process document with us, but she declined saying it wasn't ready to be shared. So, I don't know if GSAIT is using a rogue draft TTS decommissioning doc, or if they're just taking logical steps?

DLP: Yes, absolutely, decommissioning/sunsetting will be included in the DLP document.

**Comment by ryanwoldatwork** [comment]
It is covered here: https://handbook.tts.gsa.gov/launching-software/infrastructure/#decomissioning

What specific deliverables are still in question?

**Comment by gailsprinkle** [comment]
@ryanwoldatwork  thanks for that! @monicas-d and I were certain we had seen that doc but neither of us could find it. Need to clarify what document Natalie is talking about. Where is this published?
My goal this week is to get the DLP skeleton out of my head and down on paper. Rachel helped me think through some issues Friday and I look forward to meeting with you tomorrow.

**Comment by monicas-d** [comment]
Natalie is not happy with whomever published this on their handbook as she
said it is not ready for publication. If we were to use that document
without her permission, then that shuts down our relationship with her and
potentially others in TTS. Let's please discuss before sharing that
document as it's not our place to do so.


-- 

U.S. General Services Administration

*Monica Suber-Duffy*, GCDF <http://www.cce-global.org/GCDF> and Federal
Internal Coach
<https://insite.gsa.gov/topics/training-and-development/developmental-services/coaching-services>

Organizational Development Consultant
<https://insite.gsa.gov/topics/training-and-development/developmental-services/organizational-development>

GSA  | OHRM Talent Development

Pronouns: She/Her/Hers

Office of Human Resources Management (OHRM)

1800 F St, NW

Washington, DC 20526

Mobile: (202) 701-8197

E-mail: ***@***.***

Join the Yoga & Mindfulness Chatter Group
<https://gsa.my.salesforce.com/_ui/core/chatter/groups/GroupProfilePage?g=0F9t0000000aU0i>,
and see our page on InSite
<https://insite.gsa.gov/topics/training-and-development/continuous-learning/yoga-mindfulness>

Between stimulus and response there is a space. In that space is our power
to choose our response. In that response lies our growth and our
freedom.-Viktor
E. Frankl

<https://insite.gsa.gov/topics/hr-pay-and-leave>
