### ISSUE TITLE
Google Analytics / Search Console Indicators

### ISSUE THREAD

**Issue by mvogelgesang** [GSA/EDX#601]
## Summary

A collection of datapoints that may require further investigation

- websites who receive a bulk of their traffic as a referral from another GSA website. 
  - This may indicate that the destination site does not rank as high in search results, folks search using one term but actually a more nuanced term is needed. The destination site might not be SEO optimized
- deep pages on gsa.gov (long url paths) which link to a homepage. 
  - Being at such a deep url path may indicate the user is digging into a very specific topic. When they get linked to a homepage, they may have to start all over when digging into that topic area. For instance, 

| page | destination|
|---|-----|
| gsa.gov/this/that/theother/another/yetmore | sam.gov/ |
  
- If users are on a given page and then enter a search into the search box, that is an indication that they did not find what they are looking for. Pages which refer a lot of traffic to search could be indicative of pages which don't match a user expectation
-

**Comment by AKM399** [comment]
#451

**Comment by anatecture** [comment]
not pursuing
