### ISSUE TITLE
FY23 - Website evaluation thank yous, asks for advice, and actions

### ISSUE THREAD

**Issue by anatecture** [GSA/EDX#613]
FY23 follow on from [closed issue 519](https://github.com/GSA/EDX/issues/519)

A list of website teams who have done any of the following:

Thanked the EDX team for our work.
Told us they're immediately forwarding the eval to their dev teams or related teams for action.
Asked us questions about the eval.
Asked us for advice on how to move forward or take action.
Taken action.

**Comment by anatecture** [comment]
@RachelF could you add the team who reached out to you last week?

**Comment by AKM399** [comment]
4/6 thank you note from Billy Wales

**Comment by RachelF** [comment]
Ammie Farraj Feijoo also expressed appreciation for our 2023 evaluation and shared it with her team and leadership. They are now discussion options for consolidating some of the sites in their portfolio into Digital.gov to reduce administrative overhead and streamline CX.

**Comment by AKM399** [comment]
to be updated with share requests

**Comment by AKM399** [comment]
finished evals
