### ISSUE TITLE
FAS program management of websites 

### ISSUE THREAD

**Issue by anatecture** [GSA/EDX#614]
Only six websites, column two contains the name of the FAS web manager as identified by GSA IT. We have not met with these FAS web managers
| website | new manager |
|----|----|
| epay.fas.gsa.gov | Assign Website Manager as Gordan Lancaster |
| wdolhome.sam.gov | Assign Website Manager as Christy Hermansen |
| scopereview.gsa.gov | Assign Website Manager as Bart Bates |
| eoffer.gsa.gov | This should be Tim Dempsey |
| mcm.fas.gsa.gov | This should be Tim Dempsey |

**Comment by anatecture** [comment]
Need to reach out to these managers @gailsprinkle @monicas-d @anatecture +Camille. I'll take the first step by reading Camille in.

**Comment by anatecture** [comment]
adding [itvmo.gsa.gov](http://itvmo.gsa.gov/) FAS (QT) to this list. Current list: 

- [ ] epay.fas.gsa.gov | Assign Website Manager as Gordan Lancaster
- [ ] wdolhome.sam.gov | Assign Website Manager as Christy Hermansen
- [ ] scopereview.gsa.gov | Assign Website Manager as Bart Bates
- [ ] eoffer.gsa.gov | This should be Tim Dempsey
- [ ] mcm.fas.gsa.gov | This should be Tim Dempsey
- [ ] [itvmo.gsa.gov](http://itvmo.gsa.gov/) FAS (QT)

**Comment by gailsprinkle** [comment]
Noted. Ana will schedule a meeting with Camille and me to discuss our approach.

**Comment by AKM399** [comment]
@AKM399 tagging self to maintain as interviews occur.

**Comment by AKM399** [comment]
all managers assigned
