### ISSUE TITLE
EDXCLI - add preset for Condense command - GEAR data imports

### ISSUE THREAD

**Issue by mvogelgesang** [GSA/EDX#616]
## Summary

Update the `data condense` command to support a preset specific to the data structures needed in the GEAR website_scans table.

## Additional context and links

Add any other context, screenshots, or links to working docs.

## Checklist

List below the specific actions to be taken

- [ ] item 1
- [ ] item 2

**Comment by anatecture** [comment]
OBE b/c of GEAR
