### ISSUE TITLE
Deprecate Management.cio.gov

### ISSUE THREAD

**Issue by anatecture** [GSA/EDX#617]
[Management.cio.gov](http://management.cio.gov/) is still up despite its deprecation date of 10/31. 

@hatfieldjm4 has reached out to Alycia Yozzi (OGP) who directed to Alison O'Mara (QU) who directed to Andrea Wood (OGP) who directed to Olivia Haring (QQ). No response yet from Olivia. 

reach out again week of 11/14

**Comment by mvogelgesang** [comment]
Website cannot be resolved, changed status to Decommissioned in Touchpoints and closing issue
