### ISSUE TITLE
Guidance for teams transitioning from legacy GA to GA4

### ISSUE THREAD

**Issue by mvogelgesang** [GSA/EDX#618]
## Summary

A handful of teams have reached out regarding the migration to GA4. For DAP users leveraging the CDN-hosted copy of Analytics, this will be seamless. However, many sites which have an authenticated experience also leverage a separate Google Analytics account in order to see authenticated behavior. These teams require guidance.

## Checklist

- [x] Investigate the different means by which teams include GA on their sites (self hosted, cdn, google tag manager)
- [x] Provide instructions for each variation
- [ ] steer teams away from self hosting Analytics
  - [ ] #671
  - [ ] Reach out to those teams to make the switch

**Comment by mvogelgesang** [comment]
At this time, the DAP team has yet to release an update that switches Universal Analytics to GA4. When they do, the change will be seamless for users leveraging the CDN version

**Comment by AKM399** [comment]
goal is to have teams use cdn provided by  analytics.

**Comment by AKM399** [comment]
gather data on who has their own code and follow up later.  #671
