### ISSUE TITLE
GSA IT End User Services

### ISSUE THREAD

**Issue by mvogelgesang** [GSA/EDX#620]
## Summary

The End User Services (IDTR) team reached out regarding an ongoing conversation between their team and OCE. This will be a monthly-ish get together and will aim to identify projects where OCE can best support IDTR. 

Notes from the first meeting: https://app.asana.com/0/13584958764263/1203385640352695

**Comment by AKM399** [comment]
liason work

**Comment by AKM399** [comment]
closed because its not current
