### ISSUE TITLE
DNS request outreach: http://gsafleet2go.fas.gsa.gov/ 

### ISSUE THREAD

**Issue by anatecture** [GSA/EDX#621]
**What:** DNS request for [gsafleet2go.fas.gsa.gov](http://gsafleet2go.fas.gsa.gov/) 
**Who:** Lemmage

**Issue:** site doesn't present any content useful to the public user

**Ask to Lemmage team:** pull this site back to staging until you figure out the greater content.

**Comment by AKM399** [comment]
Adding this to our list of people who need t update their inventory listing or get in compliance.

**Comment by AKM399** [comment]
@anatecture to reach out to chipman again.

**Comment by AKM399** [comment]
also potentially follow up with Jessica Murray.

**Comment by AKM399** [comment]
itll drop eventually when feasible.
