### ISSUE TITLE
New websites & barriers to joining existing web properties

### ISSUE THREAD

**Issue by mvogelgesang** [GSA/EDX#625]
## Summary

From time to time, we receive DNS requests for new domains that will be used to host a one-off website. In many cases, the team building the new site allude to the fact that it is easier to build a site from the ground up than to contribute content and/or create a new content experience on an existing website. These challenges are human in nature rather than technical. Propose that we investigate the barriers to adoption and how they might be overcome.

Some initial thoughts/ questions on this subject include:

* Pre-existing websites may not have the mandate to house a variety of content and experiences. That is, they might not be set up to support a 3rd party development team coming in
* The illusion of an independent site may be achieved through vanity redirects e.g. importantissue.gsa.gov could point at gsa.gov/importantissue and none would be the wiser
* The long term maintainability of new content and any related code is likely an issue for the team that created it along with the team performing O&M. As a vendor, I would not want to take responsibility for someone else's code without certain assurances.
* How does GSA the organization influence and direct the backlogs of our large digital properties which are enterprise assets? 
* Perception that visibility of content is lost if housed in a larger site (#406)

**Comment by AKM399** [comment]
#406

**Comment by AKM399** [comment]
closing as it was covered in @gailsprinkle research
