### ISSUE TITLE
Add Broken Link Check facet to scanner

### ISSUE THREAD

**Issue by mvogelgesang** [GSA/EDX#628]
## Summary

A WebMod working group is looking at GSA websites for broken links, having an automated means for producing these reports would be valuable. 

## Additional context and links

[Broken Link Checker](https://github.com/stevenvachon/broken-link-checker) does not rely upon Puppeteer and would cover most GSA sites in a headless mode. 

The current implementation utilizes bash but should be changed into a node implementation with stronger error handling.

```sh
#!/bin/bash

now=$(date '+%Y-%m-%d') # _%H:%M:%S
folder="linkCheck/$now"
logFile="log.txt"
outputs="$folder/output.txt" #"test/$now"
userAgent="GSA IT Performance Metric - SM10-1 GSA IT-Supported Websites Compliant with 21st Century Digital IDEA Act Principles"

mkdir -p $folder

echo "New folder created in data/$now"
echo "domain, scan url, category" >> $outputs

strings=(
website1
website2
)

for i in "${strings[@]}"; do
    ## print full html of site to dataFolder, save final url (post redirects) to url var

    echo "$i, start, $(date '+%Y-%m-%d_%H:%M:%S')" >> "$folder/$logFile"

    npx broken-link-checker https://$i -fgr --filter-level 3 --requests 5  >> "$folder/$i.txt"
   
    echo "$i, completed, $(date '+%Y-%m-%d_%H:%M:%S')" >> "$folder/$logFile"
done

compDate=$(date '+%Y-%m-%d_%H:%M:%S')
echo "Processing complete at $(date '+%Y-%m-%d_%H:%M:%S')" 

```

## Checklist

List below the specific actions to be taken

- [ ] item 1
- [ ] item 2

**Comment by AKM399** [comment]
OBE due to site improve being accessible

**Comment by RachelF** [comment]
OSC now has SiteImprove which does link checking; sites can request to be added to OSC subscription
