### ISSUE TITLE
Follow up on requests for new websites

### ISSUE THREAD

**Issue by RachelF** [GSA/EDX#629]
## Summary
Follow up with teams who've requested a new website in Touchpoints.

## Checklist of sites that need followup
@mvogelgesang and @RachelF reviewed these to determine status and next steps:

- asap.gsa.gov - LIVE - follow up needed to identify owner; looks like FAS content; login page for GSA Advantage Spend Analysis Program (ASAP)
- collab.gov - NOT live - follow up with amos.stone@gsa.gov, TTS about DLP process
- fac.gov - LIVE; Fed Audit Clearinghouse is a placeholder for content moving from Census to GSA; follow up with fac@gsa.gov about DLP
- fleet.gov - NOT live; follow up with jamie.lindabury@gsa.gov, FAS about DLP (submitted as an application)
- piv.golearnportal.gov - needs followup about DLP and requirement to host site on .gov - Comment from Ryan W in Touchpoint states "The site is actually: https://piv.golearnportal.org/ Alison Kohler pointed me (Ryan) to it, Sheila Berlin and Sheila Dawson may be contacts." -- should redirect to https://piv.golearnportal.org/ 

Rachel also updated the status of several other sites in Touchpoints; most sites were already live but not yet in Touchpoints.

@anatecture let us know how you'd like to tackle next steps

**Comment by RachelF** [comment]
Additional notes on two new sites:
identityequitystudy.gsa.gov is the site submitted by Gerardo C-O
tbd.gsa.gov is a placeholder submitted by Joslann I; we're meeting w/her week after next.

**Comment by RachelF** [comment]
@anatecture @mvogelgesang Have either of you reached out to any of the sites listed here? If not, lmk and I can follow up after the holidays, now that we have a template email to engage w/these teams.

**Comment by mvogelgesang** [comment]
@RachelF No, I have not

**Comment by RachelF** [comment]
for awareness @anatecture @mvogelgesang @hatfieldjm4 @gailsprinkle 
- [ ] asap.gsa.gov - LIVE - RF reached out to Brad/Jaime to identify the website manager and update the record
- [ ] calm.gsa.gov - LIVE - RF reached out to Valarie Tran to have someone from her team update the site record in TP, and confirm whether the site is for an internal or external audience; RF also updated TP to show that site is in production
- [ ]  collab.gov - tagged as infrastructure; RF followed up with [amos.stone@gsa.gov](mailto:amos.stone@gsa.gov), TTS to confirm site status (IF infra, no further action required on our part)
- [ ]  fac.gov - LIVE - RF followed up with Sarah Withee (who created the TP record) and fac@gsa.gov about DLP

**STILL needs followup**:
- [ ]  fleet.gov - NOT live; need to follow up with [jamie.lindabury@gsa.gov](mailto:jamie.lindabury@gsa.gov), FAS about DLP (submitted as an application)
- [ ]  piv.golearnportal.gov - needs followup about DLP and requirement to host site on .gov - Comment from Ryan W in Touchpoint states "The site is actually: https://piv.golearnportal.org/ Alison Kohler pointed me (Ryan) to it, Sheila Berlin and Sheila Dawson may be contacts." -- should redirect to https://piv.golearnportal.org/
- [ ] gsa.gov/workplace - Sponsor (Chuck Hardy), Website Manager (Leslie LaMar) (ref email exchange btwn Ana/Vicki)

**Comment by RachelF** [comment]
AM reached out to Gordon Dean about pidatacollection.paymentaccuracy.gov

**Comment by RachelF** [comment]
@RachelF to follow up on catalog.gsa.gov, eis-public-pricer.eos.gsa.gov, msa-pub.gsa.gov, sourcedata.gsa.gov, fleet and pivgolearn

**Comment by RachelF** [comment]
Moving sites that still need followup to [new Issue #719 ](https://github.com/GSA/EDX/issues/719)  and closing this one
