### ISSUE TITLE
Discover GSA websites based on Site Scanner data

### ISSUE THREAD

**Issue by ryanwoldatwork** [GSA/EDX#63]
What data and cadence and what happens with the new sites identified.
### User Story

As an Admin,
I want to create new entries for GSA websites in the Touchpoints database based on Site Scanner data,
So that I can ensure websites are fully inventoried
And so that Website Managers are identified.

### Acceptance Criteria

Given a website is discovered by Site Scanner that doesn't exist in the GSA Website Inventory
When Touchpoints runs a recurring a task to read the Site Scanner .json, 
And filter it, and compare records against existing GSA Websites in the Inventory
Then a new Website record is created
And the record does not have a Website Manager

These new records will show up when the Digital Council runs it weekly report.

**Comment by anatecture** [comment]
Do you want to "create new GSA websites based on Site Scanner data" or do you want to create new entries in the GSA Website Inventory based on Site Scanner data?

**Comment by ryanwoldatwork** [comment]
new database records
