### ISSUE TITLE
Reconciling People and Domains: A Manual, Arduous Task

### ISSUE THREAD

**Issue by anatecture** [GSA/EDX#631]
## Summary

This is a write up of crit led by @gailsprinkle and @mvogelgesang week of Dec 5, 2022. 

## The issue
Each month, Gail and Mark have to reconcile the people who have joined and left GSA with the list of website managers in the Touchpoints Inventory. The process looks like [this figma process board](https://www.figma.com/file/x8cosZGrEfKL612DpgTRRi/Updated-PDs%3A-Monthly-Workflowv?node-id=0%3A1&t=J6tEvLZ3Ly0hPuMj-0). 

This process exists because three variables are in play: 

1. User-maintained domain list in Inventory
2. User-maintained manager list in Inventory 
3. HR-generated People list

Please review [this sketch ](https://www.figma.com/file/cE5h21zXsTGZxWZ6AwLjvu/Updated-PDs%3A-Collision-and-Proposed-solve?node-id=102%3A67&t=nStyAIJiHixkkZ7g-0)for details. 

Known change triggers, inconsistently tracked: 
1. Supervisor leaves
2. Bargaining unit changes
3. Person leaves (tracked)
4. Person changes series 
5. Person changes roles 

We cannot seem to resolve the conflicts into a solution, so we have to distribute the maleffects of this conflict. Current, 3-part solution: 

1. Try to **automate** as much of the monthly process as possible. 
6. Work w/ CT and OHRM to find a permanent home for PD updates plus reach out to OPM to **find a series these PDs can fall under.** 
7. **Use Digital Council members:** Brief DC on People changes each month, and ask for help finding supervisors and having conversations about about website management assignments, necessary PD changes, and website manager training. 

Open question @mvogelgesang: could we pull a domain list more usefully from another, authoritative source, like a DNS list, to control for variable (1)? Or is the Inventory the most authoritative source organized in the way we need it to be, ie, websites organized by service function?

**Comment by anatecture** [comment]
12/09: Briefed CT on need to talk w/ OMB and OHRM to move parts of this along

**Comment by anatecture** [comment]
@AKM399 will help @gailsprinkle automate the rote tasks of stripping out sensitive HR info from primary People pull each month

**Comment by ryanwoldatwork** [comment]
Security sends out an email to System Owners each month with emails for folks who leave.

I'd like to see guidance around each system processing these files, including:

1. identifying records in a system that are somehow assigned to an email
2. notifying *some* contact in the agency in order to have them re-assign the records.

#### Example Scenario

If ben.franklin@example.gov leaves the org, and he's assigned to 2 websites in Touchpoints, Touchpoints would:

1. deactivate the account
2. identify the (2) records assigned to the user
3. contact somebody (who needs to be identified) in the example.gov agency to re-assign the records to active owners

I'd recommend connecting with GSA IT (or any IT department) regarding what the "hooks" look like when a user offboards, because Laptops and Logins, etc. are handled as part of the existing offboarding processes.

**Comment by anatecture** [comment]
Note: this issue trips us up even to the granularity of the Website eval sprint planning and tracking. Must solve.

**Comment by ryanwoldatwork** [comment]
Touchpoints can provide a list of users included in the Separations List who are attached to Website records to other users in the org (eg: HR/Gail). Would this be desirable?

System owners are already involved in a process regarding users who leave the org, via the Separations List. 

I'm hoping to establish/support an agency-wide business process to identify users related to Digital Assets (database records), to extend the existing business in such a way that should address this type of problem (users who leave but are attached to records) for all systems.

**Comment by mvogelgesang** [comment]
@ryanwoldatwork that would be a great way to go about it- especially as it would connect to the management of other digital assets.

**Comment by AKM399** [comment]
Tool created by @jacksonmoody - in testing - https://docs.google.com/spreadsheets/d/1dSVvJnfg5rCig_7I7b-Sz6oapPzVQDxguJ84iS5SyiQ/edit?usp=sharing

**Comment by AKM399** [comment]
- [ ] Monthly updates - prove it works
- [ ] update slide deck report and send out to chiefs of staff and executive resources
