### ISSUE TITLE
DC - PDFs

### ISSUE THREAD

**Issue by mvogelgesang** [GSA/EDX#632]
PDFs are all over GSA websites and can cause a variety of issues for users from accessibility to search engine optimization. Some questions and ideas:

- Should we take an HTML-first stance when it comes to content?
- What pre-conceived notions are there about PDFs today that make them so prevalent?
  - Is this related to the speed at which they can be published?
  - Related to an individual's desire to organize a document just so?
  - "PDF's are static and can't be edited"
  - Printing the webpage to PDF results in poor outputs
- When are PDF's appropriate?
  - Signed memo's?
  - Long form reports?
  - Guideline documents? Thinking specifically about security directives
- Have other agencies taken an HTML first approach?
  - EPA, https://www.epa.gov/web-policies-and-procedures/web-standard-pdf-accessibility-requirements

**Comment by AKM399** [comment]
issue being confronted by content team.  Potential DC project.

**Comment by AKM399** [comment]
most likely addressed in web policy.  Its an OSC job.
