### ISSUE TITLE
Contractorpayroll.gov

### ISSUE THREAD

**Issue by anatecture** [GSA/EDX#633]
## Summary

Issue for the ongoing conversations w/ the contractorpayroll.gov team. Team is encountering a lot of pushback in trying to get this system stood up. Please see the [v1 project diagram](https://www.figma.com/file/7g63bip0mTqHceAbfKH0rE/Contractorpayroll.gov?node-id=0%3A1&t=8GTFDr4N6SNjUK8r-0) and the [DLP Proposal phase](https://docs.google.com/document/d/1ZQz7Y53Q4ZMfVrazZcEdSgddjc6DNcwlQOWXbo-557Q/edit).

**Comment by AKM399** [comment]
@AKM399 follow up due

**Comment by AKM399** [comment]
still standing issue

**Comment by RachelF** [comment]
Recommend closing this as it's unclear whether the team ever received funding for this site/project @anatecture thoughts?
