### ISSUE TITLE
OMB websites

### ISSUE THREAD

**Issue by RachelF** [GSA/EDX#634]
## List of OMB websites supported by MY

Close the loop w/OGP / OMB on OMB websites supported by GSA.

## Additional context and links

[List of sites with updates provided by OGP/MY](https://docs.google.com/document/d/1gFyxT30_zvMFVUe8gHqu9GEUKYdAEoCPonbzFRfFlcA/edit#)

## Checklist

- [x] check in w/MY on timeline for sites that are supposed to be moving off of cio.gov domain
- [ ] check in w/TMF PMO on tmf.cio.gov

**Comment by anatecture** [comment]
Action items from meeting 1/17:

1. reach out to Grey re: cio.gov (no footer; no branding; who's site is this?) @AKM399 
2. reach out to Lisa Chung re: [Techfarhub.cio.gov](http://techfarhub.cio.gov/) @RachelF

**Comment by RachelF** [comment]
emailed Lisa today, copied OGP

**Comment by RachelF** [comment]
techfarhub.cio.gov/ now redirects to https://techfarhub.usds.gov/; updated touchpoints to designate this as a redirect

**Comment by AKM399** [comment]
@RachelF sites moved to external.  Issue maintained for reference.
