### ISSUE TITLE
Mobile Friendliness

### ISSUE THREAD

**Issue by mvogelgesang** [GSA/EDX#635]
## Summary

deeper research around a principled approach to define mobile friendliness. A human-centered look at mobile friendliness. This has a DEIA angle as it affects folks who's primary means of accessing the internet is a mobile device.

Issue spun out of #132

**Comment by AKM399** [comment]
combine with documentation for website evals.  Potential with lighthouse mobile scoring.

**Comment by AKM399** [comment]
also gets largely solved with getting people to use USWDS.

**Comment by AKM399** [comment]
potential USWDS collaboration?

**Comment by AKM399** [comment]
good job for USWDS.
