### ISSUE TITLE
Websites to consider for consolidation

### ISSUE THREAD

**Issue by ryanwoldatwork** [GSA/EDX#64]
[Websites](https://touchpoints.app.cloud.gov/admin/websites) are labeled as:
* candidate-for-decommission (for TTS sites)
* edx-candidate-for-decommission (for EDX sites)

#### References

* https://cpsearch.fas.gsa.gov/cpsearch/search.do more details: https://github.com/GSA/EDX/issues/95
* TTS [maintains a spreadsheet](https://docs.google.com/spreadsheets/d/1EGgQpwq8kc43TuTYxtQAhzEnhf_p7m_6T0Q8Dt9mqjo/edit#gid=1916305098)
* [TTS Decision tree for required sites](https://docs.google.com/drawings/d/1LxsHCXHBc09u-H6FDD_C4_pj8rtdRKqgXWZixvEbcD4/edit)
* [TTS Decision tree for non-required sites](https://docs.google.com/drawings/d/1Bi2LTO6ANzcoTd_16tFZq8rL6A3SSXSLS2zgtielGK4/edit)

**Comment by hatfieldjm4** [comment]
Additional websites to consider, just based on my cursory review: 
- reporting.gov
- wdolhome.sam.gov
- wdol.gov
- fbohome.sam.gov
- 1.usa.gov

**Comment by ryanwoldatwork** [comment]
A proposed flow

![Screen Shot 2021-10-04 at 3 14 53 PM](https://user-images.githubusercontent.com/64987852/135932061-3a14b374-851f-40df-86a0-e277680ef30d.png)

**Comment by ryanwoldatwork** [comment]
Flagging a site for decommission should happen by the Website Manager.

The decision to decommission a website is a decision made based on a number of factors, including the cost of maintenance, which is informed by the amount of work applicable for a specific site. That work should be represented in a backlog, eg: USWDS updates or Search.

**Comment by anatecture** [comment]
> agile.18f.gov was flagged for consolidation. This site has [25 open issues](https://github.com/18F/agile/issues).
> 
> Are backlogs been factored into decisions around keeping websites online or not?

I believe they should be. This content almost certainly needs to live in another place, though. Do we want to use this as a test run for collaborating with TTS on decommissioning-with-content-reallocation? I'd be happy to lead that if we get some agreements in this thread.

**Comment by ryanwoldatwork** [comment]
Websites can be `tagged` in Touchpoints, then reported on by the Digital Council.

![Screen Shot 2021-10-29 at 1 13 50 PM](https://user-images.githubusercontent.com/64987852/139496286-bc4d8dcc-d833-4e26-a705-fb838e7052a6.png)

**Comment by AKM399** [comment]
@RachelF we have a list of sites tagged.   Can we get an issue acting on that list to the DC,  define process and first run through of executing on it.

**Comment by ryanwoldatwork** [comment]
As next steps for this card:

* [ ] for every [website](https://touchpoints.app.cloud.gov/admin/websites) tagged with `edx-candidate-for-decommission`, update the `Notes` field with default text below, the update the notes.
* [ ] after updating a website in Touchpoints with the rationale, send the website manager a customized [email](https://docs.google.com/document/d/16SjiCv0_Ch6RgtqH2UlhDBu0gxbrr1xhGDNmtTZAZ90/edit)
* [ ] ensure any work related to Web Modernization is captured in the product's backlog, or in [WG Issues](https://github.com/GSA/wg-web-modernization/issues). If a website product doesn't have a backlog, that should be a new issue.

```
Notes regarding decommission

And type your notes here
```

**Comment by monicas-d** [comment]
Gail and I drafted some questions that can be reviewed for these website manager interviews:
https://docs.google.com/document/d/1ngmymUcdorlz2uQ2UZC-mlqm-v5TvIVxhh_gWXT9sYw/edit

Please review and let us know your thoughts. Thanks! @anatecture @ryanwoldatwork

**Comment by RachelF** [comment]
Can we add tech.gsa.gov to the list? Appears to be targeted to an internal GSA audience.

**Comment by anatecture** [comment]
Moving this to icebox until we figure out how to plug into TTS' process more fluidly.

**Comment by ryanwoldatwork** [comment]
Gray is a good contact here.
