### ISSUE TITLE
Non-Compliant Websites

### ISSUE THREAD

**Issue by mvogelgesang** [GSA/EDX#660]
## Summary

Produce a summary report of websites that meet one or more of the following criteria:
- **No Clear Manager** - websites in which attempts to identify an owner have proven unsuccessful. Domains on this list are those in which discussions with the previously identified website manager and their supervisor have not reached a conclusion after multiple attempts.
- **No Feedback Mechanism** - List of websites in which a feedback mechanism (phone, email, webform) are not present on the home page.
- **Sunset** - List of websites in which the EDX/ Digital Council was told that the site was going away or being folded into another site. Domains that turn into headless redirects are considered sunset.

🔒 [Sheet](https://docs.google.com/spreadsheets/d/1KvXla3SIUjSpvQ-4JOIp9pTKEj-lHNgg130zIIUU_dU/edit#gid=0)

**Comment by anatecture** [comment]
[List complete](https://docs.google.com/spreadsheets/d/1KvXla3SIUjSpvQ-4JOIp9pTKEj-lHNgg130zIIUU_dU/edit#gid=75029659)
