### ISSUE TITLE
Scan for number of PDF's on a given website

### ISSUE THREAD

**Issue by mvogelgesang** [GSA/EDX#667]
## Summary

How many PDF or other files are attached to a website?

## Additional context and links

TTS Site Scanner captures information about PDF's by way of sitemap.xml. If the site does not contain a sitemap.xml though, the data is not gathered. 

This could enable us (or another group) to wrap our arms around the issue a bit more and start to make headway on decreasing the number of PDFs.

**Comment by anatecture** [comment]
Out of scope. OSC possible.
