### ISSUE TITLE
GEAR <--> D2D

### ISSUE THREAD

**Issue by anatecture** [GSA/EDX#668]
## Summary

As a senior leader, I would like to see the data for the websites in my portfolio in an aggregated manner and in comparison to one another. This data is currently awaiting deployment in GEAR 3; I would like to see it in D2D. 

## Design question
How might we make the website eval data, at the very least the trivial pursuit charts, in GEAR show up to users in D2D?

**Comment by hatfieldjm4** [comment]
Just curious, what is the reason you would want to see the websites data in D2D? Is the purpose to provide data practitioners with access to use in any D2D dashboard they may have? If so, what dashboard in particular did you have in mind? Conversely, they may be able to use GEAR's API for websites. 

Happy to meet to talk through this-- thank you!

**Comment by anatecture** [comment]
A few months ago Camille suggested she would like to see the data in D2D, since that's where senior leaders go to see dashboards. That requests was somewhat alluded to by robin independently as well. I would like to make our data fully visible to leaders, of course, and in the easiest possible way, hence the desire to use a platform they already use. Will it be hard? I'm totally willing to understand that this could be super hard and we might need to do some thinking on it.

**Comment by hatfieldjm4** [comment]
I know we spoke a bit about this at our meeting last week, but if it's okay with you, I think we should talk about this a little more as a group to understand what the need is that GEAR wouldn't be providing. If we did go the D2D route, would we maintain the data on the two different systems or would we decom the D2D dashboard when GEAR went live? Would it be confusing to users to have two sources of (I'm assuming) the same data? Or would it be different data on each?

**Comment by AKM399** [comment]
closing.
