### ISSUE TITLE
Update customer-centricity scores in airtable

### ISSUE THREAD

**Issue by mvogelgesang** [GSA/EDX#673]
## Summary

The following sites lack customer centricity scores:

### Sprint 4

- [x] cpars.gov
- [x] cpsearch.fas.gsa.gov
- [x] d2d.gsa.gov
- [x] data.gov
- [x] datacenters.cio.gov
- [x] designsystem.digital.gov
- [x] developers.login.gov
- [x] devicepki.idmanagement.gov
- [x] digital.gov
- [x] digitaldashboard.gov
- [x] disposal.gsa.gov

### Sprint 5

- [ ] fapiis.gov
- [ ] eoffer.gsa.gov
- [ ] sam.gov/content/home
- [ ] facadatabase.gov
- [ ] fai.gov
- [ ] gsa.gov
- [ ] gsaadvantage.gov
- [ ] drivethru.gsa.gov
- [ ] str.gsa.gov
- [ ] ebuy.gsa.gov
- [ ] fsd.gov
- [ ] engineering.18f.gov
- [ ] gsaauctions.gov
- [ ] esrs.gov
- [ ] federalist-builder.18f.gov
- [ ] property.reporting.gov
- [ ] eng-hiring.18f.gov
- [ ] federalist.18f.gov
- [ ] regulations.gov
- [ ] reginfo.gov
- [ ] apps.ocfo.gsa.gov
- [ ] api.data.gov

### 2023

- [ ] ffms.fas.gsa.gov
- [ ] fleet.gsa.gov
- [ ] arm.fas.gsa.gov
- [ ] amp.fas.gsa.gov
- [ ] autochoice.fas.gsa.gov
- [ ] gsac0.fas.gsa.gov
- [ ] vehiclestd.fas.gsa.gov
- [ ] afadvantage.gov
- [ ] dhsadvantage.gsa.gov
- [ ] gsaelibrary.gsa.gov
- [ ] gsaglobalsupply.gsa.gov
- [ ] usmcservmart.gsa.gov
- [ ] fpds.gov
- [ ] fsrs.gov
- [ ] fbohome.sam.gov
- [ ] wdolhome.sam.gov
- [ ] gsaxcess.gov
- [ ] gsaxcesspractice.fas.gsa.gov
- [ ] mysales.fas.gsa.gov
- [ ] realestatesales.gov
- [ ] plainlanguage.gov
- [ ] pra.digital.gov
- [ ] design.login.gov
- [ ] login.gov
- [ ] partners.login.gov
- [ ] resources.data.gov
- [ ] strategy.data.gov
- [ ] tech.gsa.gov
- [ ] open.gsa.gov
- [ ] finance.ocfo.gsa.gov
- [ ] financeweb.gsa.gov
- [ ] handbook.tts.gsa.gov
- [ ] join.tts.gsa.gov
- [ ] vote.gov
- [ ] go.usa.gov
- [ ] smartpay.gsa.gov
- [ ] training.smartpay.gsa.gov
- [ ] reporting.gov
- [ ] fairs.reporting.gov
- [ ] ret.gsa.gov

**Comment by AKM399** [comment]
fully updated
