### ISSUE TITLE
Testing DLP How-To Elements

### ISSUE THREAD

**Issue by anatecture** [GSA/EDX#683]
## Summary

Testing DLP elements started as a [2022 Fall Project](https://drive.google.com/drive/folders/1glfquLKqxRCGemWkbDomWekEMJi_sF9d). 

First element to test: Trust. Find [supporting project documents in gDrive](https://drive.google.com/drive/folders/1kBQXbRNQiPdxWIXFFjQLuy81V33PkPsE?usp=share_link).

**Comment by RachelF** [comment]
Met w/Camille and Liz today to talk thru next steps. Need to identify web managers to interview.

**Comment by RachelF** [comment]
Updated checklists to add "how-to" guidance for each policy req. Shared w/DC and SMEs for input. Launching v2 of checklists by June 1.
