### ISSUE TITLE
Draft new Order to update 2140.2 Management of GSA's Digital Presence

### ISSUE THREAD

**Issue by mvogelgesang** [GSA/EDX#7]
## Summary

[2140.2](https://www.gsa.gov/directives-library/management-of-gsas-digital-presence-21402-osc) has not been updated in almost 3 years and could use some revisions.

## Additional context and links

Working Copy, [2140.2 Working Copy 🔒 ](https://docs.google.com/document/d/1KrrDGhyQJsWblSstD96T_Il_Qnw4hVEOIXIV9vDZr7o/edit#heading=h.r2tt3alnuwhd)

## Checklist

List below the specific actions to be taken

- [x] EDX team to review and draft updated language for the Order
- [x] EDX and OSC (Sarah) scheduled to meet on 9/16 to review and discuss any remaining steps needed to finalize a new Order
- [x] OSC leadership sign off on the updated draft 9/30
- [x] draft routed to CIO for sign-off 
- [x] A-Suite (Jacky Chang) review and sign-off 10/22
- [x] updated Order submitted into GSA directives approval system
- [ ] finalize a new Order

**Comment by anatecture** [comment]
Do you want me to help out with this?

**Comment by ryanwoldatwork** [comment]
any updates?

**Comment by RachelF** [comment]
EDX team has reviewed and drafted updated language for the Order. EDX and OSC (Sarah) scheduled to meet on 9/16 to review and discuss any remaining steps needed to finalize a new Order.

**Comment by ryanwoldatwork** [comment]
@RachelF, @anatecture - any updates here from the 9/16 meeting?

**Comment by RachelF** [comment]
EDX team met w/Sarah on 9/20 to review. New draft has been finalized and Sarah is socializing w/in OSC.

**Comment by RachelF** [comment]
Sarah has gained buy-in from OSC leadership; draft is now with CIO for final sign-off, then Sarah will submit into the directives processing system

**Comment by RachelF** [comment]
@anatecture @RachelF and Peter L worked w/Sarah B to adjudicate all comments and submit them, to close out CDT. New Order should be published shortly.
