### ISSUE TITLE
2023 sprint 2 - tech.gsa.gov

### ISSUE THREAD

**Issue by AKM399** [GSA/EDX#706]
Website Evaluation of (site) - (Site manager)
**To Do**
- [x] Set appointment
- [x] assigned people
**Progress**
- [x] Scan
- [x] [ interview notes](https://docs.google.com/document/d/1QLJ8vFz4wnTrfRCRRKwL3iVNB-8pfpdmoJyPK_-quRY/edit?usp=share_link)
- [x] [Interview Spreadsheet](https://docs.google.com/spreadsheets/d/1agZ0llkXlm263CkpblUyZLYzxt14fe_yjPwUXn_ViHI/edit?usp=share_link)
**Rec Docs Needed**
- [ ] Summary
- [ ] Tl:Dr
- [ ] immediate action
**Done** 
- [x] [analysis](https://docs.google.com/spreadsheets/d/1b9sYMarwL86yBZuoNr4g4UOjpotMFgbdINEEZV3R9ws/edit?usp=share_link)
- [ ] [recc link](https://docs.google.com/document/d/1iIDvKAyZA0ZciHdzIekCB8GV90PSy6ehJ9mLwGb6lgs/edit?usp=share_link)

**Comment by RachelF** [comment]
Interview conducted today

**Comment by RachelF** [comment]
duplicate of issue #763; @AKM399 recommended deleting this one
