### ISSUE TITLE
2023 sprint 2 - financeweb.gsa.gov

### ISSUE THREAD

**Issue by AKM399** [GSA/EDX#708]
Website Evaluation of (site) - (Site manager)
**To Do**
- [ ] Set appointment
- [ ] assigned people
**Progress**
- [ ] Scan
- [ ] interview notes
- [ ] Interview Spreadsheet
**Rec Docs Needed**
- [ ] Summary
- [ ] Tl:Dr
- [ ] immediate action
**Done** 
- [ ] [Analysis 
](https://docs.google.com/spreadsheets/d/133YkCn8UEUj9gJQaQf-sQ5uzAZFVyS1HK1LCVfhMBM4/edit?usp=share_link)
- [ ] [recc link](https://docs.google.com/document/d/1_sXaOl0aSVNnoFtJtSUdWxbT5mXz_yh-UIxF-Wh_YTg/edit?usp=share_link)

**Comment by beharti** [comment]
5/8/2024 
@gailsprinkle follow-up to website manager - site shows decommissioned in Touchpoints, but needs a 301 redirect in place.
Website manager contacted tech team and Trung to learn redirect was in place for 3 months; searching for directives to id a timeframe for this action. Stated redirect was only in place during decommissioning and information was moved to insite and finance page.

@RachelF & @beharti reached out to offer additional support, suggesting to elevate the matter with IT and recommending not to recreate site to initiate the redirect, and to refer to these articles on redirects:
[1- Semrush/Redirects](https://www.semrush.com/blog/redirects/)
[2- MOZ/redirection](https://moz.com/learn/seo/redirection)
