### ISSUE TITLE
Multi Site Manager EPIC - Peter Nguyen

### ISSUE THREAD

**Issue by AKM399** [GSA/EDX#710]
- [x] #708 
- [x] #709 

- [ ] [interview](https://docs.google.com/document/d/19QHnvWXag9wNJU50s-vsCTEE1LZi9bVj-AXXTugxLJE/edit?usp=share_link)
- [ ] [Interview Coding](https://docs.google.com/spreadsheets/d/1wZxB2gVz2gOztSRgVXZyzuL5xyIKV96qBcKZ3g-Vw9w/edit?usp=share_link)

**Comment by mvogelgesang** [comment]
@AKM399 Jen has moved into ID, Peter Nguyen has taken over her role
