### ISSUE TITLE
2023 sprint 2 - handbook.tts.gsa.gov

### ISSUE THREAD

**Issue by AKM399** [GSA/EDX#712]
Website Evaluation of (site) - (Site manager)
**To Do**
- [x] Set appointment
- [x] assigned people
**Progress**
- [x] Scan
- [x] [interview notes](https://docs.google.com/document/d/18izxz3N2Gz5seJXjd-LqUdroaM9Fmp0fxUoOZ1NUs64/edit?usp=share_link)
- [x] [Interview Spreadsheet](https://docs.google.com/spreadsheets/d/1c2dX9SUOTfqz_zOkNcjAsmbfKe8XM8I8hfZIGg1HEzU/edit?usp=share_link)
**Rec Docs Needed**
- [ ] Summary
- [ ] Tl:Dr
- [x] immediate action
**Done** 
- [x] [Analysis](https://docs.google.com/spreadsheets/d/1wM5au5Sv9-5tO6hzFMXSUOIjRFMNiEsPFsGnf5eyq3s/edit?usp=share_link)
- [x] [recc link](https://docs.google.com/document/d/1kZKtUL2G2umH7vMtgK0BajPV_neZ3U9qrWZFjM5csFM/edit?usp=share_link)

**Comment by RachelF** [comment]
Interview completed 2/3
