### ISSUE TITLE
Create an EDX page on InSite

### ISSUE THREAD

**Issue by RachelF** [GSA/EDX#72]
## Summary

Create a page for InSite that describes EDX, and the work of the team.

As a GSA employee
I want to find information about the EDX Team
So I can understand what they do

## Additional context and links

[Draft content](https://docs.google.com/document/d/1Mxo0uRDGLZlbrGdFpVKMcCbMV4f7S_sJYpDQMmseCX0/edit#heading=h.sthbrcpfn96s)

## Checklist

List below the specific actions to be taken

- [x] Draft v1 of page (Monica, Rachel, Gail, Patricia)
- [x] Determine process to publish (Rachel, Patricia)
- [ ] Page review and sign-off (Ana)
- [ ] Page review and sign-off (Ed)
- [ ] Submit to OSC for publication (Rachel)
- [ ] Confirm page is published (Rachel)

**Comment by monicas-d** [comment]
Hey, thanks for assigning me to the 72 issue, @Rachel Flagg - M1ED . That
is a duplication though of issue 46, no?
https://github.com/GSA/EDX/issues/46


-- 

U.S. General Services Administration

*Monica Suber-Duffy*, GCDF <http://www.cce-global.org/GCDF> and Federal
Internal Coach
<https://insite.gsa.gov/topics/training-and-development/developmental-services/coaching-services>

Organizational Development Consultant
<https://insite.gsa.gov/topics/training-and-development/developmental-services/organizational-development>

GSA  | OHRM Talent Development

Pronouns: She/Her/Hers

Office of Human Resources Management (OHRM)

1800 F St, NW

Washington, DC 20526

Mobile: (202) 701-8197

E-mail: ***@***.***

Join the Yoga & Mindfulness Chatter Group
<https://gsa.my.salesforce.com/_ui/core/chatter/groups/GroupProfilePage?g=0F9t0000000aU0i>,
and see our page on InSite
<https://insite.gsa.gov/topics/training-and-development/continuous-learning/yoga-mindfulness>

Between stimulus and response there is a space. In that space is our power
to choose our response. In that response lies our growth and our
freedom.-Viktor
E. Frankl

<https://insite.gsa.gov/topics/hr-pay-and-leave>

**Comment by RachelF** [comment]
Duplicate issue, closing
