### ISSUE TITLE
Mark's Spring Project

### ISSUE THREAD

**Issue by mvogelgesang** [GSA/EDX#721]
## Summary

A task of tasks outlining the major work to be done in Spring 23.

## January

- [ ] Rails Training, modules 1-4, 6

## February

- [ ] Rails Training, modules 5,7

## March

- [ ] Ongoing Trusted Tester Training

## CLI Work

- [x] #659 & #522 
- [x] #630 
- [x] #693 
- [x] #587 
- [ ] #616

**Comment by AKM399** [comment]
@hursey013

**Comment by AKM399** [comment]
overcome by  the event of leaving
