### ISSUE TITLE
Develop Google Lighthouse Plugin

### ISSUE THREAD

**Issue by mvogelgesang** [GSA/EDX#722]
## Summary

Lighthouse has the ability to produce [plugins](https://github.com/GoogleChrome/lighthouse/blob/main/docs/plugins.md) and thereby extend Lighthouse CI. Migrating our existing IT Performance Measure scans into Lighthouse would enable teams to develop CI routines that ensure compliance/ passing scores. The plugin could be updated over time and versioned just in the same way that the existing EDXCLI is. 

Potential for this to be folded into #730 

## Additional context and links

At this time, the example plugin throws an ESM error upon execution. This seems to be fixed by https://github.com/GoogleChrome/lighthouse/issues/12689 but a new Lighthouse release is needed first. Will try building from lighthouse main

## Checklist

List below the specific actions to be taken

- [ ] item 1
- [ ] item 2

**Comment by AKM399** [comment]
OBE by chrome extension
