### ISSUE TITLE
go.usa

### ISSUE THREAD

**Issue by anatecture** [GSA/EDX#724]
## Summary

**Current state:** Page is not compliant in any way.

**Desired outcome:** Sunset page.  

**Barrier to that outcome:** manager points to its use in social media and forms. Our answer: that page can be a redirect, and the service can remain. 

**Hypothesis:** Manager thinks we're asking to sunset the whole service, but we just want the site down. 

**Path Forward**: Draw a process map for manager, present it to him with argument to sunset. Need to work through this. @mvogelgesang @AKM399

**Comment by AKM399** [comment]
this also gets bundled in with 1.usa.gov.  Similar URL shortner that was decommissioned 5 or 6 years ago.

**Comment by AKM399** [comment]
emailed beginning february, haven't heard since.

**Comment by AKM399** [comment]
#732 potential to chart sites going down, sites we recommend going down

**Comment by AKM399** [comment]
@anatecture @RachelF Usa.gov isn't budging on this, should i close the issue?

**Comment by RachelF** [comment]
Are we sure we've clearly articulated the ask? Would love to know why the "redirect" option will not work for them before we close this.

**Comment by AKM399** [comment]
i  believe url exists in IRS forms?  needs confirmation.

**Comment by AKM399** [comment]
@anatecture I dont think they want to change this no matter the argument? Close issue?

**Comment by AKM399** [comment]
yeah, its not changing.
