### ISSUE TITLE
2023 planned website sunsets

### ISSUE THREAD

**Issue by anatecture** [GSA/EDX#727]
## Summary

A running list of websites that are slated to sunset: 

1. [wdolhome.sam.gov](http://wdolhome.sam.gov/) - May 2023 - Hermanson manages - going to sam.gov
2. [fbohome.sam.gov](http://fbohome.sam.gov/) - May 2023 - Hermanson manages - going to sam.gov

**Comment by AKM399** [comment]
both sites sunset
