### ISSUE TITLE
Draft performance indicator for 21cIDEA conformance

### ISSUE THREAD

**Issue by RachelF** [GSA/EDX#73]
## Summary

Craft language for potential inclusion in GSA Annual Performance Plan that proposes how to measure:
- Number of public-facing production websites GSA owns or administers for others that conform to 21st Century IDEA standards. (The assessment criteria for website alignment to the 21st Century IDEA are currently being developed by GSA. The Act requires us to assess all our digital services and prioritize those with the highest impact for usability improvements.)

## Additional context and links

This is part of Performance Goal 3.1.1 - Evaluate, rationalize, and modernize GSA websites and solutions to advance standardization among websites across Government

Initial proposal:
- Number (%) of websites that have implemented USWDS banner, identifier, and footer components.

**Comment by ryanwoldatwork** [comment]
cc @mvogelgesang, because Performance indicators

**Comment by ryanwoldatwork** [comment]
I'd suggest a denominator as well; ultimately:

* total sites (same as last reported figure)
* sites updated

This figure should trend toward 100%.
What then? Would the indicator change?

--- 

A precursor to this work might be: 

* [ ] audit sites for USWDS components and provide a report of sites not in compliance
* [ ] ensure non-compliant sites have the work reflected in visible backlogs. then monitor those tasks.

**Comment by RachelF** [comment]
Yes @gailsprinkle , GSA's annual performance plan. The language in the current draft reads "Number of public-facing production websites GSA owns or administers for others that conform to 21st Century IDEA standards." but there was no mention in the plan of how we might measure that, so this card is to work thru some language we can propose to include showing HOW we show compliance. I'm keying off the word "standards" since there is language in the law that requires "compliance with GSA's website standards' - which we've interpreted to mean "adoption of USWDS"

**Comment by RachelF** [comment]
Proposed annual measure:
USWDS version number is identified through automated scanning, and is no more than 3 releases behind most current release; presence of USWDS banner, identifier, and footer components are detected on the site. Data is gathered via an automated process using Site Scanner, and reported via Touchpoints. All public-facing production GSA websites are included.
Submitted [Overview for OMB](https://docs.google.com/presentation/d/1dilcryKKGfvv4TsbPahoBgvBpANacHGotb5Ya4K7aE0/edit#slide=id.g10038ad8ac3_2_12) on 11/16.  Submitted [Performance Measure Definition](https://docs.google.com/spreadsheets/d/1xii5pagb2q838W4y4T8rSmwyI5-QpdEs9kTcUPbMtUI/edit#gid=0) on 11/19.
