### ISSUE TITLE
Continuous Integration Tooling

### ISSUE THREAD

**Issue by mvogelgesang** [GSA/EDX#730]
## Summary

This is an expansion of a project proposal which sought to develop continuous integration tooling to support GSA's digital initiatives and standards while also providing feedback mechanisms for COR's and project managers. 

While a lot has been written about GSA’s visual design standards, accessibility policies, use of USWDS, security, etc, the feedback loops to development teams occur only after work has been “completed”. This results in a higher cost to the government when fixes are requires. A 2002 NIST study found that software bugs and rework substantially grows in cost the further downstream the work ([Figure 5-4](https://www.nist.gov/system/files/documents/director/planning/report02-3.pdf)).

By meeting development teams where they are, in their software development workflows, to provide timely and actionable feedback when it comes to website compliance with laws, policies, and GSA standards. This comes in the form of continuous integration pipelines which run automated tests/ scans of proposed website changes to ensure compliance.

## Support for COR's

COR's supporting IT projects are at a real disadvantage when it comes to measuring contractual compliance. Often times, reviewing code deliverables is outside the skillset of a COR and proxy deliverables are used to assure technical completeness. For instance, the COR might look through a design document that speaks to the feature at a high level. Similarly, a contract might include a Section 508 requirement but the proof of compliance is often flimsy.

Instead, having tools which provide a _more complete_ picture are needed. These come in the form of continuous integration toolsets which can scan for things like accessibility, dead links, passing tests, and even UI standards. This allows a COR (and the developers) instant feedback as to how a deliverable meets the organization-wide spec. 
## Checklist

Actions/ Tasks 

Not in a specific order but to achieve something like this, a number of changes would be required to the current organization of the EDX CLI. An end state may look something like the following:

```mermaid
flowchart TB
    subgraph EDXCLI
    Ruleset1Facet
    end
    subgraph LH CI Plugin
    LHCIFacet1
    end
    subgraph Rulesets
    Ruleset1-->LHCIFacet1
    Ruleset1-->Ruleset1Facet
    Ruleset2
    Ruleset3
    end
```

Individual rulesets are managed as distinct modules. They get pulled into LHCI or EDXCLI as dependencies which enables clear versioning. LHCI and EDXCLI can produce outputs as needed.

- [ ] Read through source from https://github.com/forcedotcom/isvte-sfdx-plugin & reference articles: https://forcedotcom.github.io/isvte-sfdx-plugin/en/architecture/#source-code-and-contribution. Align architecture to follow similar patterns
- [x] #722 
- [ ] #723 
- [x] #583

**Comment by AKM399** [comment]
in intake with leadership team

**Comment by AKM399** [comment]
Notes from github session
Key points - capture issues upstream as they are deployed.  Potential mitigation of "review cycles".  
programming language or tools needed to do this.  - rulesets fire against drupal, Jekyll, etc.  You have to do your software builds from github.
typescript based - build once.  pass or fail and why conditions.  rulesets can be updated over time.  All teams can  share rulesets.
can be referred to contractually.

**Comment by AKM399** [comment]
noted as beneficial to CoRs for Fraud checks.

**Comment by AKM399** [comment]
Open question:  Does this exist?
Answer - there are teams using pieces of tools

**Comment by AKM399** [comment]
would inform daily or hourly feedback loops.  Adds better resolution than website evals - freeing evals open for strategic conversation by providing tactical feedback.

**Comment by AKM399** [comment]
One potential route:  it would be cool if we can get some teams to start using it.  Longer term would be incorporation to websites or writing into policy (not sure how it would work).  GSA would potentially have to write a policy.

**Comment by AKM399** [comment]
open question:  do we want to update it or give it to a team that will take care of it?

service delivery team?  18f group looking at contracting stuff?  508 team in OGP is trying to get people to use ART tool (generates contract language).  Has been a struggle to connect to the cor community. Might be something for tts team?  Gray and site scanner group?  

Or we keep it in house as part of evaluation.

**Comment by AKM399** [comment]
something that is presentable to the federal web council.

there is room to build as just a gsa thing, or it can be built fed wide without too many extra steps.

**Comment by AKM399** [comment]
could obtain partners with section 508 group.

**Comment by AKM399** [comment]
challenge is keeping scope tight.

**Comment by AKM399** [comment]
interest with ryan and detail.  First and foremost a development task.  Some benefit to organizational steps included therein.

**Comment by AKM399** [comment]
@anatecture should we close? OBE by chrome extension.

**Comment by anatecture** [comment]
OBE by chrome extension
