### ISSUE TITLE
EDX chart-of-the-week

### ISSUE THREAD

**Issue by anatecture** [GSA/EDX#732]
## Summary

[Ideas and weekly schedule](https://docs.google.com/spreadsheets/d/1XudOict4YKthx9LF252AKLiOUmiqD7UqYjvOxb9QihI/edit?usp=sharing) for chart production

**Comment by AKM399** [comment]
next charts due.  USDWS components, required links. parent chart.

See about showing progress between scans.

**Comment by AKM399** [comment]
@AKM399 needs new brainstorming session

**Comment by anatecture** [comment]
Ongoing feature. @AKM399 and @anatecture will review all of them in aggregate at offsite. want to see if there's a story or data arc for the EDX initiative therein.

**Comment by anatecture** [comment]
per @RachelF at offsite, might consider a brainstorm session on more aspects of the project to make charts about.

**Comment by anatecture** [comment]
This feature has taken root and process is established. @AKM399 owns.
