### ISSUE TITLE
Uncovering GSA domain names

### ISSUE THREAD

**Issue by mvogelgesang** [GSA/EDX#736]
## Summary

Various ways in which we can find domain names across the GSA enterprise.

- Request DNS report via ServiceNow. Looking for all externally-facing DNS entries, specifically A, AAAA, or CNAME records
- Review list of domains in DAP that register hits and list GSA as the office
- Look for *.gsa.gov (other valid domains listed below) referrers in DAP
- Consume gsa.gov content API, scan body for links and check if the domain is a known domain
- Regularly consume DNS entries out of https://github.com/18F/dns

**Comment by AKM399** [comment]
@anatecture and @mvogelgesang to converse

**Comment by AKM399** [comment]
@hursey013 what do you want to do with this one?

**Comment by anatecture** [comment]
OBE by Site Scanner changes
