### ISSUE TITLE
FY23 HCD Interview - training.smartpay.gsa.gov

### ISSUE THREAD

**Issue by AKM399** [GSA/EDX#738]
Website Evaluation of (site) - (Site manager)
**To Do**
- [x] Set appointment
- [x] assigned people
**Progress**
- [x] Scan
- [x] [interview notes](https://docs.google.com/document/d/1Y48lAt1DSSGQvJG02RUcwS2zkZi-pKE09KziaHnbyR0/edit#heading=h.6kd2t1lw7o4d)
- [x] [Interview Spreadsheet](https://docs.google.com/spreadsheets/d/1OuAE0lQhF0qDNwDCxtmcffz6iuW2Woi9Qnu5-raQup4/edit#gid=0)
**Rec Docs Needed**
- [ ] Summary
- [ ] Tl:Dr
- [ ] immediate action
**Done** 
- [x] [Analytics Package](https://docs.google.com/spreadsheets/d/1spvkZSm8LQsX2H3gSBbYnutuUzkpJ6ELr_CIpfnIt7I/edit?usp=share_link)
- [x] [recc link](https://docs.google.com/document/d/1m9Ypse2avSgrkYaAqLp6Bjjo6DEAKCjJX3UTYO5qXqw/edit#)

**Comment by RachelF** [comment]
@AKM399 report done; tagged for your review. Also see a couple of comments in the doc and LMK if you have questions
