### ISSUE TITLE
Ongoing lessons learned/best practices discussions with FAS DX staff

### ISSUE THREAD

**Issue by monicas-d** [GSA/EDX#74]
Gail and I are meeting with Ryan Williams and Kelly Deao from time to time to learn about FAS DX best practices and lessons learned around change management and comms - "work agile, communicate waterfall"

Goal is to apply some of their best practices where we see it fits for EDX work.

What we have learned is:

- They struggled with the challenges we do around working agile and communicating waterfall. 
- Do the best you can do with what you have and work with key stakeholders to determine the work and the communication.
- When communicating, they found that they would draft a comms and by the time the comms was ready to send out, it needed severely updating cause the work had evolved so much and so fast!
- OVERCOMMUNICATION is key! Communicate UP AND DOWN. Track who’s in your meetings and make sure they communicate up and down (to the best of your ability setting them up for success)! "Can’t have crickets and not communicate, while at same time you have to rely upon people to show up and mitigate that risk"
- Lessons learned: they engaged the Advisory Board too early and thus people felt they weren’t being utilized or we didn’t know what we were doing and the meetings were a waste of time. They also do a sliding scale rating on how they did in leading the meetings or not - that way you have insight on where you’re at feedback loops - after every Advisory Board meeting (2x/quarter)
- As much as you repeat yourself, we found that we have to tell them over and over again to get the message across
- Record your meetings, esp any demos! (We didn’t do closed captioning - we should have done it but we didn’t.)
- Their change resistance: This is MY tool and I don’t want people to take it over! Ownership (not stewardship). We try to direct them to the bigger picture of doing it for the enterprise, our customers, our suppliers, etc.

4/14/21: We met with Ryan
9/30/21: We met with Kelly

Next steps:
As a result of the latest meeting with Kelly, we will also meet with the sam.gov team (Christy Hermansen and Kim Goldman) to hear their lessons learned and promising practices, per Kelly's recommendation since sam.gov team helped them.

**Comment by gailsprinkle** [comment]
@monicas-d Thank you for the great summary!
@ryanwoldatwork  @RachelF  How do we operating in github with this component of research? Do we add the findings from the meeting with the sam.gov team then close this card? Thanks

**Comment by gailsprinkle** [comment]
Apologies, didn't mean to close.

**Comment by ryanwoldatwork** [comment]
Hi @monicas-d, it is common insofar as it a survey; a form with questions.

**Comment by ryanwoldatwork** [comment]
Hi @monicas-d - here is a rundown of how "Pull Requests" work.  

Basically, a Pull Request is asking: _Will you pull my code into your code?_
And because software developers do this a lot and because line-item changes are valuable and important, these code (or text) changes can also require reviews.

https://docs.github.com/en/github/collaborating-with-pull-requests/reviewing-changes-in-pull-requests/about-pull-request-reviews

**Comment by monicas-d** [comment]
Cool. Thanks @Ryan Wold - QQA ***@***.***> .

Anyone else have comments or recommendations? Thanks!


-- 

U.S. General Services Administration

*Monica Suber-Duffy*, GCDF <http://www.cce-global.org/GCDF> and Federal
Internal Coach
<https://insite.gsa.gov/topics/training-and-development/developmental-services/coaching-services>

Organizational Development Consultant
<https://insite.gsa.gov/topics/training-and-development/developmental-services/organizational-development>

GSA  | OHRM Talent Development

Pronouns: She/Her/Hers

Office of Human Resources Management (OHRM)

1800 F St, NW

Washington, DC 20526

Mobile: (202) 701-8197

E-mail: ***@***.***

Join the Yoga & Mindfulness Chatter Group
<https://gsa.my.salesforce.com/_ui/core/chatter/groups/GroupProfilePage?g=0F9t0000000aU0i>,
and see our page on InSite
<https://insite.gsa.gov/topics/training-and-development/continuous-learning/yoga-mindfulness>

Between stimulus and response there is a space. In that space is our power
to choose our response. In that response lies our growth and our
freedom.-Viktor
E. Frankl

<https://insite.gsa.gov/topics/hr-pay-and-leave>
