### ISSUE TITLE
2023 Sprint 2 - ret.gsa.gov

### ISSUE THREAD

**Issue by AKM399** [GSA/EDX#743]
Website Manager - Aaron Henderson
**To Do**
- [x] Set appointment
- [x] assigned people
**Progress**
- [ ] Scan
- [ ] interview notes
- [ ] Interview Spreadsheet
**Rec Docs Needed**
- [ ] Summary
- [ ] Tl:Dr
- [ ] immediate action
**Done** 
- [ ] recc link

**Comment by RachelF** [comment]
@AKM399 I think this is a dup of https://github.com/GSA/EDX/issues/758; if so, it can be deleted
