### ISSUE TITLE
Create first point in Statuscard: is website required by law or policy? 

### ISSUE THREAD

**Issue by anatecture** [GSA/EDX#75]
## Summary

Per the Web Modernization decision tree starting point, two features in Touchpoints: 

(1) Start off the Statuscard entry for all websites with the question "Website is required by law or policy" with yes/no answer as possibility.  (Note, we collected some responses to this question in our 2019 data call; we could import original responses for sites that have already provided this info.)

(2) Provide an open text field for them to link to the relevant law or policy or right their justification.  

## Additional context and links

[Decomissioning decision tree](https://docs.google.com/presentation/d/14kH-Rzsj8jQHLAW5w02McMalavtD8_x8SbQNqcRFkkI/edit#slide=id.g76c16b25b4_5_137) 

In spreadsheet, [Site Info tab, cell A17](https://docs.google.com/spreadsheets/d/1d7l-Zaw7KZUBko3dc1vQ8n0ZaVNOHCNcpSJ-HIS8i_c/edit#gid=433171573
)

**Comment by ryanwoldatwork** [comment]
The field `required_by_law_or_policy` exists on the Website edit screen.

<img width="507" alt="Screen Shot 2021-09-30 at 10 49 43 AM" src="https://user-images.githubusercontent.com/64987852/135505803-2766d0ee-33ca-4c7c-93c2-a53edd0a28ed.png">

**Comment by anatecture** [comment]
Thanks for that note. The current display of this item isn't necessarily its best or permanent one.

**Comment by ryanwoldatwork** [comment]
@anatecture - is there more work to be done here?

While I agree there may be ways to improve this, the goal is to outline them above. Or, this can be revisited in the future.

Did you have a specific experience in mind? Like "Creating a New Website" or having a wizard-like assessment before formally requesting a website?

**Comment by anatecture** [comment]
Issue is superseded by Digital Lifecycle Program intake form.
