### ISSUE TITLE
Website headers service

### ISSUE THREAD

**Issue by mvogelgesang** [GSA/EDX#753]
## Summary

Add module to cli to add http headers output to scan along with ability to capture results in a csv. Headers, redirect hops, etc

## Additional context and links

Add any other context, screenshots, or links to working docs.

## Checklist

List below the specific actions to be taken

- [ ] item 1
- [ ] item 2

**Comment by AKM399** [comment]
@hursey013 is this closable?

**Comment by anatecture** [comment]
OBE
