### ISSUE TITLE
Crit Process

### ISSUE THREAD

**Issue by anatecture** [GSA/EDX#768]
Guidelines for Crit  

**Crit is conversation.** This is the opposite of defense, which is the practice most of us with a liberal arts education learn. In defense, you define your argument, and defend it to people who present evidence and arguments that question your argument's position. In critique, you show others what you've been thinking about and doing and where you think your work is going, and they engage with those positions through conversation. 

**Crit centers on in-process work.** Because crit is conversation and not defense, people bring work that's in process and unfinished to crit. No need to present a deck and definitely no need to bring fully formed thoughts. Ideas at any stage of development are welcome. We will present Digital Ecosystem Goals that the EDX team has developed, but that doesn't mean they're finished; we need your thoughts and input; these goals are in-process.

**Crit starts from a sticking point.** Because crit deals with developing work, the people doing the work outline for the group where they're sort of stuck and where they want help: do they want feedback on a certain part of the work? Are they looking for ways to connect it to other work that's in flight? Are they looking for ideas because they feel blocked or siloed? Do they want a reality check on whether this has all been done before or whether it's feasible? Asks like that are useful to direct the conversation. EDX will be asking you for feedback on each goal, in terms of word usage and cross-functional applicability of these goals throughout GSA. 

**Crit is energetic.** What everyone is looking for is to walk away from crit with more ideas and energy around the work. Sometimes, the people doing the work walk away with more ideas that are a bit confusing or even disheartening, but sometimes those less-fun emotions are part of idea development. 

**Crit is future-facing.** What both the people doing the work and the group should always feel walking away from crit is supported in the work by the greater team. Even if the workers find that the ideas don't have the breadth or latitude they thought they did or they have the less fun emotions mentioned above, crit should feel like a positive investment in their work. If and when it feels like a take-down or a bit of an attack, then that's not proper crit; that's what some orgs call a "murder board", and it's not what we practice. 

**Crit takes practice.** Most of us practice either reporting out or poking holes in ideas every day, and those are useful skills! But we do them so often and we're so good at them that when we're asked to engage with other people's ideas in a constructive and conversational way, it can be hard. Crit takes practice, just like reporting out and poking holes does. It's a way of thinking and talking and relating to your colleagues' work that we don't do that often in our professional lives. So don't worry about it if you're not sure what any of this means; just come to the DC prepared to have a conversation.

For more reading on crit, these are some pithy, useful articles on the practice in application: 

[Four Things Working at Facebook Has Taught Me About Design Critique](https://medium.com/designatmeta/critique-is-an-important-part-of-any-design-process-whether-you-work-as-part-of-a-team-or-solo-ef3dcb299ce3#.i9flr39fc) | by Tanner Christensen
[Moving from Critical Review to Critique](https://archive.uie.com/brainsparks/2011/10/27/moving-from-critical-review-to-critique/) — Archive of UIE/Brainsparks
[How to give designers feedback they can actually use](https://www.invisionapp.com/inside-design/give-designers-feedback/) | Inside Design Blog
[Productive design critique guide](https://www.toptal.com/designers/product-design/productive-design-critique-guide) | Toptal

**Comment by mvogelgesang** [comment]
closed by #779

**Comment by anatecture** [comment]
### suggested question series format for drawing out discussion in crit: 
 
Consider the following guiding questions as you read: 
Does this paper clearly explain the importance of considering complicated factors in policy making other than initial cost?
tightening up this question: 
1st question: information ask: what is the core thesis of this paper?
2nd question: interpretation of that information: what does it tell you? 
3rd: information + interpertation: What does this paper provide in terms of evidence? 
4th: second layer of information + interpretation: Does the argument seem sound? 
5th: ask for idea generation: How might the argument be strengthened?

**Comment by anatecture** [comment]
### How to crit a document (paper, article, rule, bulletin, etc)

Prepare:
Write an outline, document, etc
Create guiding questions for reviewers, for example
Specific questions on specific sections - is this sufficiently explained, is there other evidence to provide,  is there an alternative to consider (especially important for rulemaking), etc
General questions - flow of document, readability/plain language, overall impressions
Avoid proofreading etc in a crit meeting - proofreading is not the best use of group time
Share a view only version of the document with reviewers prior to the meeting. Direct them to make their own copy so they can put their notes in.


During crit
Provide the shared link and directions to make a copy again. 
Give a brief overview of what the document is and what the goal is.
Ask the guiding questions, and also post them in chat.
Give reviewers 10-15 minutes (more or less depending on document size) to read through and make notes. Everyone should be on mute, cameras on or off depending on comfort level.
Bring everyone back together and start going through the document and notes. Give reviewers time and space for questions, thoughts, etc. 
Remind reviewers to share their copies with you.

After
You will not use all of the recommendations in all likelihood. I found it best to download all the copies and combine them into a single word doc (since google doesn’t have this feature worked out yet), and then reupload into gdocs.
Make changes as appropriate
Proofread on your own
Either crit again or send out for final read through. Get someone else to proofread it again.
