### ISSUE TITLE
Analyze different sources of websites data inventory

### ISSUE THREAD

**Issue by hatfieldjm4** [GSA/EDX#77]
I plan to analyze the multiple sources of data for GSA websites in order to identify source/method in obtaining the data, data disagreements, and available data, with the purpose of improving the Touchpoints inventory. 

GSA website data exists on several different systems including: 
- [Site Scanning API](https://digital.gov/guides/site-scanning/data/)
- [Dotgov inventory](https://home.dotgov.gov/data/)
- [Digital Dashboard](https://www.digitaldashboard.gov/myagency_home)
- [AMP - Accessibility Management Platform](https://gsa.levelaccess.us/index.php) (Section 508 team's tool)
- [Archer's URL inventory](https://docs.google.com/spreadsheets/d/1_SyaGq8Dth80_A7O4AdbGKOoOwQG9zyE-vAUNkOFeVc/edit?usp=sharing) (GSA IT Security's repository)
- [Analytics.USA.gov](https://analytics.usa.gov/data/)

**Comment by ryanwoldatwork** [comment]
Interesting work @hatfieldjm4! 

I'm curious which use case is this aiming to address?
And, what type of deliverables do you envision?   eg: Touchpoints can generate a [data model](https://github.com/GSA/touchpoints/wiki/Data-Model)

**Comment by hatfieldjm4** [comment]
Thanks Ryan. 
I want to make sure we're aware of all the data that is already collected in other sources so that we can either add it to Touchpoints if it's not there or compare similar data fields (between Touchpoints and one of the other systems) for data inconsistencies. Examples, 1) DD lists https://accessibility.gov/ as a GSA site, while Touchpoints does not and 2) DD gives evaluation.gov an HTTPS score of 50 but Touchpoints' boolean for the https field is TRUE.

The main deliverable would be increased data quality, which we can represent by the percentage of sites that were edited in some manner (open to suggestions on that). Also I want to make sure that we understand the data as thoroughly as we can before making recommendations to owners so that we're able to defend the data that is fueling future recommendations.  

I like the data model as an output too, as it can help users graphically view how Touchpoints is pulling the data from other sources.

**Comment by ryanwoldatwork** [comment]
Documenting this in a Data Dictionary makes sense, _if_ somebody is empowered to curate and be an effective steward of such a resource.

**Comment by hatfieldjm4** [comment]
> Documenting this in a Data Dictionary makes sense, _if_ somebody is empowered to curate and be an effective steward of such a resource.

I agree. You and I should coordinate such that if a change is made to Touchpoint's schema or data sources, we make the necessary changes to the Data Dictionary.

**Comment by ryanwoldatwork** [comment]
Conceptually that makes sense. The concept of a Data Dictionary needs work, given one doesn't exist at this time.

**Comment by hatfieldjm4** [comment]
You mean the intent of a data dictionary doesn't exist?

**Comment by ryanwoldatwork** [comment]
I'm not aware of a Data Dictionary period. Does one exist as a product? Is it ATO'd? Who's the System Owner?

**Comment by hatfieldjm4** [comment]
I think you're speaking more to an agency-wide, program-agnostic data dictionary if I'm not mistaken. Let's talk more about it at our 11am PT meeting if that works for you?

**Comment by RachelF** [comment]
_Examples, 1) DD lists https://accessibility.gov/ as a GSA site, while Touchpoints does not and 2) DD gives evaluation.gov an HTTPS score of 50 but Touchpoints' boolean for the https field is TRUE._
@hatfieldjm4 there is something goofy w/the dns for accessibility.gov -- it seems to resolve, but that content really lives at https://app.buyaccessible.gov/; accessibility.gov should actually redirect to section508.gov. I can reach out to the 508 team to see if they can fix that.
