### ISSUE TITLE
gsafcu.gsa.gov

### ISSUE THREAD

**Issue by anatecture** [GSA/EDX#772]
## Summary

GSA Federal Credit Union site is hosted by GSA, but the site does not appear in the Digital Registry.  
## Additional context and links

03/02: emailed jerome.malvin@gsa.gov, who submitted a DNS request, to find out the status of this site. Conferred w/ SB in OSC about it. She states that: "This is definitely some murky territory....definitely worth unpacking their relationship with GSA and going from there...And even if not dealing with them, maybe working with IT to craft some language around what entities can use a [gsa.gov](http://gsa.gov/) domain to prevent anything like this happening going forward"

03/02: JM emails back with: 
"This is just a brief history of the website since it has always been a little different.  Many years ago, a former GSA Administrator, along with a SES employee wanted to create a website for GSA credit union and host it on the GSA site. The rationale was to ensure that GSA employees used a safe secure website to conduct financial transactions. GSA credit union offers financial services to all GSA employees and GSA contractors nationwide. About five years ago, we were told that GSA Central Office was moving to some remote servers and could we move the website to another host. GSA still wanted to maintain the DNS, IP address side to continue the elevated protection for GSA employees." 

03/03: email back to figure out who the programmatic responsibility lies with. Will circle w/ SB to have larger philosophical conversation later in spring.

**Comment by anatecture** [comment]
The site is both inside and outside GSA. It's run by "contractors with no contracts", the federal credit union having been established in 1936. 

Asking @mvogelgesang and @anatecture to pull some analytics for the site; asking @gailsprinkle to weigh in from the HR side.

**Comment by AKM399** [comment]
circling with camille and ogc

**Comment by AKM399** [comment]
@AKM399 need to recircle

**Comment by RachelF** [comment]
this site is now in the inventory as "external" but seems as if we should sort out how to move this off GSA's network since it's not a federal site; I don't believe we can legally provide this service to the credit union as it's a private entity (even if it does serve GSA employees) @anatecture @AKM399

**Comment by AKM399** [comment]
being external kills the issue.
