### ISSUE TITLE
2023 evaluation sprint 3 - realestatesales.gov

### ISSUE THREAD

**Issue by AKM399** [GSA/EDX#774]
Website Manager - Laura Scaletti
**To Do**
- [x] Set appointment
- [x] assigned people
**Progress**
- [x] Scan
- [x] [interview notes](https://docs.google.com/document/d/100TDkoSQtie20M_loWRprff_NWYBh1QgRoZp50FrJcs/edit?usp=share_link)
- [x] [Interview Spreadsheet](https://docs.google.com/spreadsheets/d/1Jy2AeP9mE12zXMY3IjXtIXau97Kgn48FljHTmsr32hw/edit?usp=share_link)
**Rec Docs Needed**
- [ ] Summary
- [ ] Tl:Dr
- [x] immediate action - Laura noted "Would be great if there was an annual course for GSA employees on how to make things accessible." Would love to follow up on this idea.
**Done** 
- [x] [Analysis](https://docs.google.com/spreadsheets/d/19ahQzHns0EISO8SBQhj5vfn3diImKAlt71jqZaiKdJQ/edit?usp=share_link)
- [x] [recc link](https://docs.google.com/document/d/1mRTvJPINzKfGOLyEQX4I-ksMrHCVkjIz6-Sg-bQ1gxg/edit?usp=share_link)

**Comment by RachelF** [comment]
reported drafted, tagged @AKM399 for review
