### ISSUE TITLE
Third party quality assurance for a service (or call center)

### ISSUE THREAD

**Issue by ryanwoldatwork** [GSA/EDX#78]
A "secret shopper" service based operationally from CX could be valuable as a way to operationalize consistent flow of feedback while providing some type of check and balance from a user experience perspective.

It is essentially another type of "audit". 
Findings would go in the respective backlog of the product or service under review.

**Comment by ryanwoldatwork** [comment]
Chatted with Sheev.
Something like this was done in the past as a one-off, but it was not formalized.

**Comment by AKM399** [comment]
Problem discovery item - Proposal for executive buy in.   Proposed venue needed - where do we bring this up and sell the idea?

**Comment by ryanwoldatwork** [comment]
Good to icebox for now.
No resourcing for this at this time.

**Comment by ryanwoldatwork** [comment]
Consider building this into general CX staff operations - basically 'hallway testing' for services. [link](https://www.joelonsoftware.com/2000/08/09/the-joel-test-12-steps-to-better-code/)
