### ISSUE TITLE
Evaluation onboarding

### ISSUE THREAD

**Issue by ccollado30** [GSA/EDX#780]
## Summary

I want to shadow @AKM399 so that I can learn the evaluation process and eventually run my own projects.

- [ ] Watch Aaron set up GitHub
- [ ] Watch Aaron setup Google Drive
- [ ] Watch Aaron link interview templates
- [ ] Watch Aaron do evaluation assignments
- [ ] Watch Aaron assign new interviews
- [ ] Watch Aaron send out evaluations
- [ ] Aaron watches me set up GitHub
- [ ] Aaron watches me setup Google Drive
- [ ] Aaron watches me link interview templates
- [ ] Aaron watches me do evaluation assignments
- [ ] Aaron watches me assign new interviews
- [ ] Aaron watches me send out evaluations
- [ ]  set up GitHub
- [ ]  setup Google Drive
- [ ]  link interview templates
- [ ]  Do evaluation assignments
- [ ]  Assign new interviews
- [ ]  Send out evaluations

**Comment by AKM399** [comment]
closed to move new PM into compilation project
