### ISSUE TITLE
Bubble up website data when www and url paths are required

### ISSUE THREAD

**Issue by mvogelgesang** [GSA/EDX#785]
## Summary

A handful of websites at GSA require "www." or a full url path in order to serve a HTTP 200 response. The information about these sites is currently captured in https://github.com/GSA/EDX/blob/main/Tools/edxcli/src/helpers/websites/websites-metadata.ts but that information is not readily accessible to the broader team. How might we make that information easier to find?

## Additional context and links

There is a larger issue which should be tackled separately- namely, going to a domain (without www prefix or URL path) should properly redirect users. 

## Checklist

List below the specific actions to be taken

- [ ] item 1
- [ ] item 2

**Comment by AKM399** [comment]
@hursey013

**Comment by anatecture** [comment]
obe
