### ISSUE TITLE
Schedule team rituals in 2 week cadences

### ISSUE THREAD

**Issue by ryanwoldatwork** [GSA/EDX#79]
* [ ] planning - day 1
* [ ] review - last day
* [ ] retro - last day
* [ ] grooming (recurring and ad-hoc)

**Comment by ryanwoldatwork** [comment]
I sent Aaron an invite for next Thursday.
If that time works for him, add the remainder of the team as optional.

**Comment by AKM399** [comment]
Document for rules of road is under review by @anatecture Ana  https://docs.google.com/document/d/1FDN51UrairwQFe5Zxa4gGqxyDJUUVQ0epeLD-Hv54dU/edit?usp=sharing

**Comment by AKM399** [comment]
target date, every other Thursday beginning on October 21st.  Edits to rules of road up to 20th.

**Comment by anatecture** [comment]
complete. closing.
