### ISSUE TITLE
CLI - Capture which languages aare offered for a site

### ISSUE THREAD

**Issue by mvogelgesang** [GSA/EDX#790]
## Summary

Review list of languages included in USWDS Language picker on the page and capture this information in a report.

## Checklist

- [ ] create new report type for languages
- [ ] build out functionality to scan for presence of USWDS language picker and capture list of languages offered
- [ ] Review results of sites that have languages offered, see if there are common patterns in terms of how the language is presented. Ideally sites are denoting language codes within the markup - that may be the clearest way to capture this information. See if there are ways to organize this information into a common format. A couple of examples are below:
<img width="145" alt="login.gov language selection showing English, Español, Français" src="https://user-images.githubusercontent.com/4053083/227952623-460e5629-198f-4504-806b-5a2bc9fc063c.png">
<img width="250" alt="vote.gov language selection showing English,Español (Spanish),বাংলা (Bengali),中文 (Chinese - Simplified),繁體中文 (Chinese - Traditional),हिन्दी (Hindi),ភាសាខ្មែរ (Khmer),한국어 (Korean),Diné (Navajo),Tagalog,Tiếng Việt (Vietnamese), Yup'ik " src="https://user-images.githubusercontent.com/4053083/227953024-e1cd6d47-7108-46bc-b744-395fb7701b87.png">

**Comment by anatecture** [comment]
we're not pursuing
