### ISSUE TITLE
2023 website evaluation - mobile.reginfo.gov

### ISSUE THREAD

**Issue by AKM399** [GSA/EDX#796]
Website Manager - Elizabeth Harris - Marshall
**To Do**
- [x] Set appointment
- [x] assigned people
**Progress**
- [x] Scan
- [x] [interview notes](https://docs.google.com/document/d/1C2aaXj6ivsX4aUfwttWZuleUte6ltaNbo9ElcYNw3NQ/edit?usp=share_link)
- [x] [Interview Spreadsheet](https://docs.google.com/spreadsheets/d/1enSNJsPNycuAKyM3FbRZHr8fbPBh-s32PEyv5pYoV-0/edit?usp=share_link)
**Rec Docs Needed**
- [ ] Summary
- [ ] Tl:Dr
- [ ] immediate action
**Done** 
- [x] [Analysis](https://docs.google.com/spreadsheets/d/1h2w7YMiuxhEvsZ7fYNvomNDlBfIa41GUjHl08wgGrt8/edit?usp=share_link)
- [x] [recc link](https://docs.google.com/document/d/1c0MThS9X9EHsgpQmfI_VdSS-tDHIpxEwS5FkzD9FaGE/edit?usp=share_link)

**Comment by RachelF** [comment]
@AKM399 Report drafted, ready for your review. There is one paragraph that still needs to be updated, and I tagged Jonah to validate the data so we can update that piece.
