### ISSUE TITLE
2023 website evaluations - paygap.pif.gov

### ISSUE THREAD

**Issue by AKM399** [GSA/EDX#798]
Website Manager - Dennis Cronyn 
**To Do**
- [ ] Set appointment
- [ ] assigned people
**Progress**
- [ ] Scan
- [ ] [interview notes](https://docs.google.com/document/d/1TRgksmY8HWoUZ4mfOK0--YhWnl00nvYQ-a1OMUp1zqM/edit?usp=share_link)
- [ ] [Interview Spreadsheet](https://docs.google.com/spreadsheets/d/1bn-M2qgS8Wo-a3AYKfFMYc62eLRs60J06FxtTXHViKM/edit?usp=share_link)
**Rec Docs Needed**
- [ ] Summary
- [ ] Tl:Dr
- [ ] immediate action
**Done** 
- [ ] [Analysis](https://docs.google.com/spreadsheets/d/1D1IqdaJLvz8KHqbeYT3rOoY0OH3MAaCrII4fnTXlku0/edit?usp=share_link)
- [ ] [recc link](https://docs.google.com/document/d/1xw3YG2Co2gC1ByQnP5nirkVnmYsRBB_iksn6tmlIW-M/edit?usp=share_link)

**Comment by RachelF** [comment]
@AKM399 this site now redirects to https://presidentialinnovationfellows.gov/ so I think we can delete this from the schedule
