### ISSUE TITLE
Key Talking Points - consistent messaging

### ISSUE THREAD

**Issue by monicas-d** [GSA/EDX#8]
The EDX team members will work sometimes with one another when meeting with stakeholders but not exclusively. Clear and concise talking points will enable consistency when team members speak with key stakeholders about stakeholder priorities, issues, and contributions to enterprise digital experience. There should be a talking point 1-pager for each key stakeholder group (as applicable). For example:

1-OSC
2-GSA-IT
3-TTS
4-FAS

[Talking Points 🔒 ](https://docs.google.com/document/d/1kH5T5Imrg24yPc9GouXQu8Lg3tfqYqFUyXxguA0v1vg/edit?ts=6046b6b9)
[Core EDX Team Deck 🔒 ](https://docs.google.com/presentation/d/1BHck9JPnIdwpWaII3Elf1n0zCG8OsQDqsQzujUrnTaw/edit?ts=60217456#slide=id.gbc9a31e4bd_3_0)

- [ ] Establish canonical source of this information and process for archiving older versions (if necessary)

**Comment by monicas-d** [comment]
https://docs.google.com/document/d/1kH5T5Imrg24yPc9GouXQu8Lg3tfqYqFUyXxguA0v1vg/edit

**Comment by mvogelgesang** [comment]
Recent discussion with Ed centered around audiences.. what kind of messaging needs to go out to various levels of the organization? What information becomes irrelevant or too weedsy at various levels of the organization?

**Comment by monicas-d** [comment]
I recommend we discuss key stakeholders again here, and walk through the "Stakeholder Analysis" tab here as a team tomorrow: https://docs.google.com/spreadsheets/d/1EWQPAvE2zEmoHCU56Nu8ETSBQg63T4IG/edit#gid=739888856

Since scope is not narrowed, we'll want to go through this tab several iterations throughout the change (and smaller changes as well).

**Comment by ryanwoldatwork** [comment]
What does "done" look like for this story?

**Comment by ryanwoldatwork** [comment]
Given there is no `done`, are there specific tasks to highlight here?

Otherwise, I suggest closing long-standing, general guidance type of tickets. 
Definition of done is important, so the work can be defined, assigned, and move.

**Comment by monicas-d** [comment]
As with Help Desk tickets, let's consider this ticket done. It is an iterative process depending on what is going on and we have those conversations at the time in which we need them. Thanks.
