### ISSUE TITLE
error handling, how to bubble up errors from individual facets?

### ISSUE THREAD

**Issue by mvogelgesang** [GSA/EDX#800]
The work in #756 created an error array within each scanFacetReport to capture one or more errors that may have occurred while executing a scan. Generating summary level information maybe valuable so as to inform the user of basic information via the CLI. For example:

```sh
edxcli websites scan -d "mysite.gov,anothersite.gov" -p "edx scan"

mysite.gov Scan Summary
5 facets scanned, 2 errors reported
anothersite.gov Scan Summary
5 facets scanned, 0 errors reported

Scanning 2 website(s)... Scan complete, results written to data/20230330/
```

**Comment by anatecture** [comment]
B to look into

**Comment by anatecture** [comment]
OBE
