### ISSUE TITLE
decommission list april 2023

### ISSUE THREAD

**Issue by anatecture** [GSA/EDX#801]
## Summary

- [ ] fleet2go (mike c., @RachelF)
- [ ] reporting.gov (sharena t, @mvogelgesang @AKM399) 
- [ ] public-sans.digital.gov (dan w., @anatecture) 
- [ ] financeweb (alicia b, @AKM399) 
- [ ] fedspecs (jennifer m, @mvogelgesang)

**Comment by AKM399** [comment]
@AKM399 reping by end of week, report back in issue

**Comment by RachelF** [comment]
https://www.gsa.gov/reference/for-gsa-employees/on-the-go/gsafleet2go is a mobile app... not sure what the next steps are for this issue? @AKM399

**Comment by beharti** [comment]
[FAS Decommissions ](https://docs.google.com/spreadsheets/d/1vITP8PKLpNh1akSTPw50QNd-DdcLTZns3zqnEHBjqaY/edit#gid=820302003)

[Other Decommissions]([url](https://docs.google.com/spreadsheets/d/1vITP8PKLpNh1akSTPw50QNd-DdcLTZns3zqnEHBjqaY/edit#gid=1581146380))
