### ISSUE TITLE
2023 Website Evaluation - itdashboard.gov

### ISSUE THREAD

**Issue by AKM399** [GSA/EDX#810]
Website Evaluation of (site) - (Site manager)
**To Do**
- [x] Set appointment
- [x] assigned people
**Progress**
- [ ] Scan
- [x] [interview notes](https://docs.google.com/document/d/1qB0KauIasqQmAPyWS_tDbwFCLDo0DZuIkep3h9yotSw/edit?usp=share_link)
- [x] [Interview Spreadsheet](https://docs.google.com/spreadsheets/d/17RvOAAeNuNHhoYZnu5OukpEKFXK9VHkFDsEZhFTeYSg/edit?usp=share_link)
**Rec Docs Needed**
- [ ] Summary
- [ ] Tl:Dr
- [ ] immediate action
**Done** 
- [ ] [Analysis](https://docs.google.com/spreadsheets/d/1jOc-Tc0PJtfdIvOkMj9anuGk6H2YpgHq_1zCTwo26qU/edit?usp=share_link)
- [ ] [recc link](https://docs.google.com/document/d/1HlcfFNToeay1TaZjJ8_EdrI1lQ7qmTuhPhilRsk0wew/edit?usp=share_link)

**Comment by RachelF** [comment]
Rachel and Liz completed this interview on 5/10
