### ISSUE TITLE
Product design: tighten Inventory

### ISSUE THREAD

**Issue by anatecture** [GSA/EDX#82]
## Summary

Use USWDS and figma to create prototype of Inventory more balanced and navigable visual design. 

## Additional context and links

https://www.figma.com/file/VCcrrG7WR25vg997n9bdgx/U.S.-Web-Design-System-(USWDS)-2.12.0-Component-library-(Community)?node-id=1078%3A2421

## Checklist

List below the specific actions to be taken

- [x] Find figma library for USWDS
- [x] Build basic model
- [x] Build more navigable, regular layout
- [x] check in on visual evaluation @amstienstra 
- [x] check in on technical evaluation @ryanwoldatwork

**Comment by ryanwoldatwork** [comment]
Next steps are to meet on this. Date TBD.

cc @anatecture, @amstienstra, and @ryanwoldatwork

**Comment by ryanwoldatwork** [comment]
for review:

![websites-show](https://user-images.githubusercontent.com/64987852/140196239-4c175eb1-4a30-4f5a-acb5-a82e134cacbc.png)

**Comment by ryanwoldatwork** [comment]
Maintaining process context by using a modal.

<img width="285" alt="Screen Shot 2021-11-03 at 2 37 29 PM" src="https://user-images.githubusercontent.com/64987852/140196563-4481f681-5722-48ed-95c3-b3e47d5730ef.png">

<img width="931" alt="Screen Shot 2021-11-03 at 2 37 22 PM" src="https://user-images.githubusercontent.com/64987852/140196574-4e97d307-5b0e-4272-9b66-438ec428b47e.png">

**Comment by ryanwoldatwork** [comment]
Updates were shipped today.

https://touchpoints.app.cloud.gov/admin/websites/507, as an example.

**Comment by anatecture** [comment]
Thank you @ryanwoldatwork!
