### ISSUE TITLE
Bulk Lighthouse 

### ISSUE THREAD

**Issue by mvogelgesang** [GSA/EDX#821]
Came across this nom library which proports to scan many pages at once. Could be valuable for whole-site scanning efforts.

https://unlighthouse.dev/

**Comment by AKM399** [comment]
@hursey013 let us know if you want us to look into acquiring this.

**Comment by hursey013** [comment]
> @hursey013 let us know if you want us to look into acquiring this.

It's open source! I am working on a demo to test it out - will share out the results shortly.

**Comment by anatecture** [comment]
idea in search of a use case.
