### ISSUE TITLE
Closing websites the concierge experience

### ISSUE THREAD

**Issue by AKM399** [GSA/EDX#837]
feedback from Ryan Wold:

Site going offline w/in the next six months; taking it offline has been a nightmare.
Ideally we need a concierge experience to help walk WMs through this
If Ryan is having trouble, just think about how tough it is for a “regular” WM
Who is empowered to determine what happens to the content? Must be DC/Board/OSC

**Comment by AKM399** [comment]
can be fleshed out in the lifecycle.  example, learning about redirects, dns stuff, content choices and record keeping.
@hheinrich-gsa, has been tagging sites that should have closed but didn't.

**Comment by anatecture** [comment]
Can't take this one at this time.
