### ISSUE TITLE
Consider making Team Topologies explicit

### ISSUE THREAD

**Issue by ryanwoldatwork** [GSA/EDX#839]
### Idea

Given GSA Websites are Products, Websites should be managed as Products, with Product Teams.
Given GSA Websites are Products used to provide Service and deliver value to users, the broader Service should also be managed.

The organizational structure can be modeled and understood in many ways; an org chart being a common model and artifact.
A Team topology diagram is another way to model and visualize how a team relates to a website and how a website relates to a Service.
A [Business Process Model or Service Blueprint](https://github.com/gsa/service-design-analytics) or Journey Map, etc is another 

* https://teamtopologies.com/key-concepts
* https://scaledagileframework.com/organizing-agile-teams-and-arts-team-topologies-at-scale/
* https://github.com/gsa/service-design-analytics

### Business Value

As an organizational leader/executive/strategist,
I want to see a visual depiction of websites, services, and teams,
So I have increased situational awareness of current state operations,
and so that I can work with others to identify a more ideal future state,
and so that I can support the organization in managing from current to future state.

Example:

![image](https://github.com/GSA/EDX/assets/64987852/1b87ace6-0e86-4243-822a-cde9cbcca06a)

### Definition of Done

* Phase 1 - Model 1 team along with their Websites within a Service
* Phase 2 - Model 3-5 teams along with their Websites within a Service
* Phase 3+ -Model remaining Websites along with their Websites and Services

**Comment by RachelF** [comment]
Interesting @ryanwoldatwork -- curious as to what you see as a deliverable from this?
