### ISSUE TITLE
Q4 websites scans for GSA IT performance metric

### ISSUE THREAD

**Issue by hatfieldjm4** [GSA/EDX#848]
Run the edxcli scans for all sites, filter to only the sites that GSA IT manages, and [report the metrics](https://docs.google.com/spreadsheets/d/1nMq0pg8-5fq19tOC9sgi-IERSRGbC6R_RhsHj3st_8E/edit?usp=drive_web&ouid=115146496854908933924) to IQ, IC, and IP prior to providing updates to Roland Chan.

**Comment by AKM399** [comment]
@hatfieldjm4 please confirm done?
