### ISSUE TITLE
CX CoP planning

### ISSUE THREAD

**Issue by AKM399** [GSA/EDX#849]
- [ ] page update
- [x] August - Jackson Moody prep
- [x] September - TTS on paid respondents
- [ ] October - CX award or Jargon Madness
- [ ] November - CX award or Jargon Madness

**Comment by AKM399** [comment]
TTS comitted and agreed

**Comment by AKM399** [comment]
adding PBS leasing portal to list - has confirmed needs meeting

**Comment by AKM399** [comment]
september - TTS on paid compensation
October - leasing portal
November - jargon maddness

**Comment by AKM399** [comment]
Upcoming Topics
presidential transitions
product management
leasing portal
storytelling from the smithsonian

**Comment by anatecture** [comment]
Complete
