### ISSUE TITLE
Meet with Sam.gov Change/Comms Team

### ISSUE THREAD

**Issue by monicas-d** [GSA/EDX#85]
Just as Gail/I are meeting with the FAS DX change / comms folks to learn their best practices/ lessons learned, Kelly of FAS DX directed us to learn from Sam.gov as they did.

Gail/I will meet with them on 10/29 from 12-1 EST to be led through their "Softening the Landing" deck, and we will share what we learn from them here in the event they have stuff we feel can be used in our work.

**Comment by gailsprinkle** [comment]
@monicas-d Excellent notes! Thank you! We can close.
