### ISSUE TITLE
Stand Up HCD Guides on Digital.gov

### ISSUE THREAD

**Issue by jacksonmoody** [GSA/EDX#852]
## Summary

The HCD guides are currently only available in Google Docs. We should be able to view them on Digital.gov under the new guides template. See issue #850.

## Additional context and links

See issue #850 and the pull requests on the Digital.gov [repository](https://github.com/GSA/digitalgov.gov/pull/6426). 

## Checklist

- [x] Close out issue #850 
- [x] Migrate both parts of the design guide
- [x] Migrate both parts of the discovery guide 
- [x] Test both guides for usability on digital.gov

**Comment by anatecture** [comment]
was able to successfully get all of the technical pull requests for the HCD guides merged! For reference, I have linked them below:

1. [Change how the site is compiled ](https://github.com/GSA/digitalgov.gov/pull/6419)
2. [Add glossary](https://github.com/GSA/digitalgov.gov/pull/6420)
3. [Add side navigation](https://github.com/GSA/digitalgov.gov/pull/6422)
4. [Fix previous/next buttons](https://github.com/GSA/digitalgov.gov/pull/6423)
5. [Create miscellaneous components for guide content](https://github.com/GSA/digitalgov.gov/pull/6424)
6. [Create landing page template](https://github.com/GSA/digitalgov.gov/pull/6425)

The [Digital.gov](http://digital.gov/) team has assured me that they are going to get all of these changes deployed on the main site early next week. For your reference, those changes will happen [in this PR](https://github.com/GSA/digitalgov.gov/pull/6426) (for the technical modifications) and [this PR](https://github.com/GSA/digitalgov.gov/pull/6427) (for the content modifications). If you get any pushback or there are any major roadblocks, feel free to reach out to me at jacksonmoody@college.harvard.edu. I don't start school until the week after next, so happy to help push these across the finish line if necessary!

**Comment by AKM399** [comment]
awaiting digital.gov team to close out last PR

**Comment by RachelF** [comment]
closing; HCD guides have been published
