### ISSUE TITLE
DC - FY23 bi-weekly planning and strategy meetings

### ISSUE THREAD

**Issue by RachelF** [GSA/EDX#863]
## Prep and planning for bi-weekly Digital Council meetings
Meeting prep and follow-up activities.

## Actions - planning meetings
Meet with GSA IT (Peter L) and OSC (Sarah B) the Monday before each Council meeting to:

- identify/confirm topics and speakers for upcoming DC meetings
- finalize agenda
- develop content or read-aheads if needed and share as appropriate

## Actions - strategy meetings
Meet with GSA IT (Peter L) and OSC (Sarah B) the alternate Monday to:

- discuss GSA digital strategy
- identify potential topics/speakers for future meetings
- identify potential projects for DC or working groups to tackle
- strategize on council goals and future direction

**Comment by AKM399** [comment]
closable or just change the title to FY 24?

**Comment by RachelF** [comment]
Let's close this one and create a new one for 2024
