### ISSUE TITLE
Evaluate use of Chrome Extension for providing self service Lighthouse plugin results

### ISSUE THREAD

**Issue by hursey013** [GSA/EDX#866]
## Summary

As a compliment to the CI implementation, the use of a Chrome Extension could provide on-demand, self service Lighthouse audits. This adds additional flexibility to the Lighthouse Plugin to be used by teams not using a Github based site.

## Checklist

List below the specific actions to be taken

- [x] Investigate bootstraping the [official lighthouse extension](https://developer.chrome.com/docs/lighthouse/overview/#extension)
- [x] Investigate feasibility of rolling our own extension to conduct GSA specific audits

**Comment by hursey013** [comment]
Not currently possible to use custom plugin with Chrome devtools Lighthouse or the Lighthouse Chrome extension, as neither have the ability to use plugins directly. It is perhaps something that can be revisited in the future: https://github.com/GoogleChrome/lighthouse/discussions/15131

**Comment by anatecture** [comment]
[Link to extension in chrome webstore](https://chromewebstore.google.com/detail/gsa-edx/inphcfjkfegopafbnfkclnkikkdehjfa)
