### ISSUE TITLE
Goals for CY24 DC Leadership

### ISSUE THREAD

**Issue by anatecture** [GSA/EDX#868]
## Summary

These are the goals for CY24 DC leadership 

1. EBCs for UX and the Content Working Group for funding.
2. Messaging the FY25 change in definition for conformance to 21st Century IDEA to include all our scanned metrics plus customer-centricty.

**Comment by AKM399** [comment]
pending discussion and reconciliation

**Comment by anatecture** [comment]
Goal (1) OBE

Goal (2) requires internal adjustments due to direction and advice from C. Where shall we report these items in preparation for larger-scale, external reporting in 2-3 years

**Comment by anatecture** [comment]
might include these numbers in CY24 [DC Dashboarding project](https://docs.google.com/document/d/1O9iMlPVD6egH7X95dlisDcwe9P_KYlP9oUDNRdjRM4M/edit#heading=h.k07eihuswrb5)

**Comment by RachelF** [comment]
DC work this year is being driven by the DC Roadmap and GSA Administrator priorities, so this issue is OBE; closing.
