### ISSUE TITLE
New Security Control: AC-2: Account Management

### ISSUE THREAD

**Issue by ryanwoldatwork** [GSA/EDX#870]
## Background

A new Security Control has been added to the System Security Plans that impact many GSA software systems.

The new control reads:

> l. Align account management processes with personnel termination and transfer processes.

## Existing Issue References

* https://github.com/GSA/EDX/issues/191
* https://github.com/GSA/EDX/issues/631
* Existing GSA policies related to shared documents (documents are re-assigned upon employee exit)

## User Story

As a GSA System Owner
I want to deactivate all user accounts of exited employees
So that I can satisfy the assertion of Security Control AC-2 (l)

As a GSA System Owner
I want to re-assign ownership and/or permissions to applicable records for exited employees
So that I can satisfy the assertion of Security Control AC-2 (l)

Examples of "applicable records" are digital assets that are delegated authority by the organization,
like a Website, Social Media Account, Mobile Application, feedback Form, Service, or organizational Document.

## Acceptance Criteria

Given an employee leaves the organization 
And given the employee has a user account that is associated with a digital records (by email or user id)
When an employee appears on a separations report as exited or transferred
And the applicable records are identified, in every GSA system
Then the applicable records are re-assigned to at least one active user

**Comment by anatecture** [comment]
@hatfieldjm4 do we have a role here?

**Comment by hatfieldjm4** [comment]
> @hatfieldjm4 do we have a role here?

We do in the sense that we need to remove account access in GitHub if someone leaves. I've removed Mark and Jackson from the EDX repo. I have processes in place to do this in GEAR, too.

**Comment by AKM399** [comment]
don't see a place to assist with implementation.  Suggestion is to work with HR to put in place.
