### ISSUE TITLE
Fall Project - Developing next generation of IT performance metrics

### ISSUE THREAD

**Issue by AKM399** [GSA/EDX#872]
New metrics to push the maturity of 21st century idea act.

Show legacy score and upcoming score.

- [ ] brainstorm next metrics - requesting @hursey013 support - 1 month
- [ ] see if next metrics can be automated - requesting @hursey013  support will require an estimate to see if it can be implemented- 1 month
- [ ] Crit
- [ ] meet with people who may also do metrics to see if we can join forces or use their work- 508 team - no support person requested.  - 2 weeks
- [ ] comms out to website teams  -requesting support from @RachelF - 2 weeks
- [ ] Validate with GSA-IT

Notes:  Brainstorming and automation will run somewhat in parallel 

outside considerations - 
gear contract is ending September 30th - probably needs early October to focus on this
proven optics is also comming and may have schedule impacts

**Comment by AKM399** [comment]
in brainstorming

**Comment by anatecture** [comment]
Spoke w/ @AKM399 about this 11/13/2023. we were thinking that, in addition to the metric, guidance needs to be issued about how to improve those scores. Where might that guidance live? Considering @hursey013's Dev Experience site? Thoughts @hatfieldjm4 @hursey013?

**Comment by anatecture** [comment]
Breakdown of how lighthouse scores work: https://www.debugbear.com/docs/metrics/lighthouse-performance#:~:text=How%20to%20improve,you%27re%20interested%20in

**Comment by AKM399** [comment]
@hatfieldjm4 can we close'?

**Comment by hatfieldjm4** [comment]
Yes, we can. For reference, here is the [writeup](https://docs.google.com/document/d/1V5NNR7PZUl-LYfUUm1-6tYbmWo7uLjGM4w7sDxVb_us/edit#heading=h.xoqfeipcs4i7).
