### ISSUE TITLE
Fall Project -  GSA and Fed-wide Digital Lifecycle Program

### ISSUE THREAD

**Issue by AKM399** [GSA/EDX#873]
## Summary
How might we update the GSA DLP to integrate OMB’s updated 21cIDEA guidance, then generalize it to speak to any worker in any federal agency?

**Policy requirement**: Expand resources on Digital.gov: Within 60 days, GSA, in coordination with OMB and with other relevant interagency bodies and stakeholders, will update Digital.gov to continue to serve as the primary, centralized home for communities, best practices, and resources to help agencies and their respective digital delivery teams with implementation of the 21st Century IDEA.

**Proposal**
1. Complete policy analysis and create a gov-wide generic version of the DLP; publish to digital.gov by the 60-day deadline. 
2. Begin work to adapt the gov-wide version to incorporate GSA-specific guidance.

## After new OMB web policy drops, crosswalk changes - 3 weeks
- [x] Review existing DLP guidance against new policy requirements to identify current state of new policy guidance
- [x] Categorize guidance into policy topic areas.

## Work w/Digital.gov team to update resources to reflect new OMB web policy guidance - 1 week
- [x] Review and update structured content page
- [x] Review accessibility policy "intro" page and update as needed to reflect new policy guidance
- [x] Review analytics policy "intro" page and update as needed to reflect new policy guidance
- [x] Review security policy "intro" page and update as needed to reflect new policy guidance
- [x] Review privacy policy "intro" page and update as needed to reflect new policy guidance
- [x] Review content policy "intro" page and update as needed to reflect new policy guidance
- [x] Review all the "intro" pages that are already published to ensure they properly reflect the new guidance

## Draft content for DLP artifacts - 3 weeks
- [x] Integrate new content into existing DLP framework
- [x] Develop content for generic DLP Launch
- [x] Develop content for generic DLP Manage
- [x] Requesting @hheinrich-gsa help

## Create Excel versions of DLP artifacts - 1 week
- [x] Create new Excel version of go-live checklist
- [x] Submit to Digital.gov for publication

## Other considerations
- RF on vacation last 2 weeks of November
- Annual report to OMB on 21cIDEA needs to be completed by mid-November
- Onboarding new DC co-chair early October
- Working with IT Dashboard to clean up website inventory

End result - One new digital.gov page to host generic DLP content, including a new go-live checklist, genericized for use by any federal agency gov-wide.
Key outcome - Evergreen checklists that link to topical policy guidance pages on Digital.gov

**Comment by RachelF** [comment]
incorporated  https://github.com/GSA/EDX/issues/856; will close that issue

**Comment by RachelF** [comment]
Policy dropped 9/22; began in-depth review and categorization 10/4

**Comment by RachelF** [comment]
completed integration of policy changes into launch/manage content

**Comment by RachelF** [comment]
Closing this because generic go-live checklist was submitted to Digital.gov team for publication by the deadline. Tracking GSA DLP updates in https://github.com/GSA/EDX/issues/919.
