### ISSUE TITLE
Developer experience at GSA

### ISSUE THREAD

**Issue by AKM399** [GSA/EDX#884]
To create a shared understanding across GSA about the specific elements GSA websites must contain. In doing so, establishing a canonical source of information specific to guide GSA developers and providing a channel to communicate updated guidance.

Objectives
Compliant GSA hosting
Assigned web manager
Assigned technical support specialist

Deliverables
Static documentation website
Public GitHub repository
Public GSA subdomain ( developers.gsa.gov)

- [x] Find a place to host the item.  Can be pre-existing, doesn't have to be.  
         - [ ] develop pitch other office on taking the item over.  - 1 weeks requesting @anatecture help
         - [ ] brief web manager on coming product - 2 weeks (one week before and after project) - requesting @hatfieldjm4 help  
         - [ ] brief technical support on expected needs - same two weeks  - requesting @hatfieldjm4 help
- [x] draft content for static website - 1 week
         - [ ] edit content for static website - 1 week - requesting @RachelF help
- [x] design website for optimal CX - 1 week - requesting @anatecture help
- [x] build static website - 4 weeks
- [ ] create and establish public github repo, read me etc  - 1 week - requesting @RachelF for help with github readme
- [ ] gsa-it creates dns record - 12 weeks - requesting @hatfieldjm4 help
- [ ] work with host to provide information - 1 week - requesting @hatfieldjm4 help

week 1.  DNS record.  pitch development   
week 2.  dns record. brief website manager, technical manager
week 3.  draft content for static site
week 4.  edit content
week 5.  work on site design.
week 6.  build site
week 7.  build site
week 8.  build site
week 9. build site
work. 10.  end brief web manager and technical support
week 11.  create and populate public github repo
**fall project cut off**
week 12. work with host to provide information
week 13.  Launch and comms.
Week 14.  Comms

**Comment by hursey013** [comment]
Crit tentatively scheduled for 10/5

**Comment by anatecture** [comment]
Second crit to be scheduled @AKM399

**Comment by AKM399** [comment]
@hursey013 update checklist where appropriate

**Comment by AKM399** [comment]
#909

**Comment by anatecture** [comment]
Complete
