### ISSUE TITLE
Update personal access token for GitHub Workflow (December 2023)

### ISSUE THREAD

**Issue by hatfieldjm4** [GSA/EDX#886]
For the EDXPROJECT_TOKEN to automate the issue workflow (adding it to EDX's Inbox in its Kanban board)
Instructions:

- Click on your user icon at the top right
- Click settings
- Scroll down, click "Developer Settings" on the left side
- Under personal access tokens, click tokens classic
- Click the "For the EDXPROJECT_TOKEN..." link --> Regenerate token (choose 90 days)
- Go back to the EDX GitHub repo
- Go to settings tab --> secrets and variables --> actions --> click the pencil icon on EDXPROJECT_TOKEN --> paste in the API key

**Comment by anatecture** [comment]
Has this been accomplished? is our Kanban being updated?? that's exciting....

**Comment by hatfieldjm4** [comment]
Yes, when you create a new issue in GitHub, you'll notice that it automatically pulls the issue into the inbox. You'll see my name pop up in the logs of the issue as adding it to the inbox kanban lane of the EDX Backlog because it is using my API key to automate that workflow. An example: 
[hatfieldjm4](https://github.com/hatfieldjm4) added this to Inbox in [EDX Backlog](https://github.com/GSA/EDX/projects/1#card-91061907) [last week](https://github.com/GSA/EDX/issues/899#event-10915779687)

**Comment by AKM399** [comment]
confirmed done in thread
