### ISSUE TITLE
OCE article library

### ISSUE THREAD

**Issue by AKM399** [GSA/EDX#887]
I want to create a library of OCE written articles so we are not duplicating efforts, see what we are attempting to convey, and understand where future contributions will have high complementary value.

**Comment by AKM399** [comment]
#388

**Comment by anatecture** [comment]
needs scoping. Might be a worthwhile all-OCE project. Recommend putting it through the [project intake form](https://docs.google.com/forms/d/16nW0NRw83ul4hISdqtsSc4s62wYkh83qGCgBBTbEfHM/edit).

**Comment by anatecture** [comment]
Is this project ongoing? @beharti

**Comment by beharti** [comment]
Closed until further research and staffing is accomplished.
