### ISSUE TITLE
Define responsibilities of content managers/contributors

### ISSUE THREAD

**Issue by RachelF** [GSA/EDX#893]
## Define responsibilities of content contributors
Once we identify technical leads, the next layer of responsibility is the people who develop and contribute content to our websites.
Recommend adding as a potential spring project, to develop a definition of a content manager/contributor, and outline responsibilities for this role.

Clarifying responsibilities around content creation will help GSA improve readability, accessibility, usability of our content and websites.

## Checklist

- [ ] Develop a definition of a content contributor
- [ ] Identify content contributors for each website
- [ ] (add add'l items as we flesh this task out)

**Comment by ADean27** [comment]
Considerations
- differences in goals/capacity to achieve goals at content and site level
- how to align and design metrics and performance plans to account for ability to impact compliance, other digital goals at each level
- content managers - checking boxes for page/doc level compliance (for accessibility, this is where it really counts - catching things that may not show up in scans before they're posted)
- site managers - checking boxes for site-level compliance 
- SES - charged with digital experience, which is vague and org-based from a GSA POV

**Comment by anatecture** [comment]
Closing this issue so it can be pursued in issue 895, linked above.
