### ISSUE TITLE
CX Resource Page - User Testing

### ISSUE THREAD

**Issue by beharti** [GSA/EDX#896]
## Summary

[Customer Experience (CX) Resources](https://preview-insite.gsa.gov/employee-resources/customer-experience-resources#Digital%20experience) GSA Insite page was designed to provide a one stop repository of all related CX topics for GSA employees.  The page offers overview and links to **Communities of Practice, Research & Feedback, Trainings and Digital Experience** products & services.  The MVP has launched on GSA Insite for GSA employee access.   OCE/SD team will conduct user testing to gather insights on usability of site products and make continuous improvements to page with OSC. 

## Additional context and links
1) 13 volunteers have been identified and invited to participate in CX Resources page user testing
2) OCE/SD curated checklist of page content updates for OSC 
3) OCE team assembled to develop project and facilitate testing page content with users, analyze feedback and establish forward actions.
4) Project completion goal: December 2023

**Project Team:**

- Rachel Flagg 
- Behati Hart 
- Aaron Meyers 
- Helen Heinrich
- Genevieve Christensen
- Tosha Pratt
- Darius (OSC)

## Checklist

- [x] OSC (Darius) and OCE (Tosha P.) to complete page content updates - [QA: CX Resources Insite Page checklist](https://docs.google.com/spreadsheets/d/1YuSCG_U_QISYeGf0ajexmCoont2JSKbPYOxrZPIFTic/edit#gid=0) 
- [x] Rachel: Coordinate with Tosha & Darius (OSC) for content page updates.  NOTE - these updates should be completed before user testing.
- [x] Aaron and Helen: Review volunteers credentials for user testing.  Set up interview 1:1 user testing interview dates beginning November 2023
- [x] Behati: Continue developing CX Resource user testing facilitator guide [CX Resources user testing plan.](https://docs.google.com/document/d/1EF8a_lxfVOd0sb2DsNiNsd3aFIPrSOPuDApzugZHYJ0/edit?usp=sharing)
- [x] Behati: Coordinate with team to update UX interview scripts inspired by 18F before November 1 2023 (E.g: [18F Methods - Usability Testing](https://methods.18f.gov/validate/usability-testing/#usability-testing)
- [x] Rachel: Confirm Volunteers and Set up folder on Share Drive to gather related project docs.  [CX User Testing Folder](https://docs.google.com/spreadsheets/d/1XF2Ddz9u8JuwX0hMLZI_ISvL1-iw2sF6HtCMGVgBCWY/edit?usp=sharing)

- [x] Behati: Coordinate with OCE team on user testing dates, identify assigned facilitators and recruit OCE notetakers for scheduled interview dates.

**Comment by beharti** [comment]
[Usability Testing Guide](https://docs.google.com/document/u/0/d/1EF8a_lxfVOd0sb2DsNiNsd3aFIPrSOPuDApzugZHYJ0/edit) - Draft completed for team review

**Comment by anatecture** [comment]
In looking at the interviews conducted thus far (11/13/2023), conclusion made that we have collected good feedback and have enough information to make useful updates. Patterns of needed resources are established, and the scope of this project seems fulfilled. Next step will be to push those updates to OSC for implementation on our CX Resources page. This issue will be commented upon once those updates are live on Insite.

**Comment by beharti** [comment]
Team meeting to review synthesis of responses.
[QA: CX Resource Page][(url](https://docs.google.com/spreadsheets/d/1XF2Ddz9u8JuwX0hMLZI_ISvL1-iw2sF6HtCMGVgBCWY/edit#gid=1765484985))
[CX Resource Page Synthesis](https://docs.google.com/document/d/1uqIV_som1RZ4oM2PTPoGcuFAsRqBCggOi-I5mUJRQSY/edit?usp=sharing)

Next Steps: Handoff QA spreadsheet of recommended edits to OSC.

**Comment by beharti** [comment]
All tasks completed at follow-up meeting with team on 12/12.  Edits heading to OSC.
