### ISSUE TITLE
Managing OCE work

### ISSUE THREAD

**Issue by anatecture** [GSA/EDX#899]
## Summary

Project to map out how to track OCE work.

**Comment by beharti** [comment]
Managing OCE Work - [working document](https://docs.google.com/document/d/1-o0Vy1PqiDN1xoAaCc0Moi-u4fTKVMxMuftvVO6WVoI/edit?usp=sharing)

**Comment by beharti** [comment]
Designed a workshop for team to Crit on 12/13/23

**Comment by anatecture** [comment]
@beharti I believe you've completed this workshop series. Can you confirm and close the issue if yes?

**Comment by beharti** [comment]
Workshop Pt. 1 & 2 concluded on 12/28/23.  Summary of results to OCE leadership from front office team.

[Figjam Board - OCE workshop](https://www.figma.com/file/mntvw1UmEAbMrw27ITH56D/Crit%3A-Structuring-OCE-Wide-Work?type=whiteboard&node-id=0%3A1&t=6h3w97VowjCl4gDr-1)
