### ISSUE TITLE
EDX Comms Plan - in process

### ISSUE THREAD

**Issue by monicas-d** [GSA/EDX#90]
This is our Comms Plan tracker. 

This "issue" does not close until/unless the EDX team concludes all of its work.

We are sharing this issue for transparency so that everyone can view what the comms plan team is working on, when, key audience, key message, etc. We will include separate issues for comms that go out within sprints for comment, and close, linking back to this primary "issue."

https://docs.google.com/spreadsheets/d/1nYgYo8BM1myiXJb8CJoFlzBuGHhyaquGFIT7iyvgOus/edit#gid=0

**Comment by RachelF** [comment]
Per discussion with @patriciacheng, EDX and OCE will collaborate on high-level comms planning going forward. Teams will manage projects separately, but operate under a common high level plan, to ensure EDX reinforces and supports broader OCE goals

**Comment by monicas-d** [comment]
Thanks Rachel. Gail and I were talking this morning, and we should include
before Lynette folds ours into OCE, the DLP plan. We'll discuss in our
meeting later today.


-- 

U.S. General Services Administration

*Monica Suber-Duffy*, GCDF <http://www.cce-global.org/GCDF> and Federal
Internal Coach
<https://insite.gsa.gov/topics/training-and-development/developmental-services/coaching-services>

Organizational Development Consultant
<https://insite.gsa.gov/topics/training-and-development/developmental-services/organizational-development>

GSA  | OHRM Talent Development

Pronouns: She/Her/Hers

Office of Human Resources Management (OHRM)

1800 F St, NW

Washington, DC 20526

Mobile: (202) 701-8197

E-mail: ***@***.***

Join the Yoga & Mindfulness Chatter Group
<https://gsa.my.salesforce.com/_ui/core/chatter/groups/GroupProfilePage?g=0F9t0000000aU0i>,
and see our page on InSite
<https://insite.gsa.gov/topics/training-and-development/continuous-learning/yoga-mindfulness>

Between stimulus and response there is a space. In that space is our power
to choose our response. In that response lies our growth and our
freedom.-Viktor
E. Frankl

<https://insite.gsa.gov/topics/hr-pay-and-leave>

**Comment by RachelF** [comment]
OCE Comms Team met on 1/18 and discussed how best to integrate EDX comms work into overall OCE comms planning. Rachel and Monica are incorporating all EDX comms planning and artifacts into OCE strategic planning and tactical execution, so I'm closing this EDX comms issue and we'll track in https://github.com/GSA/EDX/issues/150.
