### ISSUE TITLE
OHRM Liaison Actions

### ISSUE THREAD

**Issue by anatecture** [GSA/EDX#904]
## Summary

Work with Classifiers to understand more what they’re looking for in Position Descriptions. Maps to Ideas for Actions 3.

## Three tasks for FY2024

- [ ] Interviewing Classifiers and creating a report on findings.
- [ ] Sharing report with Classifiers and their supervisory chain to show the process of research and its potential impact on the office workflow.
- [ ] Producing a report on the defining Website Managers + SES performance element showing the impact on the agency that Classification was integral to

**Comment by AKM399** [comment]
can we generate, or automate, a process for new website managers to get their PD change without gail emailing people?

**Comment by anatecture** [comment]
From OHRM's update in the upcoming weekly report: "OHRM Service Delivery and Customer Experience Improvement Project.  OHRM is conceptually exploring ways to operate more efficiently and improve the customer experience.  To that end, OHRM has engaged with Censeo on a project to specifically focus on modernizing HR service delivery and instituting customer service standards to support consistent delivery of services. This engagement kicked-off at the beginning of Q1 and is expected to conclude by Q4."

**Comment by anatecture** [comment]
Please see the figma board on liaison actions for updates.

**Comment by AKM399** [comment]
does this map to @beharti reframing?

**Comment by anatecture** [comment]
Yes, @AKM399 is correct. I will review figma board this week.
