### ISSUE TITLE
Resume templates

### ISSUE THREAD

**Issue by AKM399** [GSA/EDX#905]
How might we suggest, provide, create, resume templates which usa jobs, or internal resources can house just as examples of formats where the internal system doesn't strip out formatting.

**Comment by AKM399** [comment]
could be a matter of anonymizing submissions we receive.

@anatecture i don't know if theres a here, "here" but tagging you as ohrm liason.

**Comment by anatecture** [comment]
Out of scope. This is a good idea, but not sure if there's a way we can intervene usefully. This is a Monster or USAJOBS issue.
