### ISSUE TITLE
Presidents Management Council CX Challenge 

### ISSUE THREAD

**Issue by beharti** [GSA/EDX#908]
**PMA CX Priority Area Lead Challenge**

OCE Acting CCO discussed President's Management Council Challenge for GSA on CX;  By January 2024 we will challenge each member as follows: [https://docs.google.com/spreadsheets/d/10uG3GMLD1hMLmyGy7KQjO-90jvBmDkEj2oSm4Se15Gc/edit?usp=sharing](url)

- Workstream: (Delivery) Select one delivery item in 2024 you will be personally responsible for, that you will be able to communicate as a service delivery improvement in concrete, meaningful terms by September 2024
- Status: Underway
- Office: A-Suite
- Lead: Katy Kale, Quynh Tran

**Activities to date**

- [ ] PMA CX Challenge; _OCE recommends selecting a core GSA service that aligns with a top traffic site (identified in new 21st Century IDEA reporting)._   

- [ ] CX Challenge Card Brainstorm with GSA Leadership [https://docs.google.com/presentation/d/14daYyRldx40TSJ42-NcsEtauSboi29VhTR46qCwpgNQ/edit?usp=sharing](url)

- [ ] **Background**  VoC Team completed topic related synthesis from  IPSS Support Research on GSA Insites 11/22/23 [https://docs.google.com/document/d/1lUCRYJJIwfkpOf2o8oLmU1K_KK_k2AsOfT08xkdqyRk/edit?usp=sharing](url)
 
**Consideration per Acting CCO**

- [ ] GSA Insites has been identified as project.  Acting CCO seeking OCE Service Designers support.
- [ ] How can Service Design synthesize research and design a pathway for Service Delivery team and Office of Strategic Communications; identify broken links, data inconsistency, OSC guidance and templates, etc.
- [ ] What are the actions that can be taken by each office outside of OSC;  org charts, list of services, consistency in appearance, etc
- [ ] Who would represent GSA project team for this challenge (roles and assigned actions); OSC, OCE, IT/Service Delivery, etc

**Comment by anatecture** [comment]
Is the ask that we redesign Insite in 2024 for the Service Delivery team? Am I reading that correctly?

**Comment by beharti** [comment]
Close per Acting CCO
