### ISSUE TITLE
Onboarding experience 

### ISSUE THREAD

**Issue by anatecture** [GSA/EDX#910]
## Summary

In order to improve the GSA onboarding experience, @beharti and @AKM399 will work with PBS, OMA, OHRM, and GSA IT to better understand how the agency might support credentialing. For more details, please refer to the [project brief.](https://docs.google.com/document/d/1zqjNA_KvxDjarM6yJJ_Wp7tIyn1wJUYzGSvgVXGafUU/edit) 

Current plan:
Aa and B will work together across January, February, and to mid March 2024 to understand stakeholder needs and perspectives. This includes the creation of an interview guide and the administration of design-led interviews w/ each stakeholder. Deliverable is to measurably improve credentialing experience.

**Comment by anatecture** [comment]
[Survey feedback](https://docs.google.com/spreadsheets/d/1UTzk1YCiGGmUw5_N8id1bj3JLm4Kk5Xg_5hh2GSEe5Y/edit#gid=1147192854) regarding current multi-website userflow.

**Comment by AKM399** [comment]
possibly related issues:

#135 
#205 
#183 
#368

**Comment by AKM399** [comment]
[reference material. ](https://docs.google.com/presentation/d/1Cr1o_VIbdbHu0IjP97vDP5nP2BCv8voCkpIMHqecE7k/edit?usp=sharing)

**Comment by AKM399** [comment]
@AKM399 to be discussed in relevant web evaluations, project in review until re-directed to go

**Comment by beharti** [comment]
OHRM Project Lead update 2/2/24 - Senior leadership pushing recommendations to web/content teams.

**Comment by anatecture** [comment]
This project OBE
