### ISSUE TITLE
Incorporate M-23-22 into DLP

### ISSUE THREAD

**Issue by RachelF** [GSA/EDX#919]
Incorporate most recent OMB guidance (M-23-22) into the GSA DLP process and publish updated checklists on InSite.

## Incorporate new policy guidance
- [x] Review new policy guidance and develop new checklist content for each policy area
- [x] Validate updates with program SMEs
- [x] Develop an Excel version for gov-wide use and submit to TTS for publication

## Update GSA DLP artifacts to include GSA-specific guidance
- [x] Edit and publish Launch checklist content
- [x] Edit and publish Management checklist content

**Comment by RachelF** [comment]
Updates to Launch checklist are in process

**Comment by anatecture** [comment]
Are you able to directly convert these updates to the DLP format for gov-wide or is that an entirely new span of work?

**Comment by RachelF** [comment]
@anatecture a new go-live checklist incorporating m-23-22 was published to digital.gov in November, so that's already done.

**Comment by RachelF** [comment]
Checklists updated and published January 26; awaiting a few updates to the DLP page, closing this
