### ISSUE TITLE
From "ownership" to "stewardship"

### ISSUE THREAD

**Issue by monicas-d** [GSA/EDX#92]
@RachelF @gailsprinkle Gail, Rachel, and I discussed 10/13 that if you want to move someone from "ownership" to "stewardship", we should consider messaging out/calling site managers instead _**site stewards**_ (because sometimes they are called site owners).

What are your thoughts around this idea of starting to use that term _**site stewards**_ in writing and verbally to replace site managers and/or site owners?

@anatecture @ryanwoldatwork @AKM399 @hatfieldjm4 @mvogelgesang

**Comment by AKM399** [comment]
What is the suggested work?   Are we proposing to make communication documents consistent or to define these as different roles?  what documents are we making uniform?

**Comment by monicas-d** [comment]
It was an idea by @Gail Sprinkle - CSC ***@***.***> and thought
it would be a nice discussion for the team to consider/think about. No
proposals from us as of now or action to take. Maybe we should mention this
one in the EDX Team Room and delete in GitHub? Let us know your thoughts.
Thanks.


-- 

U.S. General Services Administration

*Monica Suber-Duffy*, GCDF <http://www.cce-global.org/GCDF> and Federal
Internal Coach
<https://insite.gsa.gov/topics/training-and-development/developmental-services/coaching-services>

Organizational Development Consultant
<https://insite.gsa.gov/topics/training-and-development/developmental-services/organizational-development>

GSA  | OHRM Talent Development

Pronouns: She/Her/Hers

Office of Human Resources Management (OHRM)

1800 F St, NW

Washington, DC 20526

Mobile: (202) 701-8197

E-mail: ***@***.***

Join the Yoga & Mindfulness Chatter Group
<https://gsa.my.salesforce.com/_ui/core/chatter/groups/GroupProfilePage?g=0F9t0000000aU0i>,
and see our page on InSite
<https://insite.gsa.gov/topics/training-and-development/continuous-learning/yoga-mindfulness>

Between stimulus and response there is a space. In that space is our power
to choose our response. In that response lies our growth and our
freedom.-Viktor
E. Frankl

<https://insite.gsa.gov/topics/hr-pay-and-leave>

**Comment by ryanwoldatwork** [comment]
Ya, discussing this topic in chat, or making it an agenda item the weekly team meeting makes sense.

Any specific actions or tasks that relate to this, can be tracked as Issues here.
