### ISSUE TITLE
M-23-22 training series

### ISSUE THREAD

**Issue by RachelF** [GSA/EDX#934]
## Provide guidance on M-23-22
Collaborate w/FAS and DC to develop and deliver a series of 45-minute briefings/training sessions on implementing M-23-22 at GSA.
Per Lori D from OHRM, "Training should create opportunities to help people practice what they need to learn/do."

## Additional context and links
[Event proposal from FAS](https://docs.google.com/document/d/1BTMJ_hZgDn06Kr5nYv1baJokDq2iWwMi71ENojOXePY/edit)
[Capacity building](https://docs.google.com/document/d/1JFyU_5eN3tlc6gIEl4uv9zeWbVZRuY62JfkX2VjM3CM/edit#heading=h.k07eihuswrb5) - roadmap deliverable 

## Checklist
- [x] Kick-off planning meeting w/FAS and Jessica M.
- [x] Determine initial topics
- [x] Get buy-in from FAS to expand participation to include Digital CoP
- [x] Develop a deck for the "intro the M-23-22" kick-off
- [x] Firm up topics for future briefings

**Comment by anatecture** [comment]
This is opened up to the entire Digital CoP. First session planned for early march.

**Comment by anatecture** [comment]
We need to ensure that we update the website manager orientation modules if any content in those trainings needs to shift. @RachelF @anatecture will figure this out once the four part series is complete. 
 
[Module 1](https://docs.google.com/presentation/d/1cARLHQejSx1Z022y44HWMKn8Dz2MEkTrKvBIyEINt3Y/edit#slide=id.gcdecbe9995_1_556)
[Module 2](https://docs.google.com/presentation/d/1KACO8TCGQSiiLRdP42PZAIUQ5EJpRXNNhx_yJ8QSjsg/edit#slide=id.g24d2b8079c6_0_1024)

**Comment by RachelF** [comment]
closing; tracking future events in https://github.com/GSA/EDX/issues/966
