### ISSUE TITLE
Onboarding new members to GSA's Digital Council

### ISSUE THREAD

**Issue by RachelF** [GSA/EDX#937]
## Digital Council Onboarding
Process for onboarding new members to the GSA Digital Council.

## Documentation
Onboarding documentation can be found in the [Council management/membership folder](https://drive.google.com/drive/folders/19AmjgLSHyhNH8rYkmWLqDMbfeVEAGUGD)

[Member management guide](https://docs.google.com/document/d/1juTJf87HHtuyygT-PkC8x35aCXTN1YKKj7ib9TqAT88/edit)

[Welcome email for new Council members](https://docs.google.com/document/d/1QSMq63X2AczMpVPwzh7pn-gaihaIcqseqeR6uYL-cZM/edit)

## Checklist
- [ ] Work with current (and departing, if possible) program rep to identify new rep
- [ ] Follow the Member Management Guide to set up the new member with access to group communications channels, files, and meetings.
- [ ] Set up a meet & greet to welcome the new member and onboard them to the DC.

**Comment by anatecture** [comment]
FYSA. Is this documentation or workflow cross-compatible with any other OCE or other office work? Qualtrecs? Surveys?
