### ISSUE TITLE
Improving OCE wide products

### ISSUE THREAD

**Issue by beharti** [GSA/EDX#941]
Joining OCE teams to update internal content and analyze data to improve offerings:

- [x] CX Classroom - research collaboration to review feedback and submit changes for Summer Camp redesign. 
- [x] OCE onboarding guide - front office collaboration to improve new employee experience and redesign checklist 30/60/90 day

All deliverables for March 2024

**Comment by AKM399** [comment]
#728

**Comment by anatecture** [comment]
Let's talk about timeline on these deliverables @beharti. Project spread is thin between now and march.

**Comment by anatecture** [comment]
CX Classroom - research collaboration to review feedback and submit changes for Summer Camp redesign.

- scope: @beharti will turn over draft interview to CX Classroom team. interviews will be undertaken by core team. 

 OCE onboarding guide - front office collaboration to improve new employee experience and redesign checklist 30/60/90 day

- scope: 45 minute conversation

**Comment by beharti** [comment]
**UPDATE**  
- CX Classroom: Interviews underway as of 3/4 and deliverables to 3/15/24
- OCE Onboarding Guide complete

**Comment by beharti** [comment]
Completed all related tasks
