### ISSUE TITLE
FY 24 Website Evaluation sprint 2 - Christy Hermanson

### ISSUE THREAD

**Issue by AKM399** [GSA/EDX#947]
Website Evaluation of fsrs.gov - Christy Hermanson
**To Do**
- [ ] Set appointment
- [ ] assigned people
**Progress**
- [ ] Scan
- [ ] [interview notes](https://docs.google.com/document/d/1BO6yQU6Uu220dqoQn21FaKYVzAxVSl-SOjacwjhFxfA/edit?usp=drive_link)
- [ ] [Interview Spreadsheet](https://docs.google.com/spreadsheets/d/1vp19QQ_iibWiQYSMmuzYE-M6xkHfcoLubsePa9VTYwU/edit?usp=drive_link)
**Rec Docs Needed**
- [ ] Summary
- [ ] Tl:Dr
- [ ] immediate action
**Done** 
- [ ] [recc link](https://docs.google.com/document/d/1JfsiGHQo2swM1ZBUpEqkD-BP3WFA4UARTVf7Y9LNZI4/edit?usp=drive_link)
- [ ] [Analytics Package](https://docs.google.com/spreadsheets/d/1arwmDk_dXze2oCkPanv72gwC7FeLwoMKoYIQ2VwVmME/edit?usp=drive_link)

**Comment by anatecture** [comment]
@beharti could you follow up with the website manager on this? It looks from the evaluation (see link above) that they're ready to decommission but it'll be a bit of a long road. Could you help them out?

**Comment by beharti** [comment]
UPDATE: Sending an email to a 10-day pilot of the Website Decommissioning Decision Guide.  Pilot runs April 1-10 with a joint retrospective session of teams who actively decommissioning and who are considering.  Retros happening 4/10 and 4/12.  Will also reach out directly to the teams identified during the current web evals to walk-thru the guide.

**Comment by beharti** [comment]
Draft of [website decommissioning decision guide.](https://docs.google.com/document/d/15GS3d34r9PemQRGfiBbPwDCJwnFkpJRyAXK7jXnlqcI/edit?usp=sharing)

Next Steps:

 - Analyze feedback from retro and pilot teams by 4/16
 - Update guide and generalize for digital.gov
 - Coordinate with OSC rep for next steps
