### ISSUE TITLE
FY 24 website evaluation sprint 2 Daniel Williams

### ISSUE THREAD

**Issue by AKM399** [GSA/EDX#948]
Website Evaluation of v1.designsystem.digital.gov - Daniel Williams
**To Do**
- [ ] Set appointment
- [ ] assigned people
**Progress**
- [ ] Scan
- [ ] [interview notes](https://docs.google.com/document/d/1OsPh9-kLRX7rNvRP-XUj1JvOPVgV9PveN5RLtVJFGlM/edit?usp=drive_link)
- [ ] [Interview Spreadsheet](https://docs.google.com/spreadsheets/d/1DmEiDlmq09Mqb4VIfI-HmxvnZX4Scs4RePMNXIdskv4/edit?usp=drive_link)
**Rec Docs Needed**
- [ ] Summary
- [ ] Tl:Dr
- [ ] immediate action
**Done** 
- [ ] [recc link](https://docs.google.com/document/d/1PmirJNKZ50fxwDj9g_K9WOXTZ3wu2O2NgS-b8tPhhSQ/edit?usp=drive_link)
- [ ] [Analytics Package](https://docs.google.com/spreadsheets/d/1q3v3SlK-aymWKPb4uw0a3yJitm4yqD1glUVAp-9Z7iI/edit?usp=drive_link)

**Comment by anatecture** [comment]
@beharti please reach out to website manager for decommissioning. This is a situation where the team wants to decomm, but the task just keeps getting pushed down their to-do list. Take the lead here so they can complete.

**Comment by beharti** [comment]
UPDATE: Sending an email to a 10-day pilot of the Website Decommissioning Decision Guide. Pilot runs April 1-10 with a joint retrospective session of teams who actively decommissioning and who are considering. Retros happening 4/10 and 4/12. Will also reach out directly to the teams identified during the current web evals to walk-thru the guide.

**Comment by beharti** [comment]
Draft of [website decommissioning decision guide.](https://docs.google.com/document/d/15GS3d34r9PemQRGfiBbPwDCJwnFkpJRyAXK7jXnlqcI/edit?usp=sharing)

**Next Steps:**

- [ ] - Analyze feedback from retro and pilot teams by 4/16
- [ ] - Update guide and generalize for digital.gov
- [ ] - Coordinate with OSC rep for next steps
