### ISSUE TITLE
FY 24 website evaluation - sprint 2 Hyon Kim

### ISSUE THREAD

**Issue by AKM399** [GSA/EDX#954]
Website Evaluation of dashboard.data.gov - Hyon Kim
**To Do**
- [ ] Set appointment
- [ ] assigned people
**Progress**
- [ ] Scan
- [ ] [interview notes](https://docs.google.com/document/d/1aDVYQjKmtQlafCKrxBIija0kLZnsPNNDFHUQZV3VFfw/edit?usp=drive_link)
- [ ] [Interview Spreadsheet](https://docs.google.com/spreadsheets/d/1sLKPsF2ylLuN7TX0SWsUzBiY4RFLMsJrwwQ_oTs7f7I/edit?usp=drive_link)
**Rec Docs Needed**
- [ ] Summary
- [ ] Tl:Dr
- [ ] immediate action
**Done** 
- [ ] [recc link](https://docs.google.com/document/d/1l8WqefOoNkFnOkNwq7W0ijrstF4C6d9Tc-oEX5AjZWY/edit?usp=drive_link)
- [ ] [Analytics Package](https://docs.google.com/spreadsheets/d/15NNghVN3rtU0fDiB690fnQHKtPwcpQ-jBTj6L-qbex4/edit?usp=drive_link)

**Comment by anatecture** [comment]
This site is a redirect; eval not required. Website registry shows it decommissoned
