### ISSUE TITLE
Training for SES and web managers

### ISSUE THREAD

**Issue by monicas-d** [GSA/EDX#97]
Gail and Monica will work with The Lab at OPM (and Boris Arratia) to develop training for web managers and SES.

- [ ] We will meet and brainstorm our ideas for content.
- [ ] We will meet with Boris to hear what he has developed thus far, and see how we can work together on this project.
- [ ] We will share our progress reports with Ana in our weekly meetings and ask her questions or gather feedback from her.
- [ ] We will develop an outline by 11/19 of what that training could entail.
- [ ] We will meet with a sample of web managers and SES in December to gather their feedback.

**Comment by AKM399** [comment]
@patriciacheng our github issue on training provided by EDX, to be cross referenced in capacity building plan

**Comment by monicas-d** [comment]
@anatecture @AKM399 I think you mentioned you're working with Lynette now on this. Is that correct? Thanks.

**Comment by anatecture** [comment]
That's correct @monicas-d

**Comment by anatecture** [comment]
[Latest scoping document](https://docs.google.com/document/d/1pGPMpjYuFP8TiwMlmZARLjUBSMWyfCQn/edit) from the Lab with OCE edits.

**Comment by monicas-d** [comment]
Sounds good. Thanks! Please let me know if I can help you all in any way since I'm in the training consultation branch of TD/OHRM.

**Comment by anatecture** [comment]
Issue super ceded by [Issue 163](https://github.com/GSA/EDX/issues/163). Closing this issue.
