### ISSUE TITLE
Develop t-shirt size estimates for "Other" login systems

### ISSUE THREAD

**Issue by ryanwoldatwork** [GSA/EDX#98]
* [ ] email website owners for Websites that have "other" Login systems
* [ ] have a conversation with each Website Manager about existing plans for the web property and its login system
* [ ] create notes for each web property
* [ ]

**Comment by AKM399** [comment]
Why?  Where does it fit?  @AKM399 bring to meeting next week

**Comment by anatecture** [comment]
Thoughts on this issue, given the ICAM work @ryanwoldatwork @mvogelgesang?
